### ISSUE TITLE
V4 cli does not respect --config

### ISSUE THREAD

**Issue by KirkOTL** [serverless/serverless#12505]
### Are you certain it's a bug?

- [X] Yes, it looks like a bug

### Is the issue caused by a plugin?

- [X] It is not a plugin issue

### Are you using the latest v3 release?

- [X] Yes, I'm using the latest v3 release

### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Issue description

we have 2 config files, serverless.yml & serverless_deploy.yml

serverless.yml is for local development, we also used plugin serverless_offline 
serverless_deploy.yml is for CI/CD deployment and we don't need serverless_offline

when we run `serverless deploy --stage $SERVERLESS_STAGE --config serverless_deploy.yml`

seems the serverless.yml has been used, so the bitbucket pipeline return below error

`Serverless plugin "serverless-offline" not found. Make sure it's installed and listed in the "plugins" section of your serverless config file. Run "serverless plugin install -n serverless-offline" to install it.
ServerlessError2: Serverless plugin "serverless-offline" not found. Make sure it's installed and listed in the "plugins" section of your serverless config file. Run "serverless plugin install -n serverless-offline" to install it.
    at PluginManager.resolveServicePlugins (file:///root/.serverless/releases/4.0.23/package/dist/sf-core.js:668:3133)`

we tried to run with serverless@3.38.0 and it is working fine

### Service configuration (serverless.yml) content

```yaml
N/A
```

### Command name and used flags

serverless deploy --stage $SERVERLESS_STAGE --config serverless_deploy.yml

### Command output

```shell
N/A
```

### Environment information

```shell
N/A
```

**Comment by paulalex** [comment]
I cannot get a single build to pass this morning, even a build that went out yesterday afternoon now fails saying it cannot find the config.

**Comment by dfrechdev** [comment]
We have the same issue since the 4.0 release yesterday. Currently we are reverting back to serverless@3.38.0, in order to get our builds passed.

**Comment by paulalex** [comment]
> We have the same issue since the 4.0 release yesterday. Currently we are reverting back to serverless@3.38.0, in order to get our builds passed.

I have done the same, currently pinned to `3.38.0` but I was not expecting to have to do anything.

**Comment by garethmcc** [comment]
Thanks for reporting the issue. We are looking into it.

**Comment by garethmcc** [comment]
We have a fix for this to be released soon. Thanks again for letting us know and the patience while we work on resolving things.

**Comment by ac360** [comment]
Should be fixed in https://github.com/serverless/serverless/releases/tag/4.0.24

Run `serverless update` to get the latest version.

**Comment by fabianobonomini** [comment]
> Should be fixed in https://github.com/serverless/serverless/releases/tag/4.0.24
> 
> Run `serverless update` to get the latest version.

I am using that version this morning. still have the issue
`ServerlessError2: Serverless plugin "serverless-offline" not found.` even if I have the install command on the CI/CD

**Comment by richard-stafflink** [comment]
@fabianobonomini You wouldn't happen to be using yarn/npm workspaces, and attempting to deploy one of the packages?

**If so**, I found that V4 only resolves the `node_modules` in the package directory, not the root `node_modules`.
One hack is to symlink the `node_modules/serverless-offline` to `packages/<your-package-directory-name/node_modules`

**Comment by ac360** [comment]
@fabianobonomini We just pushed out another version with additional fixes.
