### ISSUE TITLE
Serverless standalone installation is broken

### ISSUE THREAD

**Issue by krizon** [serverless/serverless#12510]
### Issue description

As of today some deploy pipelines are broken that use the standalone installation of serverless.

Reason is that the standalone install script gives a 404 (https://slss.io/install which redirects to https://raw.githubusercontent.com/serverless/serverless/main/scripts/pkg/install.sh).

Standalone installation was previously supported and documented on https://serverless.com/framework/docs-install-standalone but this page is removed and the getting started docs are updated (since yesterday): https://github.com/serverless/serverless/commit/d7a0f909574cc169e7357c3f636ce0ff4f64835d#diff-31bcba2ccafa41d46fbbd6d1219f7f1e3b1fb3cad9faa8e4dc521bbb579dd7b3

We probably missed some announcements but opening this bug report to validate this.

### Context

`curl -o- -L https://slss.io/install | VERSION=3.38.0 bash` gives 404.

**Comment by randomhash** [comment]
https://raw.githubusercontent.com/serverless/serverless/main/scripts/pkg/install.sh
Also missing

**Comment by krizon** [comment]
I see the slss.io link was updated to https://install.serverless.com in  https://github.com/serverless/serverless/commit/98abc5104e69391fd6aeadd920eac96a0a213076.

We already migrated some pipelines to the preferred npm install but using https://install.serverless.com might provide a quickfix for now for those running into the same issue.

And still wondering if the deprecation of slss.io/install was announced somewhere because I can imagine quite some people having this in their pipelines as it was in the docs for years as a supported method.

**Comment by rowanmanning** [comment]
Just to link issues together, this is currently a problem for anyone using the Serverless CircleCI orb https://github.com/CircleCI-Public/serverless-framework-orb/issues/51

**Comment by salemgolemugoo** [comment]
Installation script was removed here. CircleCI orb is using main branch
https://github.com/serverless/serverless/commit/bb55e0b38c30348c3284bbdba672b97cf18f3d39#diff-9179b872eb24fa9f9fef69399fe29ce90ccabbdb8dc6bc5229aea8b3cea3e0c4

**Comment by garethmcc** [comment]
As an alternative, use can be made of the following URL that points at the old install script: https://raw.githubusercontent.com/serverless/serverless/v3/scripts/pkg/install.sh

**Comment by alekgosk** [comment]
For anyone having issues deploying via CircleCI, as a workaround you can pin your serverless-framework orb to version `2.0.0` temporarily if you need to ship something quickly:

<img width="1454" alt="Screenshot 2024-05-22 at 12 52 31" src="https://github.com/serverless/serverless/assets/128028373/db24645e-d26b-43df-8868-19b2cc71097a">

**Comment by salemgolemugoo** [comment]
If you guys need a quick fix, i've published a new version to my circleci registry. You can use it like this:
```
version: 2.1

orbs:
  node: circleci/node@5.1.0
  serverless-framework: salemgolemugoo/serverless-framework@dev:issue-51

jobs:
  deploy:
    docker:
      - image: cimg/base:2023.06
    steps:
      - checkout
      - node/install:
          node-version: '14.21.3'
      - serverless-framework/setup
```

> [!CAUTION]
> You need to disable "Orb Security Settings" in "Organization Settings -> Security"

**Comment by batovpasha** [comment]
Other quick fix option, install it globally using npm/yarn:
```
yarn global add serverless
```
or
```
npm i -g serverless
```

**Comment by Mmarzex** [comment]
Hey everyone, apologies this was an issue, we had some trouble getting our url shortener to redirect correctly. I have managed to fix this and `https://slss.io/install` should be working again which hopefully means your issues should be resolved.

**Comment by freitasjuciel** [comment]
issue still happens for me on Circle CI, using the lastest orb and also de old ones
![image](https://github.com/serverless/serverless/assets/7970477/71ea0bfe-74e6-43e7-9b82-b932b5e8e751)

**Comment by Mmarzex** [comment]
@freitasjuciel Can you provide any other logs, the script is available at the url you have set in the `install_url` variable, so not sure what would be up still.
