### ISSUE TITLE
V4: dev mode throws error when function invoked

### ISSUE THREAD

**Issue by garethmcc** [serverless/serverless#12535]
### Issue description

After running `serverless dev` on a simple service, running `serverless invoke` on a function in the service or invoking it by making an HTTP request causes dev mode to fail with an error. Full `serverless support` output in Context below.

Error received:
```
Error: Cannot find module '/opt/sls-sdk-node'
Require stack:
- internal/preload
    at Module._resolveFilename (node:internal/modules/cjs/loader:1143:15)
    at Module._load (node:internal/modules/cjs/loader:984:27)
    at internalRequire (node:internal/modules/cjs/loader:174:19)
    at Module._preloadModules (node:internal/modules/cjs/loader:1574:5)
    at loadPreloadModules (node:internal/process/pre_execution:723:5)
    at setupUserModules (node:internal/process/pre_execution:203:5)
    at prepareExecution (node:internal/process/pre_execution:159:5)
    at prepareMainThreadExecution (node:internal/process/pre_execution:54:10)
    at node:internal/main/run_main_module:11:19 {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ 'internal/preload' ]
}

Node.js v20.12.2

✖ ENOENT: no such file or directory, open '/tmp/sls_3329370.json'
Error: ENOENT: no such file or directory, open '/tmp/sls_3329370.json'
```

### Context

# Service Overview
- Serverless Framework Version: 4.0.26
- Service Config File: serverless.yml
- Service Name: test-http-api2
- Service App: test-http-api
- Service Runtime: nodejs20.x
- Service Stage: dev
- Service Region: us-east-1
- Command: invoke --function hello2

## Service Path
/home/garethm/Projects/testing/test-http-api

## Service Config
```
org: xxx
app: test-http-api
service: test-http-api2
provider:
  timeout: 20
  name: aws
  stage: dev
  runtime: nodejs20.x
  deploymentBucket: 
    name: xxxxxxxx
functions:
  hello2:
    handler: handler.hello
    events:
      - http:
          method: get
          path: /
```

**Comment by senghuotlay** [comment]
i am getting the exact same error

**Comment by senghuotlay** [comment]
i am getting the exact same error

**Comment by gsavvidis96** [comment]
Same here

**Comment by ac360** [comment]
There is a conflict with dev mode in V4 and our observability product. We are working on a fix. ETA is ~1.5 days.

**Comment by austencollins** [comment]
Fixed in https://github.com/serverless/serverless/releases/tag/v4.0.34

**Comment by lorenwest** [comment]
Just installed serverless v4 `npm i -g serverless` and am getting this same error.  Performed a `serverless update` to get the latest 4.1.4

Does this require 4.0.34, or is the fix also in 4.1.4?

Thank you

Context:

# Service Overview
- Serverless Framework Version: 4.1.4
- Service Config File: serverless.yml
- Service Name: mc-serverless
- Service App: mc-serverless
- Service Runtime: nodejs20.x
- Service Stage: dev
- Service Region: us-east-1
- Command: dev --stage dev

## Service Path
...

## Service Config
```
org: ...
app: ...
service: ...
plugins:
  - serverless-domain-manager
custom:
  customDomain:
    domainName: 'api-${sls:stage}...'
    certificateName: '...'
    basePath: ''
    stage: ${sls:stage}
    autoDomain: true
    createRoute53Record: true
    endpointType: regional
    apiType: http
    x_allowPathMatching: true # Only for one deploy
provider:
  name: aws
  deploymentMethod: direct
  architecture: arm64
  runtime: nodejs20.x
  iam:
    role:
      statements:
        ...
   environment:
    RUN_STAGE: ${sls:stage}
functions:
  api:
    handler: index.handler
    memorySize: 1024
    events:
      - httpApi: '*'
```

**Comment by austencollins** [comment]
@lorenwest Should be fixed. But if you saw this in `4.1.4` we better give it another look. @eahefnawy could you check this out pls?

**Comment by lorenwest** [comment]
The actual stack trace is a little different.  Maybe this will help:
```
─ node:internal/modules/cjs/loader:1147
  throw err;
  ^

Error: Cannot find module '/opt/sls-sdk-node'
Require stack:
- internal/preload
    at Module._resolveFilename (node:internal/modules/cjs/loader:1144:15)
    at Module._load (node:internal/modules/cjs/loader:985:27)
    at internalRequire (node:internal/modules/cjs/loader:175:19)
    at Module._preloadModules (node:internal/modules/cjs/loader:1582:5)
    at loadPreloadModules (node:internal/process/pre_execution:731:5)
    at setupUserModules (node:internal/process/pre_execution:172:3)
    at prepareExecution (node:internal/process/pre_execution:132:5)
    at prepareMainThreadExecution (node:internal/process/pre_execution:55:10)
    at node:internal/main/run_main_module:11:19 {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ 'internal/preload' ]
}

Node.js v20.10.0
← λ api
```

**Comment by lorenwest** [comment]
I just updated to 4.1.7, and still cannot run serverless in dev mode.  It starts, but when I send any traffic to it, the following error occurs. Am I doing something wrong?

```
✔ Connected (Ctrl+C to cancel)

→ λ api ── aws:apigateway:v2:get:/status
─ node:internal/modules/cjs/loader:1147
  throw err;
  ^

Error: Cannot find module '/opt/sls-sdk-node'
Require stack:
- internal/preload
    at Module._resolveFilename (node:internal/modules/cjs/loader:1144:15)
    at Module._load (node:internal/modules/cjs/loader:985:27)
    at internalRequire (node:internal/modules/cjs/loader:175:19)
    at Module._preloadModules (node:internal/modules/cjs/loader:1582:5)
    at loadPreloadModules (node:internal/process/pre_execution:731:5)
    at setupUserModules (node:internal/process/pre_execution:172:3)
    at prepareExecution (node:internal/process/pre_execution:132:5)
    at prepareMainThreadExecution (node:internal/process/pre_execution:55:10)
    at node:internal/main/run_main_module:11:19 {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ 'internal/preload' ]
}

Node.js v20.10.0
← λ api
```

**Comment by austencollins** [comment]
@lorenwest This issue is caused by Serverless Framework Dashboard's observability SDK currently having a conflict with how Dev Mode works. We are addressing that, but in the interim, recent versions of the Framework include another solution. That is to simply to turn off observability in lower level environments via the `stages` property.

Please try adding a `stages` property to your configuration, and setting the following so that you can have observability on in your production stage, but off in your lower-level stages, like `dev`, which is what Dev Mode is intended to be used with.

```yaml
# serverless.yml

stages:
  prod: # Rename to whatever your production Stage is to ensure Observability is enabled.
    observability: true
  default: # This will disable observability for every Stage other than your production Stage.
    observability: false 
```

This observability config only affects the AWS Lambda functions within this Service.

As long as observability is disabled in the Stage you are running Dev Mode with, you should no longer see this issue.

**Comment by eahefnawy** [comment]
I just tested this again, and it works as expected. Remember that observability is now opt-in, so you must set the observability property as suggested by @austencollins above. When you run in dev mode, observability will be disabled even if it is set to true for that stage.

**Comment by lorenwest** [comment]
Thank you @austencollins - that works as advertised.

Dev mode is super useful!

**Comment by austencollins** [comment]
Great to hear. Lots more coming for Dev Mode!

**Comment by lorenwest** [comment]
Oh yeah, SocketIO to my IDE and we'll be stepping through lambda lines in no time. 

AWS will love the long lived executions, come billing time :)

**Comment by dornickstudios** [comment]
same error continue :(  i can't work on dev. I use with ts.

**Comment by skierkowski** [comment]
@dornickstudios can you provide more context? After seeing the error run `serverless support --summary` and share the output here.

**Comment by dave-hf** [comment]
Hello. I am getting the same error too. its pretty frustating. (Also using ts) 
Serverless ϟ Support

This generates a report from your last Serverless Framework command (including any errors) to use for Github Issues, debugging w/ AI, or creating a support ticket w/ Serverless Inc.

Summary Report -----------------

# Service Overview
- Serverless Framework Version: 4.1.22
- Command:  

# Service Overview
- Serverless Framework Version: 4.1.21
- Service Config File: lambda.yml
- Service Name: mainThreads
- Service App: conversaly-api
- Service Runtime: nodejs20.x
- Service Stage: dev
- Service Region: us-east-1
- Command: deploy --config mainThreads/lambda.yml

## Service Config
```
# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: neuralcreative
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: conversaly-api
# "service" is the name of this project. This will also be added to your AWS resource names.
service: mainThreads
provider:
  name: aws
  runtime: nodejs20.x
functions:
  getAssistantReply:
    handler: handler.getAssistantReply
```

# Service Overview
- Serverless Framework Version: 4.2.4
- Service Config File: serverless.yml
- Service Name: conversaly-mainThreads
- Service App: conversaly
- Service Runtime: nodejs20.x
- Service Stage: dev
- Service Region: us-east-1

## Command
dev --config src/mainThreads/serverless.yml,--stage dev

## Service Config
```
# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: neuralcreative2
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: conversaly
# "service" is the name of this project. This will also be added to your AWS resource names.
service: conversaly-mainThreads
provider:
  name: aws
  region: us-east-1
  runtime: nodejs20.x
  timeout: 25
  stage: ${opt:stage, 'dev'}
  stackName: ${self:service}-${self:provider.stage}-stack


stages:
  prod:
    observability: true
  dev:
    observability: false
  default:
    # Disabales observability in all other stages
    observability: true

functions:
  processTools: 
    name: ${self:service}-${self:provider.stage}-processTools
    handler: processTools/handler.processTools
    events:
      - httpApi:
          method: post
          path: /processTools
          authorizer:
            type: aws_iam
    environment:
      
  getAssistantReply:
    name: ${self:service}-${self:provider.stage}-getAssistantReply
    handler: handler.getAssistantReply
    events:
      - httpApi:
          method: post
          path: /getAssistantReply
          authorizer:
            type: aws_iam
    environment:
      DEVSESSION: "false"
      RUN_STAGE: ${sls:stage}

**Comment by diestrin** [comment]
This is also happening to me:

```
─ node:internal/modules/cjs/loader:1051
  throw err;
  ^

Error: Cannot find module '/opt/sls-sdk-node'
Require stack:
- internal/preload
    at Module._resolveFilename (node:internal/modules/cjs/loader:1048:15)
    at Module._load (node:internal/modules/cjs/loader:901:27)
    at internalRequire (node:internal/modules/cjs/loader:166:19)
    at Module._preloadModules (node:internal/modules/cjs/loader:1420:5)
    at loadPreloadModules (node:internal/process/pre_execution:678:5)
    at setupUserModules (node:internal/process/pre_execution:162:3)
    at prepareExecution (node:internal/process/pre_execution:124:5)
    at prepareMainThreadExecution (node:internal/process/pre_execution:47:3)
    at node:internal/main/run_main_module:10:1 {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ 'internal/preload' ]
}

Node.js v20.6.1
```

**Comment by dave-hf** [comment]
Any news ? Someone figured out how to fix ?

**Comment by eahefnawy** [comment]
Hi @dave-hf and @diestrin thank you for reporting this again. I just tried it and I was able to reproduce it.

While we did fix this, it seems that recent changes in handling observability settings caused a regression. We're working on a fix.

I'll reopen this issue until it is fixed.

**Comment by czubocha** [comment]
Hey, this should be fixed now in [v4.4.6](https://github.com/serverless/serverless/releases/tag/v4.4.6.) Feel free to reopen the issue if you still run into this problem.

**Comment by mordka** [comment]
If anyone is still experiencing this issue I recommend disabling observability in dev stage:

```
stages:
  prod:
    observability: true
  default:
    observability: false
```
