### ISSUE TITLE
Serverless4: Unable to Ensure that the Prisma libquery Engine and schema.prisma are Included in my Bundle

### ISSUE THREAD

**Issue by NicoHinderling** [serverless/serverless#12552]
### Issue description

Hello,

This is perhaps more of an issue with how the `package.patterns` fields play with esbuild but anyways...

So I've resolved basically all my issues except two:

1. The bundler step gets rid of the `libquery_engine-xxxx.so.node` file that we need for running Prisma
2. The bundler also gets rid of the `schema.prisma` file (which is also required)

The serverless3 deploy we currently have active has a `node_modules` folder which includes `.prisma`:

![image](https://uploads.linear.app/ca066160-e400-4ed9-98d8-d8fef15dbdf2/63179a35-9fb6-415b-be9c-eeac0dde0f90/5edcf4dc-47b4-43fd-a62e-ea6d696f4a81?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2NhMDY2MTYwLWU0MDAtNGVkOS05OGQ4LWQ4ZmVmMTVkYmRmMi82MzE3OWEzNS05ZmI2LTQxNWItYmU5Yy1lZWFjMGRkZTBmOTAvNWVkY2Y0ZGMtNDdiNC00M2ZkLWE2MmUtZWE2ZDY5NmY0YTgxIiwiaWF0IjoxNzE2OTk0NDYwLCJleHAiOjMzMjg3NTU0NDYwfQ.DnUV4Uvn9fVfwhlAPZoE9WcJsrLUTEXlpRMJMTK_LMs)

When I attempt to generate my package with serverless4 though, this is what I get:

![image](https://uploads.linear.app/ca066160-e400-4ed9-98d8-d8fef15dbdf2/92f4d2f9-a5b4-4638-862b-c949e648b79f/800d5731-d0cb-46c6-9dc3-e0bd33144275?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2NhMDY2MTYwLWU0MDAtNGVkOS05OGQ4LWQ4ZmVmMTVkYmRmMi85MmY0ZDJmOS1hNWI0LTQ2MzgtODYyYi1jOTQ5ZTY0OGI3OWYvODAwZDU3MzEtZDBjYi00NmM2LTlkYzMtZTBiZDMzMTQ0Mjc1IiwiaWF0IjoxNzE2OTk0NDYwLCJleHAiOjMzMjg3NTU0NDYwfQ.f4yCbsGI6-PEfWlQYvBRoJ5c5RfZL8yHduldpZcSgNc "=789x")

With the following esbuild config:

![image](https://uploads.linear.app/ca066160-e400-4ed9-98d8-d8fef15dbdf2/57794654-5bde-45bb-bf19-7f4c0484c5f2/7e612e5a-30fe-449d-b53d-49a68aaef81e?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2NhMDY2MTYwLWU0MDAtNGVkOS05OGQ4LWQ4ZmVmMTVkYmRmMi81Nzc5NDY1NC01YmRlLTQ1YmItYmYxOS03ZjRjMDQ4NGM1ZjIvN2U2MTJlNWEtMzBmZS00NDlkLWI1M2QtNDlhNjhhYWVmODFlIiwiaWF0IjoxNzE2OTk0NDYwLCJleHAiOjMzMjg3NTU0NDYwfQ.1u_HYM88MNw7ghgORo68apgSMCWAmsMTEcnG3jJ0UjI)

What's confusing is that in the "Advanced Configuration" section of the [serverless-esbuild docs](https://www.serverless.com/plugins/serverless-esbuild), I see two things that don't seem to carry over well for serverless4:

1. `Serverless Package Configuration will behave in the same way as native packaging. You can use patterns, include and exclude to include extra files into your bundles.`
   When I try specifying something like this:

```
package:
  patterns:
    - 'node_modules/.prisma/**'
    - 'node_modules/prisma/**'
    - 'node_modules/@prisma/**'
    - 'node_modules/.prisma/client/schema.prisma'
    - 'node_modules/.prisma/client/libquery_engine-*'
    - 'schema.prisma'
    - 'libquery_engine-*'
```

I see no difference in output for the `node_modules` files 😞

2. When I try using the `packagerOptions` option for esbuild to run some additional scripts

![image](https://uploads.linear.app/ca066160-e400-4ed9-98d8-d8fef15dbdf2/562f0981-05c4-49b2-98d0-5fcbf9dbb550/22d09c26-3fea-420c-b35b-5d51c4f749ed?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2NhMDY2MTYwLWU0MDAtNGVkOS05OGQ4LWQ4ZmVmMTVkYmRmMi81NjJmMDk4MS0wNWM0LTQ5YjItOThkMC01ZmNiZjlkYmI1NTAvMjJkMDljMjYtM2ZlYS00MjBjLWIzNWItNWQ1MWM0Zjc0OWVkIiwiaWF0IjoxNzE2OTk0NDYwLCJleHAiOjMzMjg3NTU0NDYwfQ.Bt6gRZoJX-ILgg8H062w8lymXkwgjhBmU7JOIWGXsa4)

I get the following error:

![image](https://uploads.linear.app/ca066160-e400-4ed9-98d8-d8fef15dbdf2/81ec9ca3-3edf-49ad-bff3-aa1771eebda5/3ef6852f-557c-44c5-b9a6-80b9d5e90ce6?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2NhMDY2MTYwLWU0MDAtNGVkOS05OGQ4LWQ4ZmVmMTVkYmRmMi84MWVjOWNhMy0zZWRmLTQ5YWQtYmZmMy1hYTE3NzFlZWJkYTUvM2VmNjg1MmYtNTU3Yy00NGM1LWI5YTYtODBiOWQ1ZTkwY2U2IiwiaWF0IjoxNzE2OTk0NDYwLCJleHAiOjMzMjg3NTU0NDYwfQ.mQBQXX8IbT1VeqhzWPRxfVgE1XoCj6Oe-yQp_suOIsw "=765x")

#1 is definitely the more important issue for me, howecer I raise #2 as I was inspired by [this comment](https://github.com/prisma/prisma/issues/18858#issuecomment-1517597032) suggesting to do the copies manually. I'd love to avoid it but open to all options haha 🙏 . Let me know if I've done anything wrong config wise!

### Context

# Service Overview

* Serverless Framework Version: 4.0.30
* Service Config File: serverless.yml
* Service Name: internalSlackbot
* Service Runtime: nodejs20.x
* Service Stage: dev
* Service Region: us-west-1
* Command: package

## Service Config

```
service: internalSlackbot
projectDir: ../../
frameworkVersion: '4'
configValidationMode: error
build:
  esbuild:
    external:
      - 'prisma'
      - '@prisma/client'
provider:
  name: aws
  region: us-west-1
  environment:
    SERVERLESS_STAGE: ${sls:stage}
  deploymentMethod: direct
  vpc: ${file(../../serverless.common.yml):vpc}
  runtime: nodejs20.x
  architecture: arm64
  versionFunctions: false
  iam:
    role:
      managedPolicies:
        - {omitted by me}
functions:
  testNico:
    handler: src/engagement/nico.nicoHandler
    timeout: 3
    maximumRetryAttempts: 0
    memorySize: 1024
    events:
      - httpApi:
          method: 'GET'
          path: '/slack/testNico'
  testNicoTWO:
    handler: src/appsize/nicoTwo.nicoHandler
    timeout: 3
    maximumRetryAttempts: 0
    memorySize: 1024
    events:
      - httpApi:
          method: 'GET'
          path: '/slack/testNicoTwo'
```

**Comment by NicoHinderling** [comment]
[(I also cross posted to prisma's relevant issue thread for max viz)](https://github.com/prisma/prisma/discussions/20257)

**Comment by NicoHinderling** [comment]
I wanted to share a bit more testing I just did (just using npm/node/single workspace). I'm going to omit the `provider` key from the YAML, but here's my YAML with the following dependencies:
```
    "serverless": "^3.38.0",
    "serverless-esbuild": "1.52.1"
```

YAML:
```
service: internalSlackbot

projectDir: ../../

frameworkVersion: '3'
configValidationMode: error

plugins:
  - serverless-esbuild
package:
  patterns:
    - 'node_modules/.prisma/client/schema.prisma'
    - 'node_modules/.prisma/client/libquery_engine-*'

functions:
  testNico:
    handler: src/engagement/nico.nicoHandler
    timeout: 3
    maximumRetryAttempts: 0
    memorySize: 1024
    events:
      - httpApi:
          method: 'GET'
          path: '/slack/testNico'
```

This worked great! It deployed the following:
<img width="943" alt="image" src="https://github.com/serverless/serverless/assets/9902528/fd535ffb-cfc1-42ef-afed-2bbc5affa73c">

-----
Now I upgrade serverless to `^4.0.24` and remove the `serverless-esbuild` dependency entirely. All I change in the YAML is removing 

```
plugins:
  - serverless-esbuild
```
and setting `frameworkVersion` to 4. The following is generated:
<img width="941" alt="image" src="https://github.com/serverless/serverless/assets/9902528/0f693137-7258-44c7-9314-22619ec4b493">

I'm guessing we'd want this to be consistent / hints to me it's an issue with the serverless4 changes rather than the `serverless-esbuild` plugin 🤔🤔🤔🤔

**Comment by NicoHinderling** [comment]
> @NicoHinderling Thanks for the reporting, it definitely is an issue in our implementation. It is not handling packaging config correctly. I'll work on a solution to this and have a new version out soon.

🥳 huge, thank you @Mmarzex for the fast response! Will be happy to verify the fix

**Comment by austencollins** [comment]
@NicoHinderling We've tried to address this in: https://github.com/serverless/serverless/releases/tag/v4.0.33

**Comment by Mmarzex** [comment]
@NicoHinderling We just published a release that ensures files from your `package.patterns` config is included in your archive, if you could go ahead and run ` serverless update` and try it again and let us know.

On your second point related to packager options, we did not implement that. That is a functionality only in serverless-esbuild plugin, if you need this functionality could you expand on why and the usecase? We were trying to keep additional configuration in our esbuild implementation to a minimum.

**Comment by NicoHinderling** [comment]
@Mmarzex The patterns do seem to be working now! It does seem like a good fix that was added :D 

That being said, I'm still having the issue where my `.prisma` directory seems to not be discoverable (?) or more simply just copied in by esbuild. 

After further testing, this is 100% related to pnpm because it now works with both `serverless3` and `serverless4` as long as I use `npm`. If I switch to `pnpm`, I start getting this issue, regardless of using `serverless3` or `serverless4`.

In case others see this, I was able to make it begin working by basically breaking the native pnpm symlink behavior and adding the following flags to my root level `.npmrc` file:
```
node-linker=hoisted
shared-workspace-lockfile=false
```

The problem though is that when I add these flags, my web package no longer works in the pnpm workspace on vercel deploys 😢  The issue that arises is being [tracked here](https://github.com/pnpm/pnpm/issues/6106)... the reason I share is that I do think there's one more workaround that could give me the cake and eat it too (not require those two flags):

> On your second point related to packager options, we did not implement that. That is a functionality only in serverless-esbuild plugin, if you need this functionality could you expand on why and the usecase? We were trying to keep additional configuration in our esbuild implementation to a minimum.

I totally hear you, despite being the voice who has already asked for a few to be added 😂 😂 😂. The reason a script could be very valuable is because then I could just either:
1. try generating the prisma client within the build directory context
2. (more likely) manually copy the `.prisma/client` directory into my serverless build

Is there a way to currently do what I'm thinking with #2? If not, what do you think? 🤔 I could see it being very useful
