### ISSUE TITLE
After deploying single function, serverless stops sending logs to axiom

### ISSUE THREAD

**Issue by mishabhi** [serverless/serverless#12885]
### Issue description

This is the issue described in https://github.com/serverless/serverless/issues/12875. Despite team saying its fixed, I cant get it working

**Comment by mishabhi** [comment]
@czubocha May I ask your help here? This has been bitching us a lot and the functions are getting difficult back to axiom.

**Comment by czubocha** [comment]
@mishabhi this has been fixed in [4.4.7](https://github.com/serverless/serverless/releases/tag/v4.4.7), could you please explain why you can't upgrade to 4.4.7? You [mentioned ](https://github.com/serverless/serverless/issues/12875#issuecomment-2430277307) issues with environment variables - could you provide more details?

**Comment by mishabhi** [comment]
The moment we upgrade to 4.4.7, it starts giving us below error

```
Error: Cannot resolve '${self:custom.ssm.dev.blah_blah}' variable at 'provider.environment.BLAH_BLHA'. No value is available for this variable, and no default value was provided. Please check your variable definitions or provide a default value.
    at _ResolverManager.resolve (file:///home/abhishek/.serverless/releases/4.4.7/package/dist/sf-core.js:693:56026)
    at async #handlePlaceholderNode (file:///home/abhishek/.serverless/releases/4.4.7/package/dist/sf-core.js:693:54456)
    at async file:///home/abhishek/.serverless/releases/4.4.7/package/dist/sf-core.js:693:52448
    at async processNodeAndHandleCompletion (file:///home/abhishek/.serverless/releases/4.4.7/package/dist/sf-core.js:693:43090)
```

**Comment by mishabhi** [comment]
To fix this if I change the framework version to 4.4.2, it works. But logs are still not getting back to axiom.

**Comment by czubocha** [comment]
Got it. Are you able to provide a simple example of `serverless.yml` config that's causing this error? From what I understand, you're using `self` resolver in the `provider.environment` block. How does your `custom` block look like?

**Comment by mishabhi** [comment]
I have kept framework version as 4.4.2 and serverless version in package.json as 4.4.7 to make it work. Do you think it will bring back axiom logs?

**Comment by mishabhi** [comment]
My severless file has two references. One for custom and the other for environment. I guess its failing when it tries to load environment one
In custom.yml we have values like below

```
scheduleProdOnly:
  offline: false
  dev: false
  test: false
  prod: true
```

And in environment.yml we have values like below

```
APPLICATION_NAME: backend-${self:provider.stage}
```

**Comment by czubocha** [comment]
> I have kept framework version as 4.4.2 and serverless version in package.json as 4.4.7 to make it work. Do you think it will bring back axiom logs?

No, you can only run one version of serverless at a time. If you need to use 4.4.2, you can re-integrate your service with Axiom by running a full deployment - first without Axiom observability and then with Axiom enabled.

> My severless file has two references.

It looks like your setup is similar to this:
```
provider:
  environment: ${file(environment.yml)}

custom: ${file(custom.yml)}
```
And in the `environment.yml` file, you're also referencing properties from `custom.yml` using the `self` resolver, like this:
```
APPLICATION_NAME: example-${self:custom.dev.blah}
```
Is that correct?

**Comment by mishabhi** [comment]
Yes correct.

**Comment by czubocha** [comment]
Hey @mishabhi 
I tried reproducing your issue with the following config:
```
# serverless.yml
service: my-service

custom: ${file(custom.yml)}

provider:
  name: aws
  environment: ${file(environment.yml)}

functions:
  hello:
    handler: handler.hello
    description: ${self:custom.dev.YYY}
```

```
# custom.yml
dev:
  YYY: YYYvalue
```

```
# environment.yml
ABC: ${self:custom.dev.YYY}
```

It resolved successfully to:
```
service: my-service
custom:
  dev:
    YYY: YYYvalue
provider:
  name: aws
  environment:
    ABC: YYYvalue
  stage: dev
  region: us-east-1
  versionFunctions: true
functions:
  hello:
    handler: handler.hello
    description: YYYvalue
    events: []
    name: my-service-dev-hello
```
when I ran `sls print`. However, we’re aware of similar reports in https://github.com/serverless/serverless/issues/12854 and are actively tracking it down. I’ll close this issue so we can focus on the details in the main thread. If you notice anything specific (e.g., in debug logs) that could help, please share it in the other issue to speed up our resolution.
