### ISSUE TITLE
Referencing variables from other file does not work

### ISSUE THREAD

**Issue by JakubMatejka** [serverless/serverless#2169]
# This is a Bug Report

## Description

When I read external file to some field in serverless.yml (let's say `custom`) and then reference it's variables using e.g. `${self:custom.S3_BUCKET_ICONS}` I get error `Trying to populate non string value into a string for variable ${self:custom.S3_BUCKET_ICONS}. Please make sure the value of the property is a string.` from Serverless cli. But reading the variable directly like `${file(./env.yml):S3_BUCKET_ICONS}` works without problem.

My simplified serverless.yml looks like:

```yml
---
custom: ${file(./env.yml)}

service: "${self:custom.SERVICE_NAME}"

provider:
  name: aws
  region: us-east-1
  runtime: nodejs4.3
  stage: dev
  iamRoleStatements:
      -
        Action:
          - "s3:*"
        Effect: Allow
        Resource:
          - "arn:aws:s3:::${self:custom.S3_BUCKET_ICONS}/*"
      -
        Action:
          - "ses:SendEmail"
        Effect: Allow
        Resource:
          - "*"
      -
        Action:
          - "cognito-identity:*"
          - "cognito-idp:*"
        Effect: Allow
        Resource:
          - "${file(./env.yml):COGNITO_POOL_ARN}"

functions:
  default:
    handler: handler.handler
```

and the env.yml looks like:

```yml
SERVICE_NAME: jakub-test
COGNITO_POOL_ARN: ...
S3_BUCKET_ICONS: dev-portal-icons
```

## Additional Data

* ***Serverless Framework Version you're using***: 1.0.0 rc1
* ***Operating System***: macOS 10.12
* ***Stack Trace***:
* ***Provider Error messages***:

**Comment by andymac4182** [comment]
I have confirmed this was a bug in `rc1` and it is fixed in master already. 

If you want to use the version from master you can run `npm install https://github.com/serverless/serverless -g` ? This will install the latest version from `master` branch.

**Comment by flomotlik** [comment]
Thanks for reviewing @andymac4182 , Closing.

**Comment by gozup** [comment]
Hi @andymac4182 @flomotlik ,
I've installed the master package, but the bug is still here for me.

```
npm list serverless -g
/usr/local/lib
└── serverless@1.0.0-rc.2  (git+https://github.com/serverless/serverless.git#e099533491a98ca945b2e44cf615d86ebbb831bd)
```

Still have the issue:
```
     Trying to populate non string value into a string for
     variable ${self:custom.environment}. Please make sure
     the value of the property is a string.
```

The files are:
```yaml
[...]
provider:
  custom: ${file(./_sls_ENV/env.yml)}
  stage: ${self:custom.environment}
[...]
```

And env.yml is
```yaml
environment: 'development'
```

Am I doing something wrong, or the bug still here?

Thank you

**Comment by andymac4182** [comment]
That is because you are referencing that file at `${self:provider.custom.environment}`

**Comment by gozup** [comment]
Thank you @andymac4182 
Crystal clear ! What a dumb I am...

**Comment by polvoazul** [comment]
I think that self should reference the actual file, it is not very intuitive that way.

**Comment by polvoazul** [comment]
Also, anyone know how to merge files?

**Comment by Dev-Dipesh** [comment]
## ⚠️ Please open the issue

The error is still there in the new version.

This doesn't work.

```yml
environment: ${file(./config/env.yml)}
```

**Throws error:**

```qml
Cannot** create property 'PRISMA_ENDPOINT' on string '${file(./config/env.yml)}'
```

This works:

```yml
environment:
    - "${file(./config/env.yml):PRISMA_ENDPOINT}"
    - "${file(./config/env.yml):PRISMA_SECRET}"
    - "${file(./config/env.yml):APP_SECRET}"
```

### Additional Info

**My `env.yml` file**

```yml
PRISMA_ENDPOINT: ${env:PRISMA_ENDPOINT}
PRISMA_SECRET: ${env:PRISMA_SECRET}
APP_SECRET: ${env:APP_SECRET}
```

**Serverless in `package.json`**

```json
"serverless": "^1.51.0",
"serverless-dotenv-plugin": "^2.1.1",
"serverless-offline": "^5.10.1",
"serverless-prune-plugin": "^1.4.1",
"serverless-webpack": "^5.3.1",
```
