### ISSUE TITLE
Question: angular $http.post to API Gateway getting 403

### ISSUE THREAD

**Issue by jodagm** [serverless/serverless#222]
Hi,

I am able to call API GW successfully from postman, however calling it from angular $http.post leads to error 403.

It might be related to CORS.
based on #133 I setup the endpoint as follows:

```
"apiGateway": {
    "deploy": false,
    "cloudFormation": {
      "Type": "AWS",
      "Path": "login",
      "Method": "POST",
      "AuthorizationType": "none",
      "ApiKeyRequired": false,
      "RequestTemplates": {},
      "RequestParameters": {},
      "Responses": {
        "400": {
          "statusCode": "400"
        },
        "default": {
          "statusCode": "200",
          "responseParameters": {
            "method.response.header.Access-Control-Allow-Origin": "'*'"
          },
          "responseTemplates": {
            "application/json": ""
          }
        }
      }
    }
  }
```

Any help is greatly appreciated
Jonathan

**Comment by ac360** [comment]
@jodagm Could it be that Angular does a pre-flight OPTIONS request and you don't have an OPTIONS method on your API Gateway resource?

Also, [perhaps this is the problem as well](http://stackoverflow.com/questions/31376281/angular-resource-post-request-query-params-not-detected-by-aws-api-gateway/31376675#31376675)

**Comment by DanDiac** [comment]
@jodagm Can you check if there are any differences on the URL that the angular uses? 
You can try to add these two: 'Access-Control-Allow-Methods' and 'Access-Control-Allow-Headers'
http://docs.aws.amazon.com/apigateway/latest/developerguide/how-to-cors.html

@ac360 The problem from that link is about mapping parameters.

**Comment by Ninir** [comment]
@ac360 Indeed, AngularJS does a pre-flight OPTIONS request. As @DanDiac said, the `'Access-Control-Allow-Methods' and 'Access-Control-Allow-Headers'` should be added. 

However, an OPTIONS method should be created with the 3 (Origin, Headers and Methods), and the POST method should only have the Origin header.

Is there a way to add the OPTIONS method too?

**Comment by OneMuppet** [comment]
Hi, 
I had the same problem and you all helped me in the right direction. I'm also using angularjs and $http for ajax requests. You will have to add "method.response.header.Access-Control-Allow-Methods": "'GET, OPTIONS'", in the cloudformation setup.  This is my setup that works:
{
  "lambda": {
    "envVars": [],
    "deploy": true,
    "package": {
      "optimize": {
        "builder": "browserify",
        "minify": true,
        "ignore": [],
        "exclude": [
          "aws-sdk"
        ],
        "includePaths": []
      },
      "excludePatterns": []
    },
    "cloudFormation": {
      "Description": "",
      "Handler": "aws_modules/greetings/hello/handler.handler",
      "MemorySize": 1024,
      "Runtime": "nodejs",
      "Timeout": 6
    }
  },
  "apiGateway": {
    "deploy": false,
    "cloudFormation": {
      "Type": "AWS",
      "Path": "greetings/hello",
      "Method": "GET",
      "AuthorizationType": "none",
      "ApiKeyRequired": false,
      "RequestTemplates": {},
      "RequestParameters": {},
      "Responses": {
        "400": {
          "statusCode": "400"
        },
        "default": {
          "statusCode": "200",
          "responseParameters": {
            "method.response.header.Access-Control-Allow-Headers": "'Content-Type,X-Amz-Date,Authorization'",
            "method.response.header.Access-Control-Allow-Methods": "'GET, OPTIONS'",
            "method.response.header.Access-Control-Allow-Origin": "'*'"
          },
          "responseModels": {},
          "responseTemplates": {
            "application/json": ""
          }
        }
      }
    }
  }
}

**Comment by Ninir** [comment]
@OneMuppet Nice to hear!
However, something is bothering me: as allowed methods (with the `Access-Control-Allow-Methods`) are set on the CloudFormation `"Method": "GET",`, we're simply telling that GET and OPTIONS requests can call this endpoint when using the pre-flight request (so using OPTIONS), as in:

1. A user starts a request GET request against the endpoint
2. As CORS states, a pre-flight request (OPTIONS) is made
3. Server answers with `Access-Control-Allow-Headers:Content-Type,X-Amz-Date,Authorization`, `Access-Control-Allow-Methods:GET,POST`, `Access-Control-Allow-Origin:*`
4. The initial request is then made (a POST would be failing)

However, how do you tell API Gateway that you pre-flight request can be called using CORS without specifying those headers on it?

I mean, in your case, the logic would be that IF a pre-flight request is made, it is coming back from the server with a 403... I'm probably missing something here! :smile:

**Comment by OneMuppet** [comment]
@Ninir Those headers aren't needed, not for the call to this lambda since it doesn't have any authorization requirements on it. I just added that because the official guide from AWS on how to add CORS has it: http://docs.aws.amazon.com/apigateway/latest/developerguide/how-to-cors.html#how-to-cors-console 
I'm guessing that the javascript-sdk that you can generate from API Gateway may be using those headers, but I haven't checked. :)

the 403 is simply because the pre-flight OPTIONS method wasn't allowed before. You don't need a actual handler responding to the OPTIONS call, this will be handled by the API Gateway, as far as I can tell. 

I'm not sure if that sheds any more light on the matter? :smile:

**Comment by jodagm** [comment]
Thanks all, I am still trying to make this work.

@OneMuppet did you get this to work for POST as well? I do get this working for GET requests but not for POST.

this is the config:

```
{
  "lambda": {
    "envVars": [],
    "deploy": true,
    "package": {
      "optimize": {
        "builder": "browserify",
        "minify": true,
        "ignore": [],
        "exclude": [
          "aws-sdk"
        ],
        "includePaths": [
          "node_modules"
        ]
      },
      "excludePatterns": []
    },
    "cloudFormation": {
      "Description": "user login",
      "Handler": "aws_modules/users/login/handleApiCall/handler.handler",
      "MemorySize": 1024,
      "Runtime": "nodejs",
      "Timeout": 6
    }
  },
  "apiGateway": {
    "deploy": false,
    "cloudFormation": {
      "Type": "AWS",
      "Path": "login",
      "Method": "POST",
      "AuthorizationType": "none",
      "ApiKeyRequired": false,
      "RequestTemplates": {},
      "RequestParameters": {},
      "Responses": {
        "400": {
          "statusCode": "400"
        },
        "default": {
          "statusCode": "200",
          "responseParameters": {
            "method.response.header.Access-Control-Allow-Headers": "'Content-Type,X-Amz-Date,Authorization'",
            "method.response.header.Access-Control-Allow-Methods": "'GET,POST,OPTIONS'",
            "method.response.header.Access-Control-Allow-Origin": "'*'"
          },
          "responseModels": {},
          "responseTemplates": {
            "application/json": ""
          }
        }
      }
    }
  }
}
```

@Ninir @ac360 OPTIONS should be manually created using the APIG console? any other manual setup that is not covered by the above config?

thanks for your help

**Comment by OneMuppet** [comment]
@jodagm you are right, I get the same error on when using POST. What I did as a "workaround" for now was to, deploy my Lambda and API Gateway endpoint. Then I opened the awsm.json and changed the method from POST to OPTIONS:
´´´javascript
"apiGateway": {
    "deploy": false,
    "cloudFormation": {
      "Type": "AWS",
      "Path": "greetings/hellopost",
      "Method": "OPTIONS",
      "AuthorizationType": "none",
      "ApiKeyRequired": false,
      "RequestTemplates": {},
      "RequestParameters": {},
      "Responses": {
        "400": {
          "statusCode": "400"
        },
        "default": {
          "statusCode": "200",
          "responseParameters": {
            "method.response.header.Access-Control-Allow-Headers": "'Content-Type,X-Amz-Date,Authorization'",
            "method.response.header.Access-Control-Allow-Methods": "'POST, OPTIONS'",
            "method.response.header.Access-Control-Allow-Origin": "'*'"
          },
          "responseModels": {},
          "responseTemplates": {
            "application/json": ""
          }
        }
      }
    }
  }
´´´
and deployed the API Gateway Endpoint again, that way I get both methods with the same setup:
![image](https://cloud.githubusercontent.com/assets/4235764/10456199/47a266f0-71c0-11e5-818e-fa7123ab380c.png)

This will require you to remember to deploy a OPTIONS endpoint as well as a "normal" endpoint each time you add a new method or what to change something in how your endpoint works. We all know that everything that we have to remember, we are sure to forget so this is not a long term solution but more of an input to the discussion. 

@ac360 Is it possible to deploy multiple methods for one API Gateway endpoint?

**Comment by jodagm** [comment]
problem solved with the manual process of adding the OPTIONS method on the resource.

I am just not used to deploying using the console... got used to the easy process provided by JAWS :-)

hopefully, deploying OPTIONS will be supported in the future

**Comment by Ninir** [comment]
Yes, going through the AWS console seems the better approach here... having an array of methods would be awesome :D

**Comment by malkomalko** [comment]
I'm still having this problem after following all the steps, but interestingly only for DELETE.  Is anybody still running into this?
