### ISSUE TITLE
Unable to deploy using 1.0.2

### ISSUE THREAD

**Issue by ziaukhan** [serverless/serverless#2370]
I am unable to deploy even a simple hello world using version 1.0.2 on OS X El Capitan 10.11.5. I have tried it with 1.0.0 with the same results. It simply hangs.

<img width="1440" alt="screenshot 2016-10-14 10 21 16" src="https://cloud.githubusercontent.com/assets/545458/19376593/66cefe68-91f8-11e6-9cdb-4847c51df777.png">

**Comment by faizhasim** [comment]
Attempted to upgrade from 1.0.0-rc2 to 1.0.2, I can't deploy as well. I tried to call via API Gateway console and I saw this in the log:

```
Fri Oct 14 08:43:01 UTC 2016 : Execution failed due to configuration error: Malformed Lambda proxy response
```

**Comment by flomotlik** [comment]
@ziaukhan do you have all the rights necessary to deploy this?

**Comment by flomotlik** [comment]
@faizhasim this is a problem with a breaking change we released. Check out the APIG docs and the proxy config there: https://serverless.com/framework/docs/providers/aws/

**Comment by ziaukhan** [comment]
@flomotlik I have the aws rights, the file is uploading but not working

**Comment by ziaukhan** [comment]
@flomotlik I have even node.js and reinstalled everything, but the issue persists

**Comment by ziaukhan** [comment]
As you can see below it is uploading but the lambda function is not working, and the cli is stuck at Serverless: Checking Stack update progress...

<img width="1440" alt="screenshot 2016-10-14 16 57 49" src="https://cloud.githubusercontent.com/assets/545458/19386779/9c06c322-922f-11e6-9767-9fea358a0820.png">

**Comment by ac360** [comment]
@ziaukhan This might have to do with CloudFunction having problems with creating IAM roles lately.  The IAM roles get stuck in a "creating" stage for hours.  Not much we can do about this one :(

**Comment by mthenw** [comment]
@ziaukhan is it still and issue for you?

**Comment by ziaukhan** [comment]
@mthenw I have updated to 1.0.3 and it solved the problem for me on Mac. Thanks.

**Comment by WendySanarwanto** [comment]
Hello all, 

I still got this problem , only happened in my macbook. It did not happen in my Linux desktop. 

![image](https://cloud.githubusercontent.com/assets/18456618/21477754/d0eaf2aa-cb7f-11e6-9a31-6d941d47f0e5.png)

Does any mac users with macSierra OS got this problem as well ? 

Environments:
- Macbook , running Mac OS X macSierra 10.12
- NodeJS runtime 4.3.2 & 6.9.1
- Serverless version 1.3 & 1.4

**Comment by Fosol** [comment]
I have this same issue with Windows 10.
NodeJs 7.4.0
Serverless 1.5

**Comment by Fosol** [comment]
I downgraded to NodeJs 6.9.1 and I was able to get past the bug.  Now I'm onto the next issue where the stag isn't found...

**Comment by pmuens** [comment]
Interesting @Fosol thanks for mentioning that!

I'm running Node.js version `v7.2.0` w/o issues...

**Comment by pmuens** [comment]
Hmm. That's pretty odd.

@RastoStric do you have the possibility to test it on Node v7.2.0 since I've tested it with this version and it works...

**Comment by RastoStric** [comment]
@pmuens Thank you for your reply. I have just tried Node 7.2.0 with Serverless 1.6.0 and still hangs on "Checking Stack create progress...". 
This is no good, I think I will give up Serverless. It am sorry because you have done such a great job and it looks so promising, but I need something that would not stop me before I even started.
I wish you good luck.

**Comment by jludwi2** [comment]
Rasto,

Mine also hung the first time, and then on retrying worked like a 
charm.  I assume it's a problem with AWS, but I'm not sure.  I turned on 
debug, but it didn't show much more than "Checking Stack create 
progress".  When I checked in AWS, the stack was created but no ZIP file 
was loaded to S3.  Maybe Serverless is somehow missing the fact that the 
Stack is created sometimes?  I'm not sure.

     Jerry Ludwig, just learning about serverless now.

**Comment by pmuens** [comment]
@RastoStric that's really sad to hear 😞 . Sorry for the inconveniences...
We're currently seeing this error popping up more often. Unfortunately it's hard to resolve since it's hard to reproduce.

We try to get a fix out for this as soon as possible. In the meantime I could suggest to try out the Docker container to play around with Serverless in isolation.

It's as simple as `docker-compose run serverless-node bash` and then you can run Serverless like this `./bin/serverless info`.
