### ISSUE TITLE
updating from v1rc2 to v1.2 creates troubles with deployment

### ISSUE THREAD

**Issue by riccardo-89** [serverless/serverless#2777]
# Bug Report

## Description

For bug reports:
* What went wrong?
I have updated from v1 rc2 to v1.2 and tried to re-deploy to check if everything was working fine
* What did you expect should have happened?
Deployment going smooth

* What stacktrace or error message from your provider did you see?

Serverless Error ---------------------------------------

     An error occurred while provisioning your stack: ApiGatewayMethodApiAuthenticationNewpasswordchallengePost
     - Property HttpMethod cannot be empty..

  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues

  Your Environment Information -----------------------------
     OS:                 darwin
     Node Version:       6.2.0
     Serverless Version: 1.2.0

## Additional Data

* ***Serverless Framework Version you're using***:  1.2
* ***Operating System***: MacOS
* ***Stack Trace***: 

A bunch of these messages before Uploading CloudFormation file to S3... and Updating Stack...
Serverless: Error: could not find CloudFormation object for authenticate:api/authentication/newPasswordChallenge
Serverless: Error: could not find CloudFormation object for authenticate:api/authentication/resendPasswordChallenge
Serverless: Error: could not find CloudFormation object for signup:api/authentication/captchaSignup

Has something been changed in the cloud formation logical ids? 

thanks

**Comment by pmuens** [comment]
@riccardo-89 thanks for reporting. 👍 

Could you share your `serverless.yml` config file so that we can see how your service looks like?

**Comment by Squareomatic** [comment]
Hi @pmuens thanks for the quick response, I really think it is something related to logical id that may have changed among versions? thanks

**this is my serverless.yml**

`
service: api-auth

plugins:
  - serverless-scriptable-plugin
  - serverless-plugin-write-env-vars
  - serverless-inputs-plugin
  - serverless-webpack
  - serverless-plugin-multiple-responses
  - serverless-apicache-plugin
  - serverless-users-plugin



# PROVIDER
provider:
  name: aws
  runtime: nodejs4.3
  stage:  ${opt:stage, ${self:custom.stage}}
  region: ${opt:region, ${self:custom.region}}
  profile: ${self:custom.profiles.${self:provider.stage}}



# CUSTOM
custom:
  infrastructure: ${file(./infrastructure-${self:provider.stage}.yml)}
  stage: dev
  region: eu-west-1
  profiles:
	dev:  default
	uat:  default
	prod: default
  writeEnvVars: ${file(./variables/env.yml):EnvVars}
  writeEventVars: ${file(./variables/event-vars.yml):EventVars}
  identityPoolId: ${self:custom.infrastructure.identityPoolIdIdentityPoolMain, ""}
  webpackIncludeModules: true
  scriptHooks:
	 before:deploy:setupProviderConfiguration: scripts/discover.js
	 before:deploy:cleanup: scripts/install.js
	 before:deploy:initialize: scripts/clear.js




# RESOURCES AND OUTPUTS
resources:
   Resources: ${file(./variables/resources.yml):Resources}
   Outputs: ${file(./variables/outputs.yml):Outputs}



# FUNCTIONS
functions:

  authorizerJWT:
	timeout: 6
	memorySize: 1536
	handler: authorizers/jwt/handler.authorizer


  eventPostLogin:
	timeout: 6
	memorySize: 1536
	handler: events/post-login/handler.postLogin

  eventPostSignup:
	timeout: 6
	memorySize: 1536
	handler: events/post-signup/handler.postSignup


  authenticate:
	timeout: 6
	memorySize: 1536
	handler: authentication/authenticate/handler.authenticate
	events:
	  - http:
		  path: api/authentication/warmup
		  method: POST
		  cors: ${file(./variables/cors.yml):CORS}
	  - http:
		  path: api/authentication/login
		  method: POST
		  cors: ${file(./variables/cors.yml):CORS}
	  - http:
		  path: api/authentication/refresh
		  method: POST
		  cors: ${file(./variables/cors.yml):CORS}
	  - http:
		  path: api/authentication/enhanced
		  method: POST
		  cors: ${file(./variables/cors.yml):CORS}
	  - http:
		  path: api/authentication/newPasswordChallenge
		  method: POST
		  cors: ${file(./variables/cors.yml):CORS}
	  - http:
		  path: api/authentication/resendPasswordChallenge
		  method: POST
		  cors: ${file(./variables/cors.yml):CORS}


  signup:
	timeout: 20
	memorySize: 1536
	handler: authentication/signup/handler.signup
	events:
	  - http:
		  path: api/authentication/signup
		  method: POST
		  cors: ${file(./variables/cors.yml):CORS}
	  - http:
		  path: api/authentication/captchaSignup
		  method: POST
		  cors: ${file(./variables/cors.yml):CORS}
	  - http:
		  path: api/authentication/mobileSignup
		  method: POST
		  cors: ${file(./variables/cors.yml):CORS}


  verification:
	timeout: 6
	memorySize: 1536
	handler: authentication/verification/handler.verification
	events:
	  - http:
		  path: api/authentication/verification
		  method: POST
		  cors: ${file(./variables/cors.yml):CORS}


  forgotPassword:
	timeout: 6
	memorySize: 1536
	handler: authentication/forgot-password/handler.forgotPassword
	events:
	  - http:
		  path: api/authentication/forgotPassword
		  method: POST
		  cors: ${file(./variables/cors.yml):CORS}
	  - http:
		  path: api/authentication/captchaForgotPassword
		  method: POST
		  cors: ${file(./variables/cors.yml):CORS}


  resendVerification:
	timeout: 6
	memorySize: 1536
	handler: authentication/resend-verification/handler.resendVerification
	events:
	  - http:
		  path: api/authentication/resendVerification
		  method: POST
		  cors: ${file(./variables/cors.yml):CORS}


  resetPassword:
	timeout: 6
	memorySize: 1536
	handler: authentication/reset-password/handler.resetPassword
	events:
	  - http:
		  path: api/authentication/resetPassword
		  method: POST
		  cors: ${file(./variables/cors.yml):CORS}


  logsList:
	timeout: 6
	memorySize: 1536
	handler: logs/logs-list/handler.logsList
	events:
	  - http:
		  path: api/logs/list
		  method: POST
		  cors: ${file(./variables/cors.yml):CORS}


  devices:
	timeout: 6
	memorySize: 1536
	handler: devices/devices-graphql/handler.graphql
	events:
	  - http:
		  path: api/devices/{action}
		  method: POST
		  cors: ${file(./variables/cors.yml):CORS}


  usersMe:
	timeout: 6
	memorySize: 1536
	handler: users/me/handler.usersMe
	events:
	  - http:
		  path: api/users/me
		  method: POST
		  cors: ${file(./variables/cors.yml):CORS}


  usersMutation:
	timeout: 6
	memorySize: 1536
	handler: users/mutation/handler.usersMutation
	events:
	  - http:
		  path: api/users/me/{mutation}
		  method: POST
		  cors: ${file(./variables/cors.yml):CORS}


  usersMfa:
	timeout: 6
	memorySize: 1536
	handler: users/mfa/handler.mfaOptions
	events:
	  - http:
		  path: api/users/me/mfa/{action}
		  method: POST
		  cors: ${file(./variables/cors.yml):CORS}


  usersUpdatePassword:
	timeout: 6
	memorySize: 1536
	handler: users/update-password/handler.updatePassword
	events:
	  - http:
		  path: api/users/me/updatePassword
		  method: POST
		  cors: ${file(./variables/cors.yml):CORS}



  usersCreate:
	timeout: 12
	memorySize: 1536
	handler: users/create/handler.usersCreate



  triggerCustomMessage:
	timeout: 6
	memorySize: 1536
	handler: triggers/custom-message/handler.customMessage
  triggerPreSignup:
	timeout: 6
	memorySize: 1536
	handler: triggers/pre-signup/handler.preSignup
  triggerPostAuthentication:
	timeout: 6
	memorySize: 1536
	handler: triggers/post-authentication/handler.postAuthentication`

**Comment by pmuens** [comment]
Thank you for the kind words @riccardo-89! Really appreciate it!

Furthermore thank you for providing the `serverless.yml` file! We'll look into it.

/ccing @eahefnawy here as well!

**Comment by dougmoscrop** [comment]
This looks like the bug that was fixed here: https://github.com/serverless/serverless/pull/2774

@riccardo-89 can you try 1.2.1?

**Comment by Squareomatic** [comment]
@dougmoscrop Hi! thanks for the help, unfortunately updating to version 1.2.1 did not solve.

Which priority do you give to the custom CF that is passed from resources? because I think custom CF must have always higher priority on the one declared by serverless to avoid to restrict use cases. 

For instance in this case I reference a lambda created in another service (to share the custom authorizer lambda among services) that I did not create from serverless, so I cannot use your pattern.

It seams that by directly setting the Method resource, something is overwritten badly in CF.

Error from serverless
```
An error occurred while provisioning your stack: ApiGatewayMethodApicoreAuthenticationResendverificationPost
     - Property HttpMethod cannot be empty..
```

Reference the method resource to change few props
```
ApiGatewayMethodApicoreAuthenticationResendverificationPost: ${file(./variables/authorizations.yml):AWS_IAM_AND_API_KEY}
```

Create a custom authorizer using the current api gateway and a lambda created somewhere else
```
CustomAuthorizerJWT:
    Type: "AWS::ApiGateway::Authorizer"
    Properties:
      AuthorizerCredentials: ${self:custom.infrastructure.iamRoleArnApiGatewayInvocationAuthorizerJWT}
      AuthorizerResultTtlInSeconds: 300
      AuthorizerUri:
        Fn::Join:
          - ""
          -
            - "arn:aws:apigateway:"
            - Ref: "AWS::Region"
            - ":lambda:path/2015-03-31/functions/"
            - Fn::GetAtt:
                - "AuthorizerJWTLambdaFunction"
                - "Arn"
            - "/invocations"
      IdentitySource: "method.request.header.Authorization"
      Name: JWT
      RestApiId: { "Ref" : "ApiGatewayRestApi" }
      Type: TOKEN
```

Common way on how I do setup method resources in my api
```
JWT_AUTHORIZER_AND_API_KEY:
  Type: 'AWS::ApiGateway::Method'
  Properties:
    AuthorizationType: CUSTOM
    AuthorizerId: { "Ref" : "CustomAuthorizerJWT" }
    ApiKeyRequired: true
    Integration:
      Type: AWS_PROXY
```

Please let me know! thanks

R

**Comment by pmuens** [comment]
Hey @Squareomatic the resources you define in the `resources` section of your `serverless.yml` file will be merged on top of the CloudFormation template / resources created by Serverless.

Can you remove the whole stack and re-deploy everything with the latest Serverless release?

We've improved the logical id system a lot since `v1 rc2`.

**Comment by pmuens** [comment]
Closing this one for now since there were some breaking changes from `v1 rc2` to `v1`.

We've committed to follow semver and won't introduce any breaking changes in v1.

**Comment by riccardo-89** [comment]
@pmuens thanks a lot, yes the re-deploy has solved the issue, I noticed you now use Dash for - and put Var when in the endpoint path there is something variables {}, thanks a lot for the help!

**Comment by pmuens** [comment]
@riccardo-89 glad to hear that it helped! Yes, we've updated the resource logical ids quite a bit. 👍
