### ISSUE TITLE
Custom Authorizer Breaks Deploy - Cannot read property 'forEach' of undefined

### ISSUE THREAD

**Issue by securityvoid** [serverless/serverless#3005]
# This is a (Bug Report)

## Description
Attempting to deploy a custom authorizer blows up on deploy. This appears to be because a custom authorizer does not have an "event" attribute which breaks the forEach.

```
Serverless: Packaging service...
Serverless: Uploading CloudFormation file to S3...
Serverless: Uploading service .zip file to S3 (8.57 MB)...
Serverless: Updating Stack...
Serverless: Checking Stack update progress...
..................................................
Serverless: Stack update finished...
Serverless: Removing old service versions...

  Type Error ---------------------------------------------

     Cannot read property 'forEach' of undefined

     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.

  Stack Trace --------------------------------------------

TypeError: Cannot read property 'forEach' of undefined
    at _.forEach (C:\Users\Bob\AppData\Roaming\npm\node_modules\serverless\lib\plugins\aws\info\display.js:35:30)
    at C:\Users\Bob\AppData\Roaming\npm\node_modules\serverless\node_modules\lodash\lodash.js:4970:15
    at baseForOwn (C:\Users\Bob\AppData\Roaming\npm\node_modules\serverless\node_modules\lodash\lodash.js:3020:24)
    at C:\Users\Bob\AppData\Roaming\npm\node_modules\serverless\node_modules\lodash\lodash.js:4939:18
    at Function.forEach (C:\Users\Bob\AppData\Roaming\npm\node_modules\serverless\node_modules\lodash\lodash.js:9344:14)
    at AwsInfo.display (C:\Users\Bob\AppData\Roaming\npm\node_modules\serverless\lib\plugins\aws\info\display.js:34:9)
    at AwsInfo.tryCatcher (C:\Users\Bob\AppData\Roaming\npm\node_modules\serverless\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\Users\Bob\AppData\Roaming\npm\node_modules\serverless\node_modules\bluebird\js\release\promise.js:510:31)
    at Promise._settlePromise (C:\Users\Bob\AppData\Roaming\npm\node_modules\serverless\node_modules\bluebird\js\release\promise.js:567:18)
    at Promise._settlePromise0 (C:\Users\Bob\AppData\Roaming\npm\node_modules\serverless\node_modules\bluebird\js\release\promise.js:612:10)
    at Promise._settlePromises (C:\Users\Bob\AppData\Roaming\npm\node_modules\serverless\node_modules\bluebird\js\release\promise.js:691:18)
    at Async._drainQueue (C:\Users\Bob\AppData\Roaming\npm\node_modules\serverless\node_modules\bluebird\js\release\async.js:138:16)
    at Async._drainQueues (C:\Users\Bob\AppData\Roaming\npm\node_modules\serverless\node_modules\bluebird\js\release\async.js:148:10)
    at Immediate.Async.drainQueues (C:\Users\Bob\AppData\Roaming\npm\node_modules\serverless\node_modules\bluebird\js\release\async.js:17:14)
    at runCallback (timers.js:637:20)
    at tryOnImmediate (timers.js:610:5)
    at processImmediate [as _immediateCallback] (timers.js:582:5)

  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues

     Please report this error. We think it might be a bug.

  Your Environment Information -----------------------------
     OS:                 win32
     Node Version:       6.9.2
     Serverless Version: 1.4.0
```

Relevant Portions of Serverless YML:
```
functions:
  poller:
    name: poller
    handler: reporting.poller
    memorySize: 128
    timeout: 2
    events:
      - http:
          path: /poll
          method: get
          authorizer:
            name: validateToken
            resultTtlInSeconds: 0
            identitySource: method.request.header.Cookie
          integration: lambda-proxy
validateToken:
    name: validateToken
    handler: node_modules/cn-lambda-auth/lib/index.validateToken

```

## Additional Data

* ***Serverless Framework Version you're using***: 1.4.0
* ***Operating System***: win32
* ***Stack Trace***: (See above)
* ***Provider Error messages***: Cannot read property 'forEach' of undefined

**Comment by pmuens** [comment]
Thjs should've been fixed in the meantime. Feel free to re-open if this is still a bug.

**Comment by jeffthefate** [comment]
I'm still seeing this issue, but it is not breaking deploy. It appears when the `aws:info:displayEndpoints` hook is executed after the deploy:

```
  Type Error ---------------------------------------------
 
  Cannot read property 'forEach' of undefined
 
     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.
 
  Stack Trace --------------------------------------------
 
TypeError: Cannot read property 'forEach' of undefined
    at _.forEach (/Users/jfate/.nvm/versions/node/v6.10.3/lib/node_modules/serverless/lib/plugins/aws/info/display.js:48:30)
    at /Users/jfate/.nvm/versions/node/v6.10.3/lib/node_modules/serverless/node_modules/lodash/lodash.js:4917:15
    at baseForOwn (/Users/jfate/.nvm/versions/node/v6.10.3/lib/node_modules/serverless/node_modules/lodash/lodash.js:3002:24)
    at /Users/jfate/.nvm/versions/node/v6.10.3/lib/node_modules/serverless/node_modules/lodash/lodash.js:4886:18
    at Function.forEach (/Users/jfate/.nvm/versions/node/v6.10.3/lib/node_modules/serverless/node_modules/lodash/lodash.js:9334:14)
    at AwsInfo.displayEndpoints (/Users/jfate/.nvm/versions/node/v6.10.3/lib/node_modules/serverless/lib/plugins/aws/info/display.js:47:9)
From previous event:
    at Object.aws:info:displayEndpoints [as hook] (/Users/jfate/.nvm/versions/node/v6.10.3/lib/node_modules/serverless/lib/plugins/aws/info/index.js:66:10)
    at BbPromise.reduce (/Users/jfate/.nvm/versions/node/v6.10.3/lib/node_modules/serverless/lib/classes/PluginManager.js:372:55)
From previous event:
    at PluginManager.invoke (/Users/jfate/.nvm/versions/node/v6.10.3/lib/node_modules/serverless/lib/classes/PluginManager.js:372:22)
    at PluginManager.spawn (/Users/jfate/.nvm/versions/node/v6.10.3/lib/node_modules/serverless/lib/classes/PluginManager.js:390:17)
    at AwsInfo.BbPromise.bind.then (/Users/jfate/.nvm/versions/node/v6.10.3/lib/node_modules/serverless/lib/plugins/aws/info/index.js:49:48)
From previous event:
    at Object.deploy:deploy [as hook] (/Users/jfate/.nvm/versions/node/v6.10.3/lib/node_modules/serverless/lib/plugins/aws/info/index.js:45:10)
    at BbPromise.reduce (/Users/jfate/.nvm/versions/node/v6.10.3/lib/node_modules/serverless/lib/classes/PluginManager.js:372:55)
From previous event:
    at PluginManager.invoke (/Users/jfate/.nvm/versions/node/v6.10.3/lib/node_modules/serverless/lib/classes/PluginManager.js:372:22)
    at PluginManager.run (/Users/jfate/.nvm/versions/node/v6.10.3/lib/node_modules/serverless/lib/classes/PluginManager.js:403:17)
    at variables.populateService.then (/Users/jfate/.nvm/versions/node/v6.10.3/lib/node_modules/serverless/lib/Serverless.js:102:33)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
From previous event:
    at Serverless.run (/Users/jfate/.nvm/versions/node/v6.10.3/lib/node_modules/serverless/lib/Serverless.js:89:74)
    at serverless.init.then (/Users/jfate/.nvm/versions/node/v6.10.3/lib/node_modules/serverless/bin/serverless:42:50)
```
