### ISSUE TITLE
Deploying does not rely on artifact config parameter

### ISSUE THREAD

**Issue by hadrien** [serverless/serverless#3526]
# This is a bug report

### What went wrong?

Running `sls deploy` does not take the artifact parameter into account, it zips the whole directory 
 and deploys it rather than just take the artifact.

### What did you expect should have happened?

`sls deploy` should (it did yesterday):

* Deploy artifact zip file when it exists;
* Fail when artifact zip file does not exist

### What was the config you used?

```yaml
service: poipoi

frameworkVersion: ">=1.12.0"

provider:
  name: aws
  runtime: python3.6
  stage: dev
  region: us-east-1
  memorySize: 128
  timeout: 300
  # KMS Key used for encryption/decryption
  kmsKeyArn: arn:aws:kms:us-east-1:XXXXXXXXX:key/XXXXXXX

package:
  artifact: poipoi.zip

custom:
  actual_stage: ${opt:stage, self:provider.stage}
  dev:
    audience: XXXXXXX
    client_id: XXXXXXX
    # client_secret is encrypted using KMS poipoi/lambdas
    # $ aws kms encrypt --key-id alias/poipoi/lambdas --plaintext <secret>
    client_secret: |
      AXXXXXXXXXXXXXXXXXXXXXXdqT/KPS365PqQ4jY5Vi64RpFiVwAAAKIwgZ8GCSqGSIb3DQEHB
      XXXXXXX...
    log_level: DEBUG
    oauth_token_url: XXXXXXX
    poipoi_url: XXXXXXX


functions:
  poipoi:
    handler: poipoi.handler
    events:
      - stream: arn:aws:kinesis:us-east-1:XXXX:stream/XXXXX-${self:custom.actual_stage}
    environment:
      poipoi_url: ${self:custom.${self:custom.actual_stage}.poipoi_url}
      client_id: ${self:custom.${self:custom.actual_stage}.client_id}
      client_secret: ${self:custom.${self:custom.actual_stage}.client_secret}
      audience: ${self:custom.${self:custom.actual_stage}.audience}

```

### What stacktrace or error message from your provider did you see?

None.

It just zips everything and deploys it. 

Then AWS Lambda fail constantly as the package deployed is non-sense.

Thanks!

**Comment by hadrien** [comment]
Sorry if duplicates, it might be related to 
* #2837
* #2895

**Comment by hadrien** [comment]
SORRY 📣  
:'( 
I was using a dev version of serverless

**Comment by pmuens** [comment]
@hadrien thanks for opening (and closing)! 👍 

Yes, that should be fixed with v1.12.

We faced the exact error yesterday during out test-marathon for the new `package` / `deploy` separation.

**Comment by dlcron** [comment]
```
service: ss

frameworkVersion: ">=1.12.0"

provider:
  name: aws
  runtime: python3.6
  stage: ${opt:stage}

# lambda functions and events trigerring them
functions:
  create_vast:
    handler: ss.ss.xxx
    memorySize: 128
    timeout: 5
    events:
      - http:
          path: create
          method: post
          authorizer: aws_iam
    artifact: sss.zip
```

It still doesn't work on 1.13.2. It zips everything from root folder.

**Comment by shikasta-kashti** [comment]
I'm facing same issue with `serverless package` command. I'm using the latest version. I have opened issue: #3684.

**Comment by pmuens** [comment]
@shikasta-kashti thanks for opening! We'll look into it 👍
