### ISSUE TITLE
Change Authorizer type to "REQUEST" (instead of "TOKEN")

### ISSUE THREAD

**Issue by craigdrayton** [serverless/serverless#4325]
# This is a Feature Proposal
## Description
Change Authorizer type to "REQUEST" (instead of "TOKEN") so that the Authorizer function receives all of the parameters passed to the main function (through lamba-proxy).

As-is, it is not possible to use any parameters in the Authorizer function (other than a single authorization header) which greatly restricts what is possible in the Authorizer.

See https://forum.serverless.com/t/set-custom-authorizer-type-to-request-not-token/2760/3

## Additional Data

* ***Serverless Framework Version you're using***:
* ***Operating System***:
* ***Stack Trace***:
* ***Provider Error messages***:

**Comment by horike37** [comment]
Thank you for the suggestion @craigdrayton 😁 That's a nice idea 👍
Only one concern is that it would be a breaking change. We need to confirm that.

**Comment by craigdrayton** [comment]
To avoid the breaking change, could leave TOKEN as the default with REQUEST available as an option. Cheers :-)

**Comment by horike37** [comment]
Thank @craigdrayton for getting back 🙌

How do the parameters look like with REQUEST?
If only adding some json items based on TOKEN, it would not be the breaking change.

**Comment by craigdrayton** [comment]
AWS implementation details here:
https://aws.amazon.com/about-aws/whats-new/2017/09/amazon-api-gateway-now-supports-enhanced-request-authorizers/

http://docs.aws.amazon.com/apigateway/latest/developerguide/use-custom-authorizer.html

It may be as simple as setting 'type' to 'REQUEST':
http://docs.aws.amazon.com/apigateway/api-reference/resource/authorizer/#type

**Comment by horike37** [comment]
Thanks @craigdrayton for providing the official information 👍

Here is Token type
```
{
    "type":"TOKEN",
    "authorizationToken":"<caller-supplied-token>",
    "methodArn":"arn:aws:execute-api:<regionId>:<accountId>:<apiId>/<stage>/<method>/<resourcePath>"
}
```

Here is REQUEST type
```
{
    "type": "REQUEST",
    "methodArn": "arn:aws:execute-api:us-east-1:123456789012:s4x3opwd6i/test/GET/request",
    "resource": "/request",
    "path": "/request",
    "httpMethod": "GET",
    "headers": {
        "X-AMZ-Date": "20170718T062915Z",
        "Accept": "*/*",
        "HeaderAuth1": "headerValue1",
        "CloudFront-Viewer-Country": "US",
        "CloudFront-Forwarded-Proto": "https",
        "CloudFront-Is-Tablet-Viewer": "false",
        "CloudFront-Is-Mobile-Viewer": "false",
        "User-Agent": "...",
        "X-Forwarded-Proto": "https",
        "CloudFront-Is-SmartTV-Viewer": "false",
        "Host": "....execute-api.us-east-1.amazonaws.com",
        "Accept-Encoding": "gzip, deflate",
        "X-Forwarded-Port": "443",
        "X-Amzn-Trace-Id": "...",
        "Via": "...cloudfront.net (CloudFront)",
        "X-Amz-Cf-Id": "...",
        "X-Forwarded-For": "..., ...",
        "Postman-Token": "...",
        "cache-control": "no-cache",
        "CloudFront-Is-Desktop-Viewer": "true",
        "Content-Type": "application/x-www-form-urlencoded"
    },
    "queryStringParameters": {
        "QueryString1": "queryValue1"
    },
    "pathParameters": {},
    "stageVariables": {
        "StageVar1": "stageValue1"
    },
    "requestContext": {
        "path": "/request",
        "accountId": "123456789012",
        "resourceId": "05c7jb",
        "stage": "test",
        "requestId": "...",
        "identity": {
            "apiKey": "...",
            "sourceIp": "..."
        },
        "resourcePath": "/request",
        "httpMethod": "GET",
        "apiId": "s4x3opwd6i"
    }
}
```

As far as looking, REQUEST stuff does not exactly cover Token stuff. Therefore we had better adopt the plan which adding optional parameters in serverless.yml something like this. Off course leave TOKEN as the default.

``` yaml
authorizer:
  name: authorizerFunc
  type: token or request
```

**Comment by DavidWells** [comment]
+1 for this.

I ran into limitations with `token` custom authorizer myself on Friday.

The `type: request` option here would solve it

**Comment by Hendrixer** [comment]
Can we do this please! It's a huge brick wall

**Comment by viz** [comment]
As a bit of extra info, this becomes important if you're deploying individual services and aggregating under a single custom domain using basepaths. In this instance the TOKEN authoriser doesn't receive any information about the basepath. So if I have a `userService` mounted on the `/users` basepath, if I see a request for `/users/token` as an example, the custom authoriser can only see evidence of a request for `/token` in the methodARN of the `event` object.

Before I started breaking my project smaller services (https://github.com/serverless/serverless/issues/3411) this wasn't an issue - my authoriser was able to look at the methodARN and compare to permissions contained in the token. Unfortunately with the basepath approach, my authoriser which sees a permission for `GET::users:token` can't tell the request was for the `/users` basepath.

With the advent of REQUEST authoriser type I can deal with this issue, so just need support for this type in serverless :-)

**Comment by intoxicated** [comment]
just curious, when this patch will be available on npm? @horike37

**Comment by horike37** [comment]
@intoxicated 
Sorry, we haven't decided the next release schedule yet :cry: 
I personally think it's about time for that though.

**Comment by intoxicated** [comment]
@horike37 Not a problem 👍 In the meantime, is there a way to work around this? or should I just wait for next release?

**Comment by horike37** [comment]
@intoxicated
There is not a workaround for that. Please wait for next release :smile:

**Comment by ozbillwang** [comment]
@intoxicated 

run `./scripts/shrinkwrap && node ./scripts/pre-release.js`, this build will generate serverless command under local `bin/serverless`

Then you should be fine to use this latest version with `<full_serverless_repo_path>/bin/serverless deploy`

**Comment by ozbillwang** [comment]
@intoxicated 

run below commands, this build will generate new serverless framework.
```
cd <serverless_repo_full_path>
export SENTRY_DSN=demo
./scripts/shrinkwrap && node ./scripts/pre-release.js
ls -l bin/serverless
```
Then you should be fine to use this latest version with `<serverless_repo_full_path>/bin/serverless deploy`

**Comment by tafs7** [comment]
this should be fixed and closed as part of [Release v1.24.0](https://github.com/serverless/serverless/releases/tag/v1.24.0)

**Comment by crsepulv** [comment]
Hi @tafs7 this goes to the release 1.24.0? , I installed v.1.26.1 and I still can't make it work using type: Request. there is some documentation related to this?

**Comment by hadasz** [comment]
+1
