### ISSUE TITLE
Using the same API key in multiple services

### ISSUE THREAD

**Issue by okarlsson** [serverless/serverless#4664]
I'm working on a serverless project that's beginning to get quite big with a lot of functions and data models. And recently got the following error message: `The CloudFormation template is invalid: Template format error: Number of resources 212, is greater than maximum allowed, 200.`

So I guess that I should start breaking up my project in different services. One per data model. Currently I have two API-keys for two apps that are going to user the API:

```
apiKeys:
    - xxapp
    - yyapp
```

But when I try to deploy my new service I get the following error: `ApiGatewayApiKey2 - yyapp already exists in stack arn:aws:cloudformation:eu-west-1:*:stack/*/*.`

How can I use the same API key in different services? Or is the only way to have different names of the API-keys but with the same value?

**Comment by horike37** [comment]
Thank you for reporting @okarlsson :+1: 

You ran into CloudFormation resource limit. Therefore you might want to separate stack by using https://github.com/dougmoscrop/serverless-plugin-split-stacks.

**Comment by okarlsson** [comment]
Thanks for the reply @horike37 !

I ended up splitting my serverless into one serverless service per data model and created a custom domain name with base path mappings that maps to my separate services. All good so far.

But I could'nt find a way to use the same API-key in all my services. So I ended up with not specifying the API-keys in my serverless template and mapping all my services to a usage plan manually through the API Gateway console.

**Comment by macstr1k3r** [comment]
Afaik upon consecutive deploys serverless will teardown your api and create a new one.

All manual edits will be lost in this case

**Comment by HyperBrain** [comment]
@macstr1k3r That's not true. SLS will not create a new APIG API on each deploy (so the api id and root resource ids stay the same), but it creates a new APIG deployment resource on every deploy, which recreates the stage - because SLS uses an implicitly created stage via the stage name at the deployment resource. That is necessary, because an APIG stage is on AWS side the persisted state of the deployed API consisting of the previously deployed APIG methods and paths.

Of course that means, that any manual stage configuration will be overwritten on the next deployment.
The only way around that is, to work with a separate AWS::ApiGateway::Stage resource in the stacks and reference that in the APIG deployment resource. That allows to keep all stage specific settings.

APIKeys are also partly stage dependent.

**Comment by okarlsson** [comment]
Thanks for the explanation @HyperBrain !

Seems like the API:s referenced as Associated API Stages in my usage plan remains after I make a new deploy of the API with serverless.  How can they still be referenced after beeing added manually through the console if the stage is teared down and created with each deploy?

**Comment by rrahul963** [comment]
@okarlsson you can use this plugin to use the same api key for multiple serverless services https://github.com/rrahul963/serverless-add-api-key

Disclaimer: i created this plugin for my personal use. If you face any issues feel free to message me

**Comment by Imran99** [comment]
@rrahul963 Awesome just what I was looking for. The issue for me was that I need to use a predefined value for the api key. Although the aws cli supports this, Cloudformation (and therefore serverless) does not.

**Comment by HarryPooni-Amido** [comment]
> @okarlsson you can use this plugin to use the same api key for multiple serverless services https://github.com/rrahul963/serverless-add-api-key
> 
> Disclaimer: i created this plugin for my personal use. If you face any issues feel free to message me

Hi Rahul,

Do i need a usage plan to enable the APIKey plugin? I have set my function to Private and added the API Key section to custom block. I am getting 403 for every request, what am i missing?

**Comment by HarryPooni-Amido** [comment]
Hi Rahul,

I have installed, the latest today. The config mirrors what you’ve sent on your message.

I am not sure why the key is not being accepted….

Ta
Harry

**Comment by Imran99** [comment]
@HarryPooni-Amido @rrahul963 I think there is a bug in the latest version, 2.1.2 should be fine

**Comment by rrahul963** [comment]
@Imran99 thanks for pointing that out..
@HarryPooni-Amido  -  i have updated the code and published the new version.. please use the latest version and try now.. 
sorry for the inconvenience..

**Comment by HarryPooni-Amido** [comment]
Thanks Guys all working now 😊

**Comment by HarryPooni-Amido** [comment]
> @Imran99 thanks for pointing that out..
> @HarryPooni-Amido - i have updated the code and published the new version.. please use the latest version and try now..
> sorry for the inconvenience..

Thanks for the update the Custom API key is still not adding the key to the api, so all requests are returning a 403. When i add the key name to the provider block, then i a get a dynamic key from the console window.

**Comment by FarwaCielo** [comment]
Hi @rrahul963 ,

**Comment by FarwaCielo** [comment]
Hi @rrahul963 
I need some help getting the plugin to work. My serverless.yml looks like this:

`plugins:
  - serverless-domain-manager
  - serverless-add-api-key
service: cielo-cloud-myrules
provider:
  name: aws
  memorySize: 128
  timeout: 30
  runtime: python2.7
  stage: ${opt:stage}
  account: ${file(../.././variables-${self:provider.stage}.yml):account}
  customAuthorizer: ${file(../.././variables-${self:provider.stage}.yml):customAuthorizer}
  logRetentionInDays:  ${file(../.././variables-${self:provider.stage}.yml):logRetentionInDays}
  region: us-east-1
  environment:
    SERVICE_NAME: myrules
custom:
  customDomain:
    domainName: ${file(../.././variables-${self:provider.stage}.yml):domainName}
    stage: ${self:provider.stage}
    basePath: 'myrules'
    endpointType: ${file(../.././variables-${self:provider.stage}.yml):endpointType}
    certificateArn: ${file(../.././variables-${self:provider.stage}.yml):certificateArn}
    certificateName: ${file(../.././variables-${self:provider.stage}.yml):certificateName}
    createRoute53Record: ${file(../.././variables-${self:provider.stage}.yml):createRoute53Record}
    hostedZoneId: ${file(../.././variables-${self:provider.stage}.yml):hostedZoneId}
  apiKeys:
   - ${file(../.././variables-${self:provider.stage}.yml):ServerlessCoreAPIKey}
functions:
  rest_myrules_post:
    handler: rest_myrules_post.lambda_handler
    environment:
      stage: ${self:provider.stage}
    memorySize: ${self:provider.memorySize}
    timeout: ${self:provider.timeout}
    logRetentionInDays: ${self:provider.logRetentionInDays}
    role: arn:aws:iam::${self:provider.account}:role/lambda_basic_execution
    events:
    - http:
        path: /
        cors:
          origin: '*'
          headers:
          - Content-Type
        method: post
        private: true
        integration: lambda
        request:
          template:
`

**Comment by FarwaCielo** [comment]
> 
> 
> Hi @rrahul963
> I need some help getting the plugin to work. My serverless.yml looks something like this:
> 
> ```
> plugins:
>   - serverless-domain-manager
>   - serverless-add-api-key
> service: cielo-cloud-myrules
> provider:
>   logRetentionInDays:  ${file(../.././variables-${self:provider.stage}.yml):logRetentionInDays}
>   region: us-east-1
>   environment:
>     SERVICE_NAME: myrules
> custom:
>   customDomain:
>     domainName: ${file(../.././variables-${self:provider.stage}.yml):domainName}
>     stage: ${self:provider.stage}
>     basePath: 'myrules'
>     endpointType: ${file(../.././variables-${self:provider.stage}.yml):endpointType}
>     certificateArn: ${file(../.././variables-${self:provider.stage}.yml):certificateArn}
>     certificateName: ${file(../.././variables-${self:provider.stage}.yml):certificateName}
>     createRoute53Record: ${file(../.././variables-${self:provider.stage}.yml):createRoute53Record}
>     hostedZoneId: ${file(../.././variables-${self:provider.stage}.yml):hostedZoneId}
>   apiKeys:
>    - ${file(../.././variables-${self:provider.stage}.yml):ServerlessCoreAPIKey}
> functions:
>   rest_myrules_post:
>     handler: rest_myrules_post.lambda_handler
>     events:
>     - http:
>         path: /
>         cors: true
>         method: post
>         private: true
>         integration: lambda
> ```
> 
> And when i do "sls deploy -s dev", I get this error:
> 
> > Serverless plugin "serverless-add-api-key" initialization errored: Unexpected token function
> > Environment Information -----------------------------
> > OS:                     win32
> > Node Version:           6.10.0
> > Serverless Version:     1.27.3
> 
> what could be wrong, I am guessing its something to do with updates?

Okay I tried with node 10.6.* version and it worked well except that an undefined usage plan was created for my api stage without an API key. How to fix this?

**Comment by rrahul963** [comment]
@FarwaCielo - the `apiKeys` list needs an `object` with `name` key in it.. can you try changing it to

```
apiKeys:
   - name: ${file(../.././variables-${self:provider.stage}.yml):ServerlessCoreAPIKey}
```
i should have handled this as an error. Will update plugin in a while.

**Comment by rrahul963** [comment]
> > @Imran99 thanks for pointing that out..
> > @HarryPooni-Amido - i have updated the code and published the new version.. please use the latest version and try now..
> > sorry for the inconvenience..
> 
> Thanks for the update the Custom API key is still not adding the key to the api, so all requests are returning a 403. When i add the key name to the provider block, then i a get a dynamic key from the console window.

@HarryPooni-Amido  -  sorry i didn't see your response, are you still facing issues?

**Comment by FarwaCielo** [comment]
> 
> 
> @FarwaCielo - the `apiKeys` list needs an `object` with `name` key in it.. can you try changing it to
> 
> ```
> apiKeys:
>    - name: ${file(../.././variables-${self:provider.stage}.yml):ServerlessCoreAPIKey}
> ```
> 
> i should have handled this as an error. Will update plugin in a while.

yes @rrahul963 that solved the issue. thanks (y)

**Comment by FarwaCielo** [comment]
> 
> 
> > @Imran99 thanks for pointing that out..
> > @HarryPooni-Amido - i have updated the code and published the new version.. please use the latest version and try now..
> > sorry for the inconvenience..
> 
> Thanks for the update the Custom API key is still not adding the key to the api, so all requests are returning a 403. When i add the key name to the provider block, then i a get a dynamic key from the console window.

Hi @HarryPooni-Amido 
you will need to configure usage plan too. The api that is being deployed and the api key will both get assigned to the usage plan. As you cannot directly assign an API key to the API itself. I have shared a sample in one of the replies above. Here is the updated chunk that worked for me for adding usage plan and api key (as it had some mistakes in the previous reply):

```
 apiKeys:
   - name: ${file(../.././variables-${self:provider.stage}.yml):ServerlessCoreAPIKey}
  usagePlan:
    name: ${file(../.././variables-${self:provider.stage}.yml):RestAPIUsagePlan}
    throttle:
      burstLimit: 2000
      rateLimit: 5000
```
Hope this helps!!

**Comment by dls314** [comment]
Hi,

@rrahul963 -- Sorry for a note on the long-closed issue, but do you know if this use case still requires your plugin? I think it seems to. Attempting the following only works for the first deployment; subsequent deployments fail. I ... think it could be due to the issue described here :-)

```
provider:

  name: aws
  apiKeys:
    - name: ${{self:service.name}}-${{self:provider.stage}}-api-key
      value: ${{self:custom.ApiKey}}
```
