### ISSUE TITLE
Node.js v10.7 fails to install serverless

### ISSUE THREAD

**Issue by kei-ito** [serverless/serverless#5133]
# This is a Bug Report

## Description

For bug reports:
* What went wrong?
  "npm install" fails at the serverless@1.28.0 postinstall script.

* What did you expect should have happened?
  I had expected to install the serverless package.

* What was the config you used?: Nothing.
* What stacktrace or error message from your provider did you see?: Nothing.

## Additional Data

* ***Serverless Framework Version you're using***:
v1.28.0

* ***Operating System***:
macOS 10.13.6
Node.js v10.7.0

* ***Stack Trace***:

```
$ npm install

> serverless@1.28.0 postinstall /Users/itok/workspace/serverless
> node ./scripts/postinstall.js

Error: socket hang up
    at createHangUpError (_http_client.js:313:15)
    at TLSSocket.socketOnEnd (_http_client.js:416:23)
    at TLSSocket.emit (events.js:187:15)
    at TLSSocket.EventEmitter.emit (domain.js:442:20)
    at endReadableNT (_stream_readable.js:1081:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```

* ***Provider Error messages***: Nothing.

**Comment by kei-ito** [comment]
I inserted `console.log` at [/lib/utils/segment.js#L19](https://github.com/serverless/serverless/blob/v1.28.0/lib/utils/segment.js#L19) and ran `npm install`.
```
TypeError [ERR_INVALID_ARG_TYPE]: The "msecs" argument must be of type number. Received type string
    at validateTimerDuration (internal/timers.js:134:11)
    at TLSSocket.Socket.setTimeout (net.js:413:11)
    at setRequestSocket (_http_agent.js:361:10)
    at handleSocketCreation_Inner (_http_agent.js:349:7)
    at oncreate (_http_agent.js:224:5)
    at Agent.createSocket (_http_agent.js:229:5)
    at Agent.addRequest (_http_agent.js:185:10)
    at new ClientRequest (_http_client.js:239:16)
    at Object.request (https.js:272:10)
    at /Users/itok/workspace/serverless/node_modules/agent-base/patch-core.js:23:20
    at /Users/itok/workspace/serverless/node_modules/node-fetch/index.js:124:13
    at new Promise (<anonymous>)
    at new Fetch (/Users/itok/workspace/serverless/node_modules/node-fetch/index.js:49:9)
    at Fetch (/Users/itok/workspace/serverless/node_modules/node-fetch/index.js:37:10)
    at request (/Users/itok/workspace/serverless/lib/utils/segment.js:9:10)
    at Object.track (/Users/itok/workspace/serverless/lib/utils/segment.js:32:10)
    at BbPromise.then (/Users/itok/workspace/serverless/lib/classes/Utils.js:328:17)
    at tryCatcher (/Users/itok/workspace/serverless/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/itok/workspace/serverless/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/Users/itok/workspace/serverless/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromiseCtx (/Users/itok/workspace/serverless/node_modules/bluebird/js/release/promise.js:606:10)
    at Async._drainQueue (/Users/itok/workspace/serverless/node_modules/bluebird/js/release/async.js:138:12)
    at Async._drainQueues (/Users/itok/workspace/serverless/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/Users/itok/workspace/serverless/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:696:18)
    at tryOnImmediate (timers.js:667:5)
    at processImmediate (timers.js:649:5)
    at process.topLevelDomainCallback (domain.js:121:23)
```

The [`timeout` parameter](https://github.com/serverless/serverless/blob/v1.28.0/lib/utils/segment.js#L14) should be a number. It was passed to [validateTimerDuration](https://github.com/nodejs/node/blob/v10.7.0/lib/internal/timers.js#L134) and occurs the error. But I don't know why the request failed.

**Comment by kei-ito** [comment]
Here's the CI results: https://travis-ci.org/serverless/serverless/builds/405660518
![screenshot 2018-07-19 14 41 00](https://user-images.githubusercontent.com/7359068/42923696-da85314c-8b61-11e8-9282-98c148148878.png)

**Comment by chrgit** [comment]
Same here !
Node.js 10.7.0
Mac OS X El Capitan 10.11.6

**Comment by pmuens** [comment]
Just merged the fix! Thanks for investigating and working on that @kei-ito 👍

**Comment by winglight** [comment]
@pmuens I tried : yarn global add serverless@latest, that still not work. Would you like tell me how could I get your patched package? 

My env: MacOS 10.13, Node 10.7.0

**Comment by michaellashinsky** [comment]
> @pmuens I tried : yarn global add serverless@latest, that still not work. Would you like tell me how could I get your patched package?

It has not been published yet.

**Comment by michaellashinsky** [comment]
Looks like this was fixed today.  I can now install serverless on Node 10.7.0

**Comment by eahefnawy** [comment]
Yep just got published! Thanks everyone for reporting and fixing 😊

**Comment by Br0kensword** [comment]
I am able to deploy successfully, but I tend to still get some socket hangup errors getting logged in node 10.7.0 on MacOS

Error: socket hang up
    at createHangUpError (_http_client.js:313:15)
    at TLSSocket.socketOnEnd (_http_client.js:416:23)
    at TLSSocket.emit (events.js:187:15)
    at TLSSocket.EventEmitter.emit (domain.js:442:20)
    at endReadableNT (_stream_readable.js:1081:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)

**Comment by eahefnawy** [comment]
@Br0kensword what's your serverless version? did you upgrade to v1.29.0?

**Comment by MdShuaib** [comment]
> I have changed my node js version from 10.7.0 to version 8.11.3 
and it works for me

**Comment by Br0kensword** [comment]
Sorry for my late reply, after upgrading to 1.29.0 I no longer had this issue.

**Comment by arpangrwl** [comment]
But the below solved my issue  👍 

nvm install v10.6.0

**Comment by ZHamburglar** [comment]
The following command worked for me as well.

`nvm install v10.6.0`

**Comment by dave-k** [comment]
Same issue

    macOS 10.13.6
    serverless v1.31.0
    node v10.8.0
 
    $ npm install
   
    > serverless@1.26.1 postinstall /Users/dev/project3/node_modules/serverless
    > node ./scripts/postinstall.js

    events.js:167
          throw er; // Unhandled 'error' event
          ^
    Error: socket hang up
        at createHangUpError (_http_client.js:313:15)
        at TLSSocket.socketOnEnd (_http_client.js:416:23)
        at TLSSocket.emit (events.js:187:15)
        at TLSSocket.EventEmitter.emit (domain.js:442:20)
        at endReadableNT (_stream_readable.js:1081:12)
        at process._tickCallback (internal/process/next_tick.js:63:19)
    Emitted 'error' event at:
        at TLSSocket.socketOnEnd (_http_client.js:416:9)
        at TLSSocket.emit (events.js:187:15)
        [... lines matching original stack trace ...]
        at process._tickCallback (internal/process/next_tick.js:63:19)
    npm WARN @ng-toolkit/pwa@1.1.41 requires a peer of @angular/service-worker@^6.0.5 but none is installed. You must install peer dependencies yourself.
    npm WARN The package ts-loader is included as both a dev and production dependency.
    npm WARN The package webpack-cli is included as both a dev and production dependency.

    npm ERR! code ELIFECYCLE
    npm ERR! errno 1
    npm ERR! serverless@1.26.1 postinstall: `node ./scripts/postinstall.js`
    npm ERR! Exit status 1
    npm ERR! 
    npm ERR! Failed at the serverless@1.26.1 postinstall script.
    npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

    npm ERR! A complete log of this run can be found in:
    npm ERR!     /Users/dev/.npm/_logs/2018-09-14T21_40_41_531Z-debug.log

**Comment by faridhajnal** [comment]
I am having the exact same error. The difference is that I am targeting specific package version (1.5.1), while using node 10.14.2. Installing latest serverless with **npm i -g serverless** works, but I cannot install that specific version locally nor globally. Please help!

**Comment by faridhajnal** [comment]
> +1
> 
> Edit:
> I install 10.6.0 specific version and the problem has been resolved

Same for me... only solution so far

**Comment by quynhbkit** [comment]
But the below solved my issue:
$ rm package-lock.json
$ npm install
