### ISSUE TITLE
Serverless is timing out and hanging up the socket

### ISSUE THREAD

**Issue by Nemesisesq** [serverless/serverless#5180]
# BUG

When I try to deploy or do any action against AWS I get an Error: socket hang up

I expect that he comand woud suceed but it time s out
Error: socket hang up
    at createHangUpError (_http_client.js:313:15)
    at TLSSocket.socketOnEnd (_http_client.js:416:23)
    at TLSSocket.emit (events.js:187:15)
    at TLSSocket.EventEmitter.emit (domain.js:442:20)
    at endReadableNT (_stream_readable.js:1081:12)

I'm running node 10.7.0

and serverless 1.28.0

Thanks

**Comment by jasonkuhrt** [comment]
Example but happened to me also for `custom_domain` and others.

```
❯ sls --stage dev secrets set --name a --text a-secret
Serverless: Generating Serverless Secrets Config
Serverless: Secret a stored! Remember to add it to your environmentSecrets section(s) to retrieve it!
events.js:167
      throw er; // Unhandled 'error' event
      ^

Error: socket hang up
    at createHangUpError (_http_client.js:313:15)
    at TLSSocket.socketOnEnd (_http_client.js:416:23)
    at TLSSocket.emit (events.js:187:15)
    at TLSSocket.EventEmitter.emit (domain.js:442:20)
    at endReadableNT (_stream_readable.js:1081:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
Emitted 'error' event at:
    at TLSSocket.socketOnEnd (_http_client.js:416:9)
    at TLSSocket.emit (events.js:187:15)
    [... lines matching original stack trace ...]
    at process._tickCallback (internal/process/next_tick.js:63:19)
```

```
❯ node --version
v10.7.0
```

**Comment by jasonkuhrt** [comment]
I tried with `10.8.0`. Same issue as well.

I DO NOT get this issue with `10.6.0`, however.

**Comment by eahefnawy** [comment]
We fixed this. Please upgrade to v1.29.2

**Comment by jasonkuhrt** [comment]
@eahefnawy we were using 1.29.2 I believe but will double check.

**Comment by congcharlieqin** [comment]
I'm still having this happen on 1.29.2. Please let me know if there's any other info I can provide to troubleshoot.

```
serverless package
head: illegal line count -- -1
events.js:167
      throw er; // Unhandled 'error' event
      ^

Error: write EPIPE
    at WriteWrap.afterWrite [as oncomplete] (net.js:836:14)
Emitted 'error' event at:
    at onwriteError (_stream_writable.js:431:12)
    at onwrite (_stream_writable.js:456:5)
    at _destroy (internal/streams/destroy.js:40:7)
    at Socket.stdout._destroy (internal/process/stdio.js:25:7)
    at Socket.destroy (internal/streams/destroy.js:32:8)
    at WriteWrap.afterWrite [as oncomplete] (net.js:838:10)
```

```
serverless -v
head: illegal line count -- -1
events.js:167
      throw er; // Unhandled 'error' event
      ^

Error: write EPIPE
    at WriteWrap.afterWrite [as oncomplete] (net.js:836:14)
Emitted 'error' event at:
    at onwriteError (_stream_writable.js:431:12)
    at onwrite (_stream_writable.js:456:5)
    at _destroy (internal/streams/destroy.js:40:7)
    at Socket.stdout._destroy (internal/process/stdio.js:25:7)
    at Socket.destroy (internal/streams/destroy.js:32:8)
    at WriteWrap.afterWrite [as oncomplete] (net.js:838:10)
1.29.2
```

```
node -v
v10.8.0
```

**Comment by Nemesisesq** [comment]
I just re initialized the app and its working again.

**Comment by continuata** [comment]
I'm getting this with node v10.9.0 and serverless v1.5.0

```
Serverless: Stack update finished...
events.js:167
      throw er; // Unhandled 'error' event
      ^

Error: socket hang up
    at createHangUpError (_http_client.js:322:15)
    at TLSSocket.socketOnEnd (_http_client.js:425:23)
    at TLSSocket.emit (events.js:187:15)
    at TLSSocket.EventEmitter.emit (domain.js:442:20)
    at endReadableNT (_stream_readable.js:1085:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
Emitted 'error' event at:
    at TLSSocket.socketOnEnd (_http_client.js:425:9)
    at TLSSocket.emit (events.js:187:15)
    [... lines matching original stack trace ...]
    at process._tickCallback (internal/process/next_tick.js:63:19)
```

**Comment by continuata** [comment]
actually having this issue again repeatedly ... literally closed everything else down that could possibly be using a socket for updating.
This is very irritating, it's taking around 10 `sls deploy` calls until one gets through.

**Comment by eahefnawy** [comment]
@continuata "serverless v1.5.0"?! 🤔 ... the latest version is 1.30.3

**Comment by trops** [comment]
serverless 1.32.0, having same error
node: 10.10.0

```
Serverless: Packaging service...
events.js:167
      throw er; // Unhandled 'error' event
```

**Comment by squarebizchris** [comment]
@trops I had the problem as well and downgraded to Node 10.6.0 and things are working

**Comment by rush86999** [comment]
i m getting a socket hangup as well after install npm modules in the lambda function; latest node 10.13.0 and sls 1.28.0

```Error: socket hang up
    at createHangUpError (_http_client.js:322:15)
    at TLSSocket.socketOnEnd (_http_client.js:425:23)
    at TLSSocket.emit (events.js:187:15)
    at TLSSocket.EventEmitter.emit (domain.js:442:20)
    at endReadableNT (_stream_readable.js:1094:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)```

**Comment by klintan** [comment]
Think  this might be related, trying to install serverless-python-requirements. Get the same error whenever I try to do anything serverless related. Reinstalled serverless and node.

`sls --version 
1.26.1`

`node --version
v11.4.0`

`mac os mojave`

```sls plugin install -n serverless-python-requirements
Serverless: Installing plugin "serverless-python-requirements@latest" (this might take a few seconds...)
Serverless: Successfully installed "serverless-python-requirements@latest"
events.js:174
      throw er; // Unhandled 'error' event
      ^

Error: socket hang up
    at createHangUpError (_http_client.js:330:15)
    at TLSSocket.socketOnEnd (_http_client.js:433:23)
    at TLSSocket.emit (events.js:194:15)
    at TLSSocket.EventEmitter.emit (domain.js:441:20)
    at endReadableNT (_stream_readable.js:1107:12)
    at process.internalTickCallback (internal/process/next_tick.js:72:19)
Emitted 'error' event at:
    at TLSSocket.socketOnEnd (_http_client.js:433:9)
    at TLSSocket.emit (events.js:194:15)
    [... lines matching original stack trace ...]
    at process.internalTickCallback (internal/process/next_tick.js:72:19)```

**Comment by dschep** [comment]
@klintan, could you try upgrading your serverless version? @eahefnawy mentioned above that it was fixed in v1.29.2

**Comment by adnanmomin** [comment]
> @klintan, could you try upgrading your serverless version? @eahefnawy mentioned above that it was fixed in v1.29.2

This helped me after the long search and multiple node installations and uninstallations.

**Comment by pmuens** [comment]
Closing this since it should've been fixed in the interim. Feel free to re-open if this is still an issue...

**Comment by ademidun** [comment]
Can you please reopen this issue I am still getting the error when trying to deploy to serverless:
`events.js:174
      throw er; // Unhandled 'error' event
`

Serverless: 1.38.0
Node: v11.4.0

Stacktrace:
```
events.js:174
      throw er; // Unhandled 'error' event
      ^

Error: socket hang up
    at createHangUpError (_http_client.js:330:15)
    at TLSSocket.socketOnEnd (_http_client.js:433:23)
    at TLSSocket.emit (events.js:194:15)

```

**Comment by ademidun** [comment]
Update: It seems like I had to install a different version of Node:

`nvm install 8.10`
`nvm use 8.10`

I chose 8.10 because that is what AWS Lambda supports but you can probably do other, more recent versions.

https://stackoverflow.com/questions/7718313/how-to-change-to-an-older-version-of-node-js

https://github.com/serverless/serverless/issues/5133#issuecomment-414104576

**Comment by sioux-hockey** [comment]
I am having the same problem

Node: V10.15.3
Serverless: 1.26.1
