### ISSUE TITLE
Support for Yarn Plug'n'Play

### ISSUE THREAD

**Issue by o-alexandrov** [serverless/serverless#5634]
# This is a Feature Proposal

## Description

Before moving forward, please be informed that [Plug'n'Play is **not** meant to be Yarn-specific](https://dev.to/arcanis/plugnplay-and-tink-4684).
Serverless does not (yet) have [PnP](https://github.com/yarnpkg/rfcs/pull/101) support.

Related links:
- [Getting started PnP](https://gist.github.com/arcanis/02b49752c385908479734d8027d7a6c7)
- [https://github.com/facebook/metro/issues/308](https://github.com/facebook/metro/issues/308)

**Comment by crubier** [comment]
@arcanis 😏 This is me again aha

**Comment by volkipp** [comment]
Curiosity got the best of me, so I started digging into this a little.  It looks like there are about 15 places where serverless is [referencing node_modules folders directly.](https://github.com/serverless/serverless/search?l=JavaScript&q=node_modules)  It seems like they are mostly in tests and housekeeping / uninstall, but I could be off here.

The second snag is with the [ncjsm library](https://github.com/medikoo/ncjsm) not supporting PnP. Ncjsm is also making assumptions about node_modules folders for lookups, so they would either need to implement PnP support, or serverless would need to remove ncjsm as a dependency. Looks like ncjsm is only used in the PluginManager, and a couple places in the CLI. 

I would love to see support for PnP in serverless as well! Happy to help if I can.

**Comment by thiagorp** [comment]
Is there any workaround to make it work atm?

**Comment by jakegibson** [comment]
@thiagorp Not that I am aware of for PnP but if you're just wanting to use yarn 2, you can set `nodeLinker: node-modules` in your .yarnrc so that it creates node_modules instead of using PnP

**Comment by crubier** [comment]
Adding `nodeLinker: node-modules` to the config works but defeats the whole point of yarn v2 / pnp though. For example on our large monorepo it changes the re-install duration from 25s to 1 hour! So not always a practical solution.

**Comment by thiagorp** [comment]
I don't know what the complexity of supporting PnP is. But the fact that no action is being done in this direction conveys a very bad information IMHO. Yarn 2 together with PnP is a great improvement compared to the old `node_modules` approach, serious tools that take developer experience seriously and want stay up to date with technology should definitely at least already be moving in this direction. So far nothing...

**Comment by nkalinov** [comment]
I managed to make it work by using a combination of `yarn pnpify` and symlinks 🎉 Here is what I did:
1. `yarn add --dev @yarnpkg/pnpify`

2. Add `serverless` as a local dependency (to be able to run it with pnpify): `yarn add --dev serverless` 

3. Something screws up while `serverless` searches the installed plugins and threw an error that it cannot find them from this folder `.serverless_plugins/`. 
![image](https://user-images.githubusercontent.com/2777825/78873006-d05ec480-7a52-11ea-8bbd-e908330df784.png)
So to fix the plugins, you have to do the following for each one of them:
  - Unplug it: `yarn unplug serverless-offline` (to provide an extracted version to serverless)
  - Symlink the unplugged plugin folder: `ln -s ../.yarn/unplugged/serverless-offline-virtual-4d8139d5d0/node_modules/serverless-offline .serverless_plugins/serverless-offline`
(**note** the relative path to the plugin: `../.yarn/...` it's because the symlink is within a folder)

4. Verify it's working: `yarn pnpify serverless --verbose`

5. Enjoy! :)

**Comment by esetnik** [comment]
I have been working on [a branch](https://github.com/esetnik/serverless/tree/pnp) which supports serverless pnp without the workarounds mentioned by @nkalinov. If you want to test it out add:

```
    "serverless": "esetnik/serverless#pnp",
```
to your `package.json`. I have other plugins getting loaded, but for a currently unknown reason `serverless-webpack` isn't working.

**Comment by esetnik** [comment]
> The second snag is with the [ncjsm library](https://github.com/medikoo/ncjsm) not supporting PnP. Ncjsm is also making assumptions about node_modules folders for lookups, so they would either need to implement PnP support, or serverless would need to remove ncjsm as a dependency. Looks like ncjsm is only used in the PluginManager, and a couple places in the CLI.

The issue I faced was that `@serverless/inquirer` depends on `ncjsm` and so in my branch i've switched from `@serverless/inquirer` back to `inquirer`. It doesn't have the color customizations, but otherwise seems to work fine.

**Comment by esetnik** [comment]
It looks like this change was made recently in https://github.com/serverless/serverless/pull/7729 so my suggestion is that `@serverless/inquirer` should be modified to avoid depending on `ncjsm`.

**Comment by juuyan** [comment]
any update?

**Comment by cuberoot** [comment]
Also interested in an update.

**Comment by knowroozi** [comment]
We are looking forward to implementing this as well.

**Comment by mungojam** [comment]
It does at least work with yarn 2 now as they have provided a `node_modules` linker option. You don't get the benefits of PnP, but you get the other benefits of yarn 2 like a local package cache.

https://yarnpkg.com/getting-started/migration#if-required-enable-the-node-modules-plugin

**Comment by Bnaya** [comment]
https://yarn.build/ May be a viable option,
"yarn.BUILD also includes a powerful bundle command that can create zips ready for AWS Lambda, Kubernetes, Docker or really anywhere you can run node."

**Comment by ojkelly** [comment]
👋 just sharing how I got this to work for yarn.build.

We start by looking at the monorepo, and based on the package that is going to be deployed we copy the repo to a temp directory. Then look at the dependency graph and remove anything thats not required. This leaves us with a function yarn workspace, with only the required local and remote (npm) deps.

From there we drop a small `entrypoint.js` file that preloads `pnp.js` before loading the `index.js` file of the package.
https://github.com/ojkelly/yarn.build/blob/trunk/packages/plugins/plugin-build/src/commands/bundle/index.ts#L272

```js

"use strict";
const pnp = require("${pnp}").setup();
const index = require("./${main}");
Object.defineProperty(exports, "__esModule", { value: true });
exports.default = index;
```

It’s then just a matter of running `node entrypoint.js` to start the package.

**Comment by theseyi** [comment]
> 👋 just sharing how I got this to work for yarn.build.
> 
> We start by looking at the monorepo, and based on the package that is going to be deployed we copy the repo to a temp directory. Then look at the dependency graph and remove anything thats not required. This leaves us with a function yarn workspace, with only the required local and remote (npm) deps.
> 
> From there we drop a small `entrypoint.js` file that preloads `pnp.js` before loading the `package.json#main` file of the package.
> https://github.com/ojkelly/yarn.build/blob/trunk/packages/plugins/plugin-build/src/commands/bundle/index.ts#L272
> 
> ```js
> "use strict";
> const pnp = require("${pnp}").setup();
> const index = require("./${main}");
> Object.defineProperty(exports, "__esModule", { value: true });
> exports.default = index;
> ```
> 
> It’s then just a matter of running `node entrypoint.js` to start the package.

Just to clarify is this intended to get serverless to work with pnp, or a replacement for serverless? I haven't explored yarn.build but I'm starting to look at it now

**Comment by theseyi** [comment]
> 👋 just sharing how I got this to work for yarn.build.
> 
> We start by looking at the monorepo, and based on the package that is going to be deployed we copy the repo to a temp directory. Then look at the dependency graph and remove anything thats not required. This leaves us with a function yarn workspace, with only the required local and remote (npm) deps.
> 
> From there we drop a small `entrypoint.js` file that preloads `pnp.js` before loading the `package.json#main` file of the package.
> https://github.com/ojkelly/yarn.build/blob/trunk/packages/plugins/plugin-build/src/commands/bundle/index.ts#L272
> 
> ```js
> "use strict";
> const pnp = require("${pnp}").setup();
> const index = require("./${main}");
> Object.defineProperty(exports, "__esModule", { value: true });
> exports.default = index;
> ```
> 
> It’s then just a matter of running `node entrypoint.js` to start the package.



Just to clarify is this intended to get serverless to work with pnp, or a replacement for serverless? I haven't explored yarn.build but I'm starting to look at it now @ojkelly

**Comment by ojkelly** [comment]
> intended to get serverless to work with pnp

This is basically just a script that runs before anything else, and ensures pnp is configured correctly. It is currently missing one other bit, which is to set `NODE_OPTIONS` to require the pnp script too. This ensures child process are also setup with pnp.

see https://github.com/yarnpkg/berry/blob/a76373ac01680b85e6499dc2085abac00d4db575/packages/plugin-pnp/sources/index.ts#L44

More info on the bug https://github.com/ojkelly/yarn.build/issues/50

But yeah, the short of it is there's a `pnp.js` file likely right next to the root `package.json`, and that file needs to be loaded before anything else.

This is relevant for say, building a zip file to send off to lambda or docker to run. See the `yarn bundle` command specifically.

**Comment by arcanis** [comment]
Thanks to @nkalinov and @esetnik's information, I've implemented fixes in the following two PRs:

- https://github.com/serverless/utils/pull/75
- https://github.com/serverless/serverless/pull/8911

The fix in itself is fairly simple: Serverless just needs to use the `createRequire` function when available. Being part of the Node APIs, it intrinsically has support for the runtime resolution, regardless of what the algorithm is for the current session.

To use the fix before it gets merged (I'm not a contributor here so someone will have to greenlight it), try adding the following to your `package.json` file. Let me know if you see another issue:

```json
{
  "resolutions": {
    "@serverless/utils": "arcanis/utils#mael/createrequire",
    "serverless": "arcanis/serverless#mael/createrequire"
  }
}
```

(Note that you'll still need to `require` the `.pnp.js` file at the beginning of your entrypoint - cf [Initializing Plug'n'Play](https://yarnpkg.com/features/pnp#initializing-pnp) in our documentation, and the [comment](https://github.com/serverless/serverless/issues/5634#issuecomment-746068527) here by @ojkelly)

**Comment by sergioramos** [comment]
You can use [serverless-plugin-tree-shake](https://github.com/sergioramos/serverless-plugin-tree-shake). I have examples of Serverless running with the plugin and PnP:

- [With Typescript, PnP, and individual functions](https://github.com/sergioramos/serverless-plugin-tree-shake/tree/master/test/__fixtures__/ts-pnp-individually);
- [With Typescript and PnP](https://github.com/sergioramos/serverless-plugin-tree-shake/tree/master/test/__fixtures__/ts-pnp-single);
- [With Javascript and PnP](https://github.com/sergioramos/serverless-plugin-tree-shake/tree/master/test/__fixtures__/js-pnp-single);
- [With Javascript, PnP, and individual functions](https://github.com/sergioramos/serverless-plugin-tree-shake/tree/master/test/__fixtures__/js-pnp-individually);

We have been using it for a while on an [open source project](https://github.com/yldio/asap-hub).

**Comment by M1kep** [comment]
> Thanks to @nkalinov and @esetnik's information, I've implemented fixes in the following two PRs:
> 
> * [serverless/utils#75](https://github.com/serverless/utils/pull/75)
> * #8911
> 
> The fix in itself is fairly simple: Serverless just needs to use the `createRequire` function when available. Being part of the Node APIs, it intrinsically has support for the runtime resolution, regardless of what the algorithm is for the current session.
> 
> To use the fix before it gets merged (I'm not a contributor here so someone will have to greenlight it), try adding the following to your `package.json` file. Let me know if you see another issue:
> 
> ```json
> {
>   "resolutions": {
>     "@serverless/utils": "arcanis/utils#mael/createrequire",
>     "serverless": "arcanis/serverless#mael/createrequire"
>   }
> }
> ```
> 
> (Note that you'll still need to `require` the `.pnp.js` file at the beginning of your entrypoint - cf [Initializing Plug'n'Play](https://yarnpkg.com/features/pnp#initializing-pnp) in our documentation, and the [comment](https://github.com/serverless/serverless/issues/5634#issuecomment-746068527) here by @ojkelly)

@arcanis  What would be the best way to run `serverless invoke local` with these changes? I've attempted to run via `yarn node serverless invoke local` but that still throws errors about files such as `serverless.node` and `serverless.js` not being found.

**Comment by rally25rs** [comment]
A simple workaround for anyone hoping and praying for Yarn PnP support to find it's way in one day...
You can use a local serverless plugin to load the real plugin you want, which will work with Yarn PnP.
_(Note: This worked for me in Serverless v2.66)_

in `serverless.yml` add a local plugin (starts with `./`)
```yaml
plugins:
  - ./serverless-plugins/serverless-s3-sync
  ```
  
in `./serverless-plugins/serverless-s3-sync.js` just load the real desired plugin from (Yarn PnP) and return it.
```js
module.exports = require('serverless-s3-sync');
```

**Comment by mnapoli** [comment]
Hey everyone! Given this is one of the most upvoted issues, I'd like to clarify:

1. if this feature request is still relevant today
2. what is the benefit that Yarn plug'n'play provides (the end result for users, i.e. the problem this feature would solve)
3. would those benefits only apply to Yarn users, or to any NPM users as well? to standalone binary users too?

From what I gather this would make the installable package lighter, which could make the installation faster? Any idea by how much? Any other benefit?

**Comment by mungojam** [comment]
> 1. if this feature request is still relevant today

Yes, though a little less important as yarn added a node-modules linker option which has unlocked the use of serverless with the latest versions of yarn.

> 2. what is the benefit that Yarn plug'n'play provides (the end result for users, i.e. the problem this feature would solve)

The main benefit for us is the speed of restoring the serverless package and any plugins or other node packages. This is significant for us as our Antivirus slows everything to a crawl when it has to scan a newly populated node-modules folder (which is almost empty for PNP)

> 3. would those benefits only apply to Yarn users, or to any NPM users as well? to standalone binary users too?

Not NPM. But I don't know how standalone works with external plugins and packages. Don't you still need to restore them with npm or yarn?

> From what I gather this would make the installable package lighter, which could make the installation faster? Any idea by how much? Any other benefit?

I don't think impacts the final packaged output assuming all is configured correctly. It's all about the developer experience for us.

**Comment by mungojam** [comment]
Some performance benchmarks are published on pnpm website (comparing npm, pnpm and yarn in both modes):

https://pnpm.io/benchmarks

**Comment by mnapoli** [comment]
> I don't think impacts the final packaged output assuming all is configured correctly. It's all about the developer experience for us.

Ah so this would impact people that develop on Serverless Framework (i.e. those that git clone this repository), not end users?

> > 3. would those benefits only apply to Yarn users, or to any NPM users as well? to standalone binary users too?
>
> Not NPM. But I don't know how standalone works with external plugins and packages. Don't you still need to restore them with npm or yarn?

Got it, standalone wouldn't be impacted then (just wanted to make sure). The dependencies are packaged in the binary.

**Comment by jeysal** [comment]
Another quick note: I don't know much about serverless or how it's implemented, but in general in my experience making tooling and other things work with PnP is usually making things cleaner and using better practices and will also leave the code in a better state for other users since it abstracts away details of the dependency resolution algorithm. For a pretty crude example of what many packages used to do (again not necessarily applicable to serverless specifically), replacing `path.resolve(cwd, 'node_modules', packageName)` with `require.resolve(packageName)` not only fixes PnP but also workspace setups since `node_modules` was never guaranteed to be in the cwd but could be anywhere further up including `/home/node_modules` or `/node_modules`.
(Again just an example, I know the issues with serverless are more complicated due to its unusually implemented plugin system, point is in my experience making PnP work is an overall improvement in its own right)

**Comment by mungojam** [comment]
> > I don't think impacts the final packaged output assuming all is configured correctly. It's all about the developer experience for us.
> 
> Ah so this would impact people that develop on Serverless Framework (i.e. those that git clone this repository), not end users?

Oh sorry, no. I do mean end users then. I wrongly assumed that by end users you meant the consumers of what we produce from the output of `serverless deploy` or similar.

> 
> > > 3. would those benefits only apply to Yarn users, or to any NPM users as well? to standalone binary users too?
> > 
> > 
> > Not NPM. But I don't know how standalone works with external plugins and packages. Don't you still need to restore them with npm or yarn?
> 
> Got it, standalone wouldn't be impacted then (just wanted to make sure). The dependencies are packaged in the binary.

How about plugins? How do you add them of not through npm or yarn?

**Comment by mnapoli** [comment]
@mungojam got it! So it would improve installation speed for `serverless` users, as well as possibly for CI/CD (installing `serverless` in CI).

Regarding plugins, yeah these would always be installed via NPM, that's correct.

**Comment by severi** [comment]
i think this still is a really valid feature request. For example in our use case we have a monorepo with multiple frontends and serverless apis that we wish to migrate Yarn and PnP. It would be a shame if this would be prevented by the usage of serverless (trying out some of the workarounds but serverless-bundle is causing some issues at this moment)

**Comment by severi** [comment]
> A simple workaround for anyone hoping and praying for Yarn PnP support to find it's way in one day... You can use a local serverless plugin to load the real plugin you want, which will work with Yarn PnP. _(Note: This worked for me in Serverless v2.66)_
> 
> in `serverless.yml` add a local plugin (starts with `./`)
> 
> ```yaml
> plugins:
>   - ./serverless-plugins/serverless-s3-sync
> ```
> 
> in `./serverless-plugins/serverless-s3-sync.js` just load the real desired plugin from (Yarn PnP) and return it.
> 
> ```js
> module.exports = require('serverless-s3-sync');
> ```

haven't gotten this approach to work. Wondering if it's caused by the fact that we're using yarn workspaces and the serverless api is not in the root folder of the project together with `.yarn/` but in a subfolder.

I keep on getting an error message like `Error: Cannot find module './serverless-plugins/serverless-sentry'` eventhough the file exists (same issue occured with the approach mentioned by @nkalinov )

Are you running serverless using pnpify ?

**Comment by severi** [comment]
Just an update to give some more motivation for native pnp support. The current way of running serverless with `yarn pnpify` causes issues with node having too many files open if doing anything else with node at the same time (for example running 2 create-react-app based frontends while trying to deploy the api with serverless)

```
node:events:368
      throw er; // Unhandled 'error' event
      ^

Error: EMFILE: too many open files, watch
    at FSEvent.FSWatcher._handle.onchange (node:internal/fs/watchers:204:21)
Emitted 'error' event on FSWatcher instance at:
    at FSEvent.FSWatcher._handle.onchange (node:internal/fs/watchers:210:12) {
  errno: -24,
  syscall: 'watch',
  code: 'EMFILE',
  filename: null
}
```

In case someone else bumps into this issue with OSX a temporary solution that enables at least some more parallel work can be found here https://annacoding.com/article/3ANSmivu2UrkP2AcrkRmtz/The-solution-to-solve-update-error:-EMFILE:-too-many-open-files,-uv_cwd--in-Mac-OS

**Comment by MrChrisRodriguez** [comment]
@mnapoli:

### Why care?
With PnP, Yarn cuts out the linking step (extracting files into node_modules) which has several significant benefits:
- **Faster**: in our monorepo, PnP time-to-install is an order of magnitude faster than Yarn (node_modules) or NPM. And on slower dev machines or IO constrained environments (which we also encounter in virtualized environments), it's an additional order of magnitude improvement over that. 
- **Smaller**: you only need one copy of the dependencies -- the archived version. In our case, it reduced the footprint of our monorepo from 6.5GIB to 2GiB. And with improvements in compression (i.e. zstd), that could get even smaller.
- **Simpler**: Since you only have one file per dependency, you can have a shared global cache multiple systems are using, and/or commit your dependencies directly into your repo.
- **Predictable**: PnP requires that packages explicitly define their dependencies. That's great because it reduces the occurrence of misaligned sub-dependencies causing unexpected errors (like what's happening with Strapi [here](https://github.com/strapi/strapi/issues/13158#issuecomment-1111825777)). It has workarounds for when packages are missing those explicit dependencies, too. 

In summary, PnP leads to a faster and more _dependable_ (get it?) experience.

### So what's being suggested? 
Make Serverless PnP-compatible.

### Who does this help:
- Teams using Yarn that want to yield the benefits from enabling PnP, but can't because it breaks Serverless.
- Teams using Yarn PnP and Serverless with workarounds, but who are afraid that every time there's a new Serverless release that it will break because Serverless lacks first-class support for PnP.
- Everyone using Serverless, regardless of their package manager, will benefit from explicitly defined dependencies.

Ultimately, this request isn't about changing the Serverless experience itself; it's about updating Serverless to unlock Yarn PnP's substantive benefits for the millions of developers that use both tools together.

**Comment by mnapoli** [comment]
Hey everyone, a quick follow-up.

First, the PRs mentioned earlier in the thread were actually implemented in the v3 release. So it might be worth trying again.

Second, we are open to adding support for Yarn PnP, **the next step would be listing what needs to be done** (because we don't know what's left to do). Then we can decide if the maintenance effort is something we can support.

**Comment by mungojam** [comment]
It actually works perfectly well for me now, using it in multiple serverless projects with no workarounds

**Comment by MrChrisRodriguez** [comment]
@mnapoli thanks for the follow-up. It's working for us, too.

At this stage, my only request would be that y'all add a "works-with-PnP" test to the suite to make sure that support is ongoing.

If other folks don't add anything here in the next bit, you can probably mark this issue as completed. Thanks again!

**Comment by severi** [comment]
Seems like the plugins are indeed resolved correctly :) I'm still facing issues myself but I assume it's related to what @esetnik mentioned in his comment regarding serverless-webpack as for some reason the dependencies cannot be resolved when the functions are built.

> I have other plugins getting loaded, but for a currently unknown reason `serverless-webpack` isn't working.

Assuming it's the same problem - did you find a solution to this?

**Comment by gruckion** [comment]
> It actually works perfectly well for me now, using it in multiple serverless projects with no workarounds

Did you get this working with webpack at all or maybe even serverless-webpack-plugin? We're using Typescript and yarn workspaces. Hoping to be able to share dependencies as well as PnP

**Comment by mungojam** [comment]
> > It actually works perfectly well for me now, using it in multiple serverless projects with no workarounds
> 
> Did you get this working with webpack at all or maybe even serverless-webpack-plugin? We're using Typescript and yarn workspaces. Hoping to be able to share dependencies as well as PnP

actually, you're skepticism is correct. We've got it working when we are using serverless to deploy lambdas in other languages (python and C#), but our node one is not currently working as it isn't bundling the dependencies with it. I'm trying pnpm mode, but that currently runs out of memory during `serverless package` call

**Comment by Ruderud** [comment]
For someone who may be struggling to apply Yarn's Plug 'n' Play (PnP) with Serverless, I'm leaving this note here. (This message is written as of September 6, 2023.)

In conclusion, I successfully resolved the issue of using Yarn's PnP with esbuild bundling in Serverless.

```json
// package.json
"scripts": {
  "build": "esbuild src/index.ts --bundle --platform=node --tsconfig=./tsconfig.json --outfile=dist/index.js",
  "deploy": "yarn build && sls deploy"
}
```

```yaml
// serverless.yml
// I've omitted parts outside the function application for brevity.

functions:
  hello:
    handler: dist/index.hello
```

```bash
// for excute
$ yarn deploy
```

By following these steps, you can deploy to AWS Lambda with Yarn's PnP applied.

To explain further:

1. esbuild Flags:

- src/index.ts is the initial handler entry point.
- `--bundle` indicates that bundling should be performed.
- `--platform=node` specifies that it should run in a Node.js environment (essential for AWS Lambda).
- `--tsconfig=./tsconfig.json` implies the usage of tsconfig.json (optional if you have one).
- `--outfile=dist/index.js` specifies the output location of the bundled file as dist/index.js.

2. serverless.yml Functions Option:
dist/index.hello refers to the hello function in the bundled index.js produced by esbuild.

I hope this helps someone out there.
