### ISSUE TITLE
AWS Parameter store variables ssm

### ISSUE THREAD

**Issue by fcastellanos** [serverless/serverless#5675]
# This is a Bug Report

## Description

* What went wrong?
Using variables in Parameter store `ssm:MY_VARIABLE` not working in `1.36.0` breaking the deployment.

* What did you expect should have happened?
To be able to fetch the `ssm` parameter and set it to my sls env variable.

* What was the config you used?
```
service: my-sls-service

provider:
  name: aws
  runtime: python3.6
...
  environment:
    MY_VARIABLE: ${ssm:MY_VARIABLE}
...
```
```
{
  "name": "my-sls-service",
  "description": "",
  "version": "0.1.0",
  "dependencies": {
    "serverless": "^1.32.0"
  },
  "devDependencies": {
    "serverless-python-requirements": "^4.2.5"
  }
}
```

* What stacktrace or error message from your provider did you see?
```

++ node_modules/.bin/serverless deploy --verbose
--
  |  
  | Serverless Information ----------------------------------
  |  
  | ##########################################################################################
  | # 2501: 16 of 17 promises have settled
  | # 2501: 1 unsettled promises:
  | # 2501:   ssm:MY_VARIABLE waited on by: ${ssm:MY_VARIABLE}
  | # This can result from latent connections but may represent a cyclic variable dependency
  | ##########################################################################################
```
This error message goes on forever retrying and retrying.

Similar or dependent issues:
* Maybe #5669 ?

## Additional Data

* ***Serverless Framework Version you're using***: 1.36.0
* ***Operating System***: node:8.9.1-alpine

**Comment by fcastellanos** [comment]
Seems like one of the very first things when running `sls deploy` is to go and fetch the Parameter Store variables in AWS to it can create the CF template but for some reason is hanging there trying to fetch it retrying for ever causing the deployment to hang.

**Comment by lavie** [comment]
Also happens to me in `1.36.0-1`

Does not happen with `1.35.1`

Problem seems to happen only when an "assume role" AWS CLI profile is used.

**Comment by michaelwittwer** [comment]
Experiencing the same behavior as @lavie describes, also authenticating with "assume role" using a profile

**Comment by exoego** [comment]
Fixed in https://github.com/serverless/serverless/pull/5739

**Comment by dschep** [comment]
@fcastellanos @michaelwittwer  @lavie could you confirm that #5739 did indeed fix the issue for you? `npm i -g serverless/serverless` to upgrade to the master branch of sls that has the fix merged.

**Comment by fcastellanos** [comment]
@dschep No, it did not fix the issue, same error.

This is part of my package.json, I'm depoying with Buildkite 
```
"dependencies": {
    "serverless": "^1.36.3"
  },
```

**Comment by lavie** [comment]
> @fcastellanos @michaelwittwer @lavie could you confirm that #5739 did indeed fix the issue for you? `npm i -g serverless/serverless` to upgrade to the master branch of sls that has the fix merged.

Confirm, fixed in `1.36.3`

**Comment by exoego** [comment]
@fcastellanos 
Current master branch with the fix is NOT published to npm yet.
I think you need to run `npm i -g serverless/serverles` and deploy locally to confirm.

Note) What `npm i -g serverless/serverles` mean is installing serverless from default (master) branch of severless/serverless repository.

**Comment by fcastellanos** [comment]
Yes, it worked, this is basically what I did

```
$ npm i -g serverless/serverless
.....
$ sls --version
1.36.3
$ sls deploy --aws-profile [profile] --stage [stage]
...
```
It deployed successfully to AWS.

Thanks so much!

**Comment by WeirdMachine** [comment]
Still experience this issue. Did the same steps as above, expect setting stage parameter

Npm: 6.5.0
Node: v11.9.0
Ubuntu 18.10

**Comment by dschep** [comment]
@WeirdMachine could you share the sls yaml that's causing an issue for you?

@abhivijay89 did you install with `npm i -g serverless/serverless` to install from github instead of npm?

**Comment by abhivijay89** [comment]
@dschep Yes
`➤ $ npm i -g serverless/serverless
/usr/local/bin/serverless -> /usr/local/lib/node_modules/serverless/bin/serverless
/usr/local/bin/slss -> /usr/local/lib/node_modules/serverless/bin/serverless
/usr/local/bin/sls -> /usr/local/lib/node_modules/serverless/bin/serverless

> serverless@1.36.3 postinstall /usr/local/lib/node_modules/serverless
> node ./scripts/postinstall.js

+ serverless@1.36.3
updated 1 package in 99.045s

➤ $ sls --version
1.36.3

➤ $ sls package --region us-west-2

 Serverless Information ----------------------------------

  # 2501: 2 of 3 promises have settled
  # 2501: 1 unsettled promises:
  # 2501:   ssm:emrApiKey waited on by: ${ssm:emrApiKey}
  # This can result from latent connections but may represent a cyclic variable dependency
`

`➤ $ cat serverless.yml | grep -B 2 ssm
  apiKeys:
    - name: emr_api_key
      value: ${ssm:emrApiKey}`

**Comment by abhivijay89** [comment]
@dschep My bad! Looks like there was an issue with my aws profile not getting picked up correctly and indirectly causing this issue. It's working now. Thanks much!

**Comment by fcastellanos** [comment]
Hi all, can we close this issue then?

**Comment by dschep** [comment]
Yup!

**Comment by jamesdixon** [comment]
@abhivijay89 can you tell me what you did regarding your profile? everything was working for me and then installed the latest version of serverless and now i get nothing but these messages. totally regretting upgrading...smh

**Comment by itrathnasekara** [comment]
Hi, I am getting a similar issue when accessing ssm parameters with serverless version 1.47.0

Error :

Serverless Information ----------------------------------
#####################################################################
2502: 13 of 14 promises have settled
2502: 1 unsettled promises:
25 02: ssm:/vpc/devlocal/subnetId waited on by: undefined
This can result from latent connections but may represent a cyclic variable dependency
####################################################################

Should I report this as a separate issue ? I can see a similar issue here as well https://github.com/serverless/serverless/issues/5972

**Comment by phmasek** [comment]
The issue still remains... As @itrathnasekara you can find the smilar issue at #5972.
