### ISSUE TITLE
Error in calling named profile from aws credentials

### ISSUE THREAD

**Issue by pritamneog29** [serverless/serverless#5755]
The latest version 1.36.3 has got deployment issue when deployed with a named profile having iam role asigned. It calls the default profile eveytime.

**Comment by Kjir** [comment]
We have issues as well with named profiles, serverless will exit without errors in a matter of a few seconds. Downgrading to 1.35.1 seems to be fixing it.

**Comment by paul** [comment]
Adding my report to this as well. I have two profiles, one specified in by .profle (`AWS_PROFILE=staging`, and a production one (`AWS_PROFILE=production`) that uses `AssumeRole` with the same credentials.

Deploying to staging works fine:

```
$ sls deploy                           
Serverless: Building native Rust cloudwatch-logexporter func...
    Finished release [optimized] target(s) in 0.13s                                                                                                                                                                   
  adding: bootstrap (deflated 61%)
Serverless: Packaging service...
Serverless: Uploading CloudFormation file to S3...
Serverless: Uploading artifacts...
Serverless: Uploading service .zip file to S3 (1.16 MB)...
Serverless: Validating template...
Serverless: Updating Stack...
Serverless: Checking Stack update progress...
.........
Serverless: Stack update finished...
Service Information
service: cloudwatch-logexporter
stage: dev
region: us-east-1
stack: cloudwatch-logexporter-dev
api keys:
  None
endpoints:
  None
functions:
  logexport: cloudwatch-logexporter-dev-logexport
layers:
  None
Serverless: Removing old service artifacts from S3...
```

Trying to switch to the other profile just bails, no output, even with `--verbose`.

```
$ sls deploy --aws-profile production --verbose --force
Serverless: Building native Rust cloudwatch-logexporter func...
    Finished release [optimized] target(s) in 0.13s                                                                                                                                                                   
  adding: bootstrap (deflated 61%)
Serverless: Packaging service...

$
```

Other attempts to set the profile (`AWS_PROFILE=production sls deploy`, `export AWS_PROFILE=production && sls deploy`) fail in the same way.

serverless 1.35.1 works as expected.

**Comment by derricksong** [comment]
I have the same issue, can't deploy using a profile that uses an AssumeRole

`sls deploy --profile profile1`

works fine, but

`sls deploy --profile profile2` 

Gives a `ServerlessError: AWS provider credentials not found. Learn how to set up AWS provider credentials in our docs here: <http://bit.ly/aws-creds-setup>.` error message.

In ~/.aws/credentials it looks like:

[profile1]
aws_access_key_id = foo
aws_access_key_secret = bar

and ~/.aws/config it looks like:

[profile profile2]
role_arn = arn:aws:iam::stuff
source_profile = profile1

I've also tried moving profile2's configs to `~/.aws/credentials` but overall I've been reading documentation and trying things from googling for a few hours without success so far.

**Comment by thomasmichaelwallace** [comment]
I think that's a subtly different issue. In this issue the provider configurations are found, but SLS halts.

@derricksong - have you tried setting the environment variable `AWS_SDK_LOAD_CONFIG=1`?

**Comment by derricksong** [comment]
> I think that's a subtly different issue. In this issue the provider configurations are found, but SLS halts.
> 
> @derricksong - have you tried setting the environment variable `AWS_SDK_LOAD_CONFIG=1`?

You know, I was completely wrong.  It was merely a hard to spot role ARN typo, cross-account roles work fine exactly as described above.  Sorry.

**Comment by thomasmichaelwallace** [comment]
I think this is fixed by #5739 (1.37.0)

**Comment by dschep** [comment]
Agreed @thomasmichaelwallace, could other folks confirm this bug still exists?
