### ISSUE TITLE
Missing required key 'restApiId' in params in 1.42.0

### ISSUE THREAD

**Issue by aaronjensen** [serverless/serverless#6100]
# This is a Bug Report

## Description

* What went wrong?

After upgrading to 1.42.0, I can no longer deploy. I get:

```
  Serverless Error ---------------------------------------
 
  Missing required key 'restApiId' in params
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com
 
  Your Environment Information ---------------------------
     OS:                     linux
     Node Version:           8.11.4
     Serverless Version:     1.42.0
```

* What did you expect should have happened?

It should have worked like the previous version did.

* What was the config you used?

<details>
<summary>`serverless.yml`</summary>

```
service: my-app-consent

cors: &cors
  origins:
    - '${file(../../packages/dev/config/env.js):env.POWER_UP_URL}'
  headers:
    - Content-Type
    - X-Amz-Date
    - Authorization
    - X-Api-Key
    - X-Amz-Security-Token
    - X-Amz-User-Agent
    - SPOOF
  allowCredentials: false

provider:
  name: aws
  runtime: nodejs8.10
  memorySize: 256
  logRetentionInDays: 14
  apiGateway:
    restApiId: '${file(../../packages/dev/config/env.js):env.REST_API_ID}'
    restApiRootResourceId: '${file(../../packages/dev/config/env.js):env.REST_API_ROOT_RESOURCE_ID}'
  deploymentBucket:
    serverSideEncryption: AES256
  environment:
    AWS_ACCOUNT_ID: '${file(../../packages/dev/config/env.js):env.AWS_ACCOUNT_ID}'
    ENV_NAMESPACE: ${self:custom.namespace}
  iamRoleStatements:
    - Effect: 'Allow'
      Resource: 'arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:custom.namespace}-userConsents'
      Action:
        - dynamodb:PutItem

plugins:
  - serverless-sentry
  - serverless-webpack
  - serverless-offline

package:
  individually: true

custom:
  stage: ${opt:stage, self:provider.stage}
  namespace: my-app-${self:custom.stage}
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: false
    packager: 'yarn'
  serverless-offline:
    httpsProtocol: '../../config/localhost'
    port: 8003
  sentry:
    dsn: ${file(../../packages/dev/config/env.js):env.SENTRY_FUNCTIONS_DSN}
    captureTimeoutWarnings: false

functions:
  record-consent:
    handler: src/handlers/recordConsent.lambda
    events:
      - http:
          path: /consent
          method: post
          cors: *cors
```

</details>

* What stacktrace or error message from your provider did you see?

See above

Similar or dependent issues:

None

## Additional Data

* ***Serverless Framework Version you're using***: 1.42.0
* ***Operating System***: any
* ***Stack Trace***: none
* ***Provider Error messages***: see above

**Comment by aaronjensen** [comment]
Additional debug info:

```
Serverless: [AWS sts 200 0.366s 0 retries] getCallerIdentity({})
Serverless: [AWS apigateway 200 0.409s 0 retries] getRestApis({ limit: 500 })
Serverless: [AWS apigateway undefined 0.001s 0 retries] getStage({ restApiId: null, stageName: 'staging' })
Serverless: [AWS apigateway undefined 0.001s 0 retries] getDeployments({ restApiId: null, limit: 500 })

  Serverless Error ---------------------------------------

  Missing required key 'restApiId' in params

  Stack Trace --------------------------------------------

ServerlessError: Missing required key 'restApiId' in params
    at promise.catch.err (/Users/aaronjensen/Source/hello-epics/node_modules/serverless/lib/plugins/aws/provider/awsProvider.js:302:11)
    at <anonymous>
    at runMicrotasksCallback (internal/process/next_tick.js:121:5)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickDomainCallback (internal/process/next_tick.js:218:9)

  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com

  Your Environment Information ---------------------------
     OS:                     darwin
     Node Version:           8.11.4
     Serverless Version:     1.42.0
```

**Comment by adamclerk** [comment]
I'm seeing this error as of this morning as well.

**Comment by sharstream** [comment]
Same error  from here, I tried to deploy the serverless yml but it couldn't deploy successfully because  is missing required key 'restApiId' in params.

**Comment by ceefour** [comment]
👍 I'm getting this too with v1.42.1. I'll try downgrading to v1.41.1.

**Comment by mrusme** [comment]
Same for me:

```
  Serverless Error --------------------------------------- 
  
  Missing required key 'restApiId' in params 
  
  Get Support -------------------------------------------- 
     Docs:          docs.serverless.com 
     Bugs:          github.com/serverless/serverless/issues 
     Issues:        forum.serverless.com 
  
  Your Environment Information --------------------------- 
     OS:                     linux 
     Node Version:           8.11.0 
     Serverless Version:     1.42.1 
```

**Comment by medikoo** [comment]
Fixed and published with v1.42.2

**Comment by fabianib102** [comment]
> 👍 I'm getting this too after upgrading from v1.36.1 to v1.42.1. I'll try downgrading to v1.41.1.
> 
> After downgrading to v1.41.1 I get another problem: (Update: turned out to be due to `serverless-domain-manager` v3.2.1, after downgrading to v2.6.13 I can now deploy successfully using serverless v1.41.x or earlier, but not with v1.42.1)
> 
> ```
>   Error: Failed to find CloudFormation resources for x.xyz.com
> ```
> 
> argh, bad time to upgrade :(

I fix this problem, changing version with  v1.41.1

**Comment by alaasdk** [comment]
I rolled back to version v1.41.1 and everything worked just fine.

`npm i -g serverless@v1.41.1`

**Comment by bpg** [comment]
Just tried to deploy with 1.42.2:
```
Serverless Error ---------------------------------------
 
  Missing required key 'restApiId' in params
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com
 
  Your Environment Information ---------------------------
     OS:                     linux
     Node Version:           10.15.3
     Serverless Version:     1.42.2
```

**Comment by medikoo** [comment]
@bpg Thanks for report. Can you run it with `-d` and show us full error stack trace, also can you show us `serverless.yml` (at least related details)?

**Comment by bpg** [comment]
Now I can't reproduce it, simple re-deploy of existing stack helped. But this time I also removed `node_modules` folder, so that might be a caching issue.

**Comment by medikoo** [comment]
> Now I can't reproduce it, simple re-deploy of existing stack helped. But this time I also removed node_modules folder, so that might be a caching issue.

Interesting, especially that in env information v1.42.2 was listed.

**Comment by bpg** [comment]
I have plugins:
```
plugins:
  - serverless-plugin-aws-alerts
  - serverless-step-functions
  - serverless-pseudo-parameters
  - serverless-domain-manager
```
custom domain config
```
  customDomain:
    domainName: ${self:custom.prefix}.example.com
    basePath: api
    certificateName: '*.example.com'
    createRoute53Record: true
    endpointType: 'regional'
```
provider settings:
```
provider:
  name: aws
  runtime: java8
  region: us-east-1
  memorySize: 1024
  timeout: 120
  versionFunctions: false
  cfLogs: true
  logRetentionInDays: 60
  apiKeys:
    - ${self:custom.prefix}
```
I have multiple lambda handlers configured with http event like:
```
    events:
      - http:
          path: /some/thing
          method: get
          cors: true
          authorizer: aws_iam
```
and finally a custom resource in `resources`:
```
  Resources:
    ApiGatewayRestApi:
      Type: AWS::ApiGateway::RestApi
      Properties:
        Name: ${self:custom.prefix}
```

**Comment by guikaercher** [comment]
We were running into another problem here and we decided to delete stack and redeploy, but after that we have this error too.
Our deploy runs through circle CI and I did already changed the version to the 1.42.2 but the problem still happening.

`  Serverless Error ---------------------------------------
 
  Missing required key 'restApiId' in params
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com
 
  Your Environment Information ---------------------------
     OS:                     linux
     Node Version:           8.15.1
     Serverless Version:     1.42.2`

**Comment by medikoo** [comment]
Thanks @guikaercher  are you by chance also define `AWS::ApiGateway::RestApi` as custom resource?

Can you sure relevant bits of `.serverless.yml` with us?

**Comment by guikaercher** [comment]
Yes, I replaced every sensitive info with "hidden"

# serverless.yml

service: hidden-hidden-hidden

plugins:
  - serverless-offline
  - serverless-webpack
  - serverless-dotenv-plugin

custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true
  prd:
    vpc:
      securityGroupIds:
        - sg-hidden
      subnetIds:
        - subnet-hidden
        - subnet-hidden
  dev:
    vpc:
      securityGroupIds:
        - sg-hidden
      subnetIds:
        - subnet-hidden
        - subnet-hidden

package:
  individually: true
  include:
    - src/receiver.ts # hidden hidden
    - src/processor.ts # hidden hidden
    - src/sender.ts # hidden Push Service

provider:
  name: aws
  runtime: nodejs8.10
  stage: ${env:STAGE}
  region: ${env:AWS_SERVER_REGION}
  environment:
    STAGE: ${self:provider.stage}
    SSM_PARAMETER_ARN: ${env:SSM_PARAMETER_ARN}
    PUSH_SERVICE_ROLE: ${env:PUSH_SERVICE_ROLE}
  deploymentBucket:
    name: ${env:DEPLOYMENT_BUCKET}


functions:
  # Hidden Service
  receiver:
    handler: src/receiver.handler
    role: ${env:PUSH_SERVICE_ROLE}
    environment:
      AWS_SERVER_REGION: ${env:AWS_SERVER_REGION}
      HIDDEN_QUEUE_URL: !Ref hiddenQueue # Gets SQS Queue URL
      LOGGING_QUEUE_URL: ${env:LOGGING_QUEUE_URL}
    events:
      - http: POST push-notifications
  # HIDDEN Service
  processor:
    handler: src/processor.handler
    reservedConcurrency: 50
    vpc: ${self:custom.${self:provider.stage}.vpc}
    role: ${env:PUSH_SERVICE_ROLE}
    environment:
      AWS_SERVER_REGION: ${env:AWS_SERVER_REGION}
      HIDDEN_QUEUE_URL: !Ref hiddenQueue # Gets SQS Queue URL
      PUSHES_QUEUE_URL: !Ref PushesQueue # Gets SQS Queue URL
      LOGGING_QUEUE_URL: ${env:LOGGING_QUEUE_URL}
      MONGO_PREFIX: ${env:MONGO_PREFIX}
      MONGO_DB_NAME: ${env:MONGO_DB_NAME}
      MONGO_DB_PARAMETER: ${env:MONGO_DB_PARAMETER}
    events:
      - sqs:
          arn:
            Fn::GetAtt:
              - hiddenQueue
              - Arn
          batchSize: 10
    enabled: true
  # hidden Push Service
  sender:
    handler: src/sender.handler
    role: ${env:PUSH_SERVICE_ROLE}
    environment:
      AWS_SERVER_REGION: ${env:AWS_SERVER_REGION}
      PUSHES_QUEUE_URL: !Ref PushesQueue # Gets SQS Queue URL
      LOGGING_QUEUE_URL: ${env:LOGGING_QUEUE_URL}
    events:
      - sqs:
          arn:
            Fn::GetAtt:
              - PushesQueue
              - Arn
    enabled: true
# Resources
resources:
  Resources:
    # Hidden Service
    hiddenQueue:
      Type: "AWS::SQS::Queue"
      Properties:
        QueueName: "hiddenQueue"
    # hidden Push Service
    PushesQueue:
      Type: "AWS::SQS::Queue"
      Properties:
        QueueName: "PushesQueue"

**Comment by medikoo** [comment]
Great thanks @guikaercher, we're looking into it

**Comment by guikaercher** [comment]
> Thanks @guikaercher are you by chance also define `AWS::ApiGateway::RestApi` as custom resource?
> 
> Can you sure relevant bits of `.serverless.yml` with us?

About API GW I'm not using inside Resource itself, but I'm referencing it at receiver lambda trigger event
```
events:
      - http: POST push-notifications
```

**Comment by bpg** [comment]
more fun stuff -- exactly same code, deployment from my Mac works, but deployment from CircleCI gives me the same error as before. I can spot only difference in Node version: local: v11.14.0, CirceCI: 10.15.3.

**Comment by guikaercher** [comment]
My circle builds with this docker image: `node:8.15-jessie-slim`, in my computer I'm using node `v8.16.0`

**Comment by aidinkhosrowshahi** [comment]
I am getting this error for new version: 

this is my config and it used to work 

apiGateway:
    restApiId:
      'Fn::ImportValue': "RestApiId-${self:custom.stage}"
    restApiRootResourceId:
      'Fn::ImportValue': "v0-${self:custom.stage}"



Serverless Error --------------------------------------- 
  
  Expected params.restApiId to be a string 
  
  Get Support -------------------------------------------- 
     Docs:          docs.serverless.com 
     Bugs:          github.com/serverless/serverless/issues 
     Issues:        forum.serverless.com 
  
  Your Environment Information --------------------------- 
     OS:                     linux 
     Node Version:           10.14.1 
     Serverless Version:     1.42.2

**Comment by viktorlarsson** [comment]
Same error occuring here on BitBucket pipelines on v1.42.2 Using node:10.6.0.

**Comment by bpg** [comment]
Here is the log from my failing deployment:
```
> Task :xxxx:slsInstallPlugins
Serverless: Creating an empty package.json file in your service directory
Serverless: Installing plugin "serverless-domain-manager@latest" (this might take a few seconds...)
Serverless: Successfully installed "serverless-domain-manager@latest"
Serverless: Installing plugin "serverless-plugin-aws-XXXXs@latest" (this might take a few seconds...)
Serverless: Successfully installed "serverless-plugin-aws-XXXXs@latest"

> Task :xxxx:deploy
Serverless: Custom domain xxx.example.com already exists.
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command create
Serverless: Load command install
Serverless: Load command package
Serverless: Load command deploy
Serverless: Load command deploy:function
Serverless: Load command deploy:list
Serverless: Load command deploy:list:functions
Serverless: Load command invoke
Serverless: Load command invoke:local
Serverless: Load command info
Serverless: Load command logs
Serverless: Load command metrics
Serverless: Load command print
Serverless: Load command remove
Serverless: Load command rollback
Serverless: Load command rollback:function
Serverless: Load command slstats
Serverless: Load command plugin
Serverless: Load command plugin
Serverless: Load command plugin:install
Serverless: Load command plugin
Serverless: Load command plugin:uninstall
Serverless: Load command plugin
Serverless: Load command plugin:list
Serverless: Load command plugin
Serverless: Load command plugin:search
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command rollback
Serverless: Load command rollback:function
Serverless: Load command create_domain
Serverless: Load command delete_domain
Serverless: Invoke deploy
Serverless: Invoke package
Serverless: Invoke aws:common:validate
Serverless: Invoke aws:common:cleanupTempDir
Serverless: Packaging service...
Serverless: Warning: Not deploying XXXXs on stage dev
Serverless: Invoke aws:package:finalize
Serverless: Invoke aws:common:moveArtifactsToPackage
Serverless: Invoke aws:common:validate
Serverless: Invoke aws:deploy:deploy
Serverless: [AWS cloudformation 200 0.089s 0 retries] describeStacks({ StackName: 'xxxx' })
Serverless: [AWS cloudformation 200 0.066s 0 retries] describeStackResource({ StackName: 'xxxx',
  LogicalResourceId: 'ServerlessDeploymentBucket' })
Serverless: [AWS s3 200 0.117s 0 retries] listObjectsV2({ Bucket: 'xxxx-serverlessdeploymentbucket-1af9l1iw36h27',
  Prefix: 'serverless/xxxx/dev' })
Serverless: [AWS s3 200 0.036s 0 retries] headObject({ Bucket: 'xxxx-serverlessdeploymentbucket-1af9l1iw36h27',
  Key:
   'serverless/xxxx/dev/1557515258598-2019-05-10T19:07:38.598Z/xxxx-1.0.15-SNAPSHOT.zip' })
Serverless: [AWS s3 200 0.049s 0 retries] headObject({ Bucket: 'xxxx-serverlessdeploymentbucket-1af9l1iw36h27',
  Key:
   'serverless/xxxx/dev/1557515258598-2019-05-10T19:07:38.598Z/compiled-cloudformation-template.json' })
Serverless: [AWS sts 200 0.02s 0 retries] getCallerIdentity({})
Serverless: Uploading CloudFormation file to S3...
Serverless: [AWS s3 200 0.127s 0 retries] putObject({ Body:
   <Buffer 7b 22 41 57 53 54 65 6d 70 6c 61 74 65 46 6f 72 6d 61 74 56 65 72 73 69 6f 6e 22 3a 22 32 30 31 30 2d 30 39 2d 30 39 22 2c 22 44 65 73 63 72 69 70 74 ... >,
  Bucket: 'xxxx-serverlessdeploymentbucket-1af9l1iw36h27',
  Key:
   'serverless/xxxx/dev/1557516402705-2019-05-10T19:26:42.705Z/compiled-cloudformation-template.json',
  ContentType: 'application/json',
  Metadata:
   { filesha256: 'CHEt5iaWFnczcsYw4C4kXf/E007Fr5acAtmHv0CwcbY=' } })
Serverless: Uploading artifacts...
Serverless: Uploading service xxxx-1.0.15-SNAPSHOT.zip file to S3 (31.54 MB)...
Serverless: [AWS s3 200 0.074s 0 retries] createMultipartUpload({ Bucket: 'xxxx-serverlessdeploymentbucket-1af9l1iw36h27',
  Key:
   'serverless/xxxx/dev/1557516402705-2019-05-10T19:26:42.705Z/xxxx-1.0.15-SNAPSHOT.zip',
  ContentType: 'application/zip',
  Metadata:
   { filesha256: 'PCNfInh1ejlTCKVxjlyUSS7zV6CiSHexqjCKaum7UVs=' } })
Serverless: [AWS s3 200 0.227s 0 retries] uploadPart({ Body:
   <Buffer b3 70 00 f3 c2 c4 cb 92 31 f0 aa ec 04 c7 8f 53 52 5a 4b b0 14 87 dc f6 e2 9f d3 43 95 df ba 1e 4f 70 f2 fb bc f2 ea 1e 8a a4 7d 22 5a c6 55 15 36 cd ... >,
  ContentLength: 5242880,
  PartNumber: 2,
  Bucket: 'xxxx-serverlessdeploymentbucket-1af9l1iw36h27',
  Key:
   'serverless/xxxx/dev/1557516402705-2019-05-10T19:26:42.705Z/xxxx-1.0.15-SNAPSHOT.zip',
  UploadId:
   'Pzh3UWKLTEQuKEyM3J5ygtjMjcww11_XSmnVoHDlrOijhnn8p5d45IicsuBrmivQf8NKHaYanH1MX7z8CyFInvKVVltd9CDWDH71wBdTFpJ62VVKXat598H7__dGMvUH' })
Serverless: [AWS s3 200 0.242s 0 retries] uploadPart({ Body:
   <Buffer e6 b5 2e aa 36 c6 d0 12 1b 63 42 7b c4 6f 2f d4 1f 60 39 3c 3e b3 82 9f b4 5f 53 63 42 27 b0 7e 1f 72 20 6e e0 35 a9 90 68 40 c4 07 c2 2b e1 1d f5 91 ... >,
  ContentLength: 5242880,
  PartNumber: 3,
  Bucket: 'xxxx-serverlessdeploymentbucket-1af9l1iw36h27',
  Key:
   'serverless/xxxx/dev/1557516402705-2019-05-10T19:26:42.705Z/xxxx-1.0.15-SNAPSHOT.zip',
  UploadId:
   'Pzh3UWKLTEQuKEyM3J5ygtjMjcww11_XSmnVoHDlrOijhnn8p5d45IicsuBrmivQf8NKHaYanH1MX7z8CyFInvKVVltd9CDWDH71wBdTFpJ62VVKXat598H7__dGMvUH' })
Serverless: [AWS s3 200 0.338s 0 retries] uploadPart({ Body:
   <Buffer 50 4b 03 04 0a 00 00 08 08 00 03 9b aa 4e 00 00 00 00 02 00 00 00 00 00 00 00 04 00 00 00 63 6f 6d 2f 03 00 50 4b 03 04 0a 00 00 08 08 00 03 9b aa 4e ... >,
  ContentLength: 5242880,
  PartNumber: 1,
  Bucket: 'xxxx-serverlessdeploymentbucket-1af9l1iw36h27',
  Key:
   'serverless/xxxx/dev/1557516402705-2019-05-10T19:26:42.705Z/xxxx-1.0.15-SNAPSHOT.zip',
  UploadId:
   'Pzh3UWKLTEQuKEyM3J5ygtjMjcww11_XSmnVoHDlrOijhnn8p5d45IicsuBrmivQf8NKHaYanH1MX7z8CyFInvKVVltd9CDWDH71wBdTFpJ62VVKXat598H7__dGMvUH' })
Serverless: [AWS s3 200 0.169s 0 retries] uploadPart({ Body:
   <Buffer 75 d8 5c df 85 35 94 5e 3f d4 f4 2a 9e fc 7c 9e 74 49 26 31 4d cb 12 99 92 16 cc 71 a6 c1 e1 08 f1 d7 ff 4a 91 1f d1 1f 2e 2a 49 fe 92 ea 5c fa 29 b8 ... >,
  ContentLength: 5242880,
  PartNumber: 4,
  Bucket: 'xxxx-serverlessdeploymentbucket-1af9l1iw36h27',
  Key:
   'serverless/xxxx/dev/1557516402705-2019-05-10T19:26:42.705Z/xxxx-1.0.15-SNAPSHOT.zip',
  UploadId:
   'Pzh3UWKLTEQuKEyM3J5ygtjMjcww11_XSmnVoHDlrOijhnn8p5d45IicsuBrmivQf8NKHaYanH1MX7z8CyFInvKVVltd9CDWDH71wBdTFpJ62VVKXat598H7__dGMvUH' })
Serverless: [AWS s3 200 0.181s 0 retries] uploadPart({ Body:
   <Buffer d6 24 ce 64 45 74 62 df 53 05 e6 84 4d 52 e4 fd e7 44 00 a7 8e 88 be 91 e1 66 07 8c 6c b3 6b 39 8e 08 7a 64 55 25 45 40 95 7b 94 ec 02 a8 78 54 c8 3f ... >,
  ContentLength: 5242880,
  PartNumber: 5,
  Bucket: 'xxxx-serverlessdeploymentbucket-1af9l1iw36h27',
  Key:
   'serverless/xxxx/dev/1557516402705-2019-05-10T19:26:42.705Z/xxxx-1.0.15-SNAPSHOT.zip',
  UploadId:
   'Pzh3UWKLTEQuKEyM3J5ygtjMjcww11_XSmnVoHDlrOijhnn8p5d45IicsuBrmivQf8NKHaYanH1MX7z8CyFInvKVVltd9CDWDH71wBdTFpJ62VVKXat598H7__dGMvUH' })
Serverless: [AWS s3 200 0.109s 0 retries] uploadPart({ Body:
   <Buffer 39 c4 b9 64 ca 7c ac c5 0e c4 3f e4 c5 cb 16 4f 3b c2 4b e3 71 28 52 54 83 44 53 ce a6 41 61 2d 50 4c 32 99 31 cc 14 2d 79 21 9a 49 f7 c8 63 15 c7 14 ... >,
  ContentLength: 1611493,
  PartNumber: 7,
  Bucket: 'xxxx-serverlessdeploymentbucket-1af9l1iw36h27',
  Key:
   'serverless/xxxx/dev/1557516402705-2019-05-10T19:26:42.705Z/xxxx-1.0.15-SNAPSHOT.zip',
  UploadId:
   'Pzh3UWKLTEQuKEyM3J5ygtjMjcww11_XSmnVoHDlrOijhnn8p5d45IicsuBrmivQf8NKHaYanH1MX7z8CyFInvKVVltd9CDWDH71wBdTFpJ62VVKXat598H7__dGMvUH' })
Serverless: [AWS s3 200 0.226s 0 retries] uploadPart({ Body:
   <Buffer f1 14 7e 10 89 d7 0c 24 f3 0f 83 83 b2 c1 58 26 4e 62 af 7f 52 6f 5d bc ff e1 49 da 4b 3b 65 f6 6c cd 03 72 1a cc 3d 10 c9 28 f6 49 67 3b 8a e8 24 28 ... >,
  ContentLength: 5242880,
  PartNumber: 6,
  Bucket: 'xxxx-serverlessdeploymentbucket-1af9l1iw36h27',
  Key:
   'serverless/xxxx/dev/1557516402705-2019-05-10T19:26:42.705Z/xxxx-1.0.15-SNAPSHOT.zip',
  UploadId:
   'Pzh3UWKLTEQuKEyM3J5ygtjMjcww11_XSmnVoHDlrOijhnn8p5d45IicsuBrmivQf8NKHaYanH1MX7z8CyFInvKVVltd9CDWDH71wBdTFpJ62VVKXat598H7__dGMvUH' })
Serverless: [AWS s3 200 0.123s 0 retries] completeMultipartUpload({ MultipartUpload:
   { Parts:
      [ { ETag: '"44d0e5dd99b5b2a7f0a0beb931c201dc"', PartNumber: 1 },
        { ETag: '"be7523e9000c74f419f3debcfb25b9ef"', PartNumber: 2 },
        { ETag: '"9829ee3474605def2f0e7e15b1d6ac06"', PartNumber: 3 },
        { ETag: '"5b624a2350e10b31cfb19d50971b9f15"', PartNumber: 4 },
        { ETag: '"2682ca00f2ed9ad99c35a89b6ad52d53"', PartNumber: 5 },
        { ETag: '"f07da194024a658b72a86613bad2ebdd"', PartNumber: 6 },
        { ETag: '"70d61af0824ac3658c27961a9925a12e"', PartNumber: 7 },
        [length]: 7 ] },
  Bucket: 'xxxx-serverlessdeploymentbucket-1af9l1iw36h27',
  Key:
   'serverless/xxxx/dev/1557516402705-2019-05-10T19:26:42.705Z/xxxx-1.0.15-SNAPSHOT.zip',
  UploadId:
   'Pzh3UWKLTEQuKEyM3J5ygtjMjcww11_XSmnVoHDlrOijhnn8p5d45IicsuBrmivQf8NKHaYanH1MX7z8CyFInvKVVltd9CDWDH71wBdTFpJ62VVKXat598H7__dGMvUH' })
Serverless: Validating template...
Serverless: [AWS cloudformation 200 0.146s 0 retries] validateTemplate({ TemplateURL:
   'https://s3.amazonaws.com/xxxx-serverlessdeploymentbucket-1af9l1iw36h27/serverless/xxxx/dev/1557516402705-2019-05-10T19:26:42.705Z/compiled-cloudformation-template.json' })
Serverless: Updating Stack...
Serverless: [AWS cloudformation 200 0.491s 0 retries] updateStack({ StackName: 'xxxx',
  Capabilities: [ 'CAPABILITY_IAM', 'CAPABILITY_NAMED_IAM', [length]: 2 ],
  Parameters: [ [length]: 0 ],
  TemplateURL:
   'https://s3.amazonaws.com/xxxx-serverlessdeploymentbucket-1af9l1iw36h27/serverless/xxxx/dev/1557516402705-2019-05-10T19:26:42.705Z/compiled-cloudformation-template.json',
  Tags: [ { Key: 'STAGE', Value: 'dev' }, [length]: 1 ] })
Serverless: Checking Stack update progress...
Serverless: [AWS cloudformation 200 0.097s 0 retries] describeStackEvents({ StackName:
   'arn:aws:cloudformation:us-east-1:xxxx:stack/xxxx/6f484330-f8a1-11e8-870f-500c217b1cd2' })
CloudFormation - UPDATE_IN_PROGRESS - AWS::CloudFormation::Stack - xxxx
Serverless: [AWS cloudformation 200 0.149s 0 retries] describeStackEvents({ StackName:
   'arn:aws:cloudformation:us-east-1:xxxx:stack/xxxx/6f484330-f8a1-11e8-870f-500c217b1cd2' })
CloudFormation - UPDATE_IN_PROGRESS - AWS::Lambda::Function - XXXXLambdaFunction
CloudFormation - UPDATE_IN_PROGRESS - AWS::Lambda::Function - XXXXLambdaFunction
Serverless: [AWS cloudformation 200 0.177s 0 retries] describeStackEvents({ StackName:
   'arn:aws:cloudformation:us-east-1:xxxx:stack/xxxx/6f484330-f8a1-11e8-870f-500c217b1cd2' })
CloudFormation - UPDATE_IN_PROGRESS - AWS::Lambda::Function - XXXXLambdaFunction
CloudFormation - UPDATE_IN_PROGRESS - AWS::Lambda::Function - XXXXLambdaFunction
CloudFormation - UPDATE_IN_PROGRESS - AWS::Lambda::Function - XXXXLambdaFunction
CloudFormation - UPDATE_IN_PROGRESS - AWS::Lambda::Function - XXXXLambdaFunction
CloudFormation - UPDATE_IN_PROGRESS - AWS::Lambda::Function - XXXXLambdaFunction
CloudFormation - UPDATE_IN_PROGRESS - AWS::Lambda::Function - XXXXLambdaFunction
CloudFormation - UPDATE_IN_PROGRESS - AWS::Lambda::Function - XXXXLambdaFunction
CloudFormation - UPDATE_COMPLETE - AWS::Lambda::Function - XXXXLambdaFunction
CloudFormation - UPDATE_COMPLETE - AWS::Lambda::Function - XXXXLambdaFunction
CloudFormation - UPDATE_COMPLETE - AWS::Lambda::Function - XXXXLambdaFunction
CloudFormation - UPDATE_COMPLETE - AWS::Lambda::Function - XXXXLambdaFunction
CloudFormation - UPDATE_COMPLETE - AWS::Lambda::Function - XXXXLambdaFunction
CloudFormation - UPDATE_COMPLETE - AWS::Lambda::Function - XXXXLambdaFunction
CloudFormation - UPDATE_COMPLETE - AWS::Lambda::Function - XXXXLambdaFunction
CloudFormation - UPDATE_COMPLETE - AWS::Lambda::Function - XXXXLambdaFunction
CloudFormation - UPDATE_COMPLETE - AWS::Lambda::Function - XXXXLambdaFunction
Serverless: [AWS cloudformation 200 0.124s 0 retries] describeStackEvents({ StackName:
   'arn:aws:cloudformation:us-east-1:xxxx:stack/xxxx/6f484330-f8a1-11e8-870f-500c217b1cd2' })
Serverless: [AWS cloudformation 200 0.093s 0 retries] describeStackEvents({ StackName:
   'arn:aws:cloudformation:us-east-1:xxxx:stack/xxxx/6f484330-f8a1-11e8-870f-500c217b1cd2' })
Serverless: [AWS cloudformation 200 0.107s 0 retries] describeStackEvents({ StackName:
   'arn:aws:cloudformation:us-east-1:xxxx:stack/xxxx/6f484330-f8a1-11e8-870f-500c217b1cd2' })
CloudFormation - CREATE_IN_PROGRESS - AWS::ApiGateway::Deployment - ApiGatewayDeployment1557516402244
CloudFormation - CREATE_IN_PROGRESS - AWS::ApiGateway::Deployment - ApiGatewayDeployment1557516402244
CloudFormation - CREATE_COMPLETE - AWS::ApiGateway::Deployment - ApiGatewayDeployment1557516402244
Serverless: [AWS cloudformation 200 0.094s 0 retries] describeStackEvents({ StackName:
   'arn:aws:cloudformation:us-east-1:xxxx:stack/xxxx/6f484330-f8a1-11e8-870f-500c217b1cd2' })
Serverless: [AWS cloudformation 200 0.089s 0 retries] describeStackEvents({ StackName:
   'arn:aws:cloudformation:us-east-1:xxxx:stack/xxxx/6f484330-f8a1-11e8-870f-500c217b1cd2' })
Serverless: [AWS cloudformation 200 0.202s 0 retries] describeStackEvents({ StackName:
   'arn:aws:cloudformation:us-east-1:xxxx:stack/xxxx/6f484330-f8a1-11e8-870f-500c217b1cd2' })
CloudFormation - UPDATE_COMPLETE_CLEANUP_IN_PROGRESS - AWS::CloudFormation::Stack - xxxx
CloudFormation - DELETE_IN_PROGRESS - AWS::ApiGateway::Deployment - ApiGatewayDeployment1557515258080
CloudFormation - DELETE_COMPLETE - AWS::ApiGateway::Deployment - ApiGatewayDeployment1557515258080
CloudFormation - UPDATE_COMPLETE - AWS::CloudFormation::Stack - xxxx
Serverless: Stack update finished...
Serverless: Invoke aws:info
Serverless: [AWS cloudformation 200 0.078s 0 retries] describeStacks({ StackName: 'xxxx' })
Serverless: [AWS cloudformation 200 0.208s 0 retries] listStackResources({ StackName: 'xxxx' })
Serverless: [AWS cloudformation 200 0.092s 0 retries] describeStackResources({ StackName: 'xxxx' })
Serverless: [AWS apigateway 200 0.18s 0 retries] getApiKey({ apiKey: 'zf0nzwyaka', includeValue: true })
Service Information
service: xxxx
stage: dev
region: us-east-1
stack: xxxx
resources: 63
api keys:
  xxxx: yyyy
endpoints:
  POST - https://xxxx.execute-api.us-east-1.amazonaws.com/dev/event
  POST - https://xxxx.execute-api.us-east-1.amazonaws.com/dev/XXXX
  GET - https://xxxx.execute-api.us-east-1.amazonaws.com/dev/tracking/{jobId}
  GET - https://xxxx.execute-api.us-east-1.amazonaws.com/dev/tracking
  POST - https://xxxx.execute-api.us-east-1.amazonaws.com/dev/tracking/job/{jobId}
  POST - https://xxxx.execute-api.us-east-1.amazonaws.com/dev/tracking/job
  POST - https://xxxx.execute-api.us-east-1.amazonaws.com/dev/tracking/task/{jobId}
  PUT - https://xxxx.execute-api.us-east-1.amazonaws.com/dev/tracking/job
  PUT - https://xxxx.execute-api.us-east-1.amazonaws.com/dev/tracking/task
  GET - https://xxxx.execute-api.us-east-1.amazonaws.com/dev/org/registration
  HEAD - https://xxxx.execute-api.us-east-1.amazonaws.com/dev/org/{orgId}
functions:
  XXXX: xxxx-XXXX
  XXXX: xxxx-TestXXXXHandler
  XXXX: xxxx-XXXX
  XXXX: xxxx-XXXX
  XXXX: xxxx-XXXX
  XXXX: xxxx-XXXX
  XXXX: xxxx-XXXX
  XXXX: xxxx-XXXX
  XXXX: xxxx-XXXX
layers:
  None

Stack Outputs
XXXX: xxxx
XXXX: xxxx
ServerlessDeploymentBucketName: xxxx
ApiTestXXXXEndpoint: xxxx

Serverless: [AWS sts 200 0.049s 0 retries] getCallerIdentity({})
Serverless: [AWS apigateway 200 0.06s 0 retries] getRestApis({ position: undefined, limit: 500 })
Serverless: [AWS apigateway undefined 0.001s 0 retries] getStage({ restApiId: null, stageName: 'dev' })
Serverless: [AWS apigateway undefined 0s 0 retries] getDeployments({ restApiId: null, limit: 500 })
 
  Serverless Error ---------------------------------------
 
  Missing required key 'restApiId' in params
 
  Stack Trace --------------------------------------------
 
ServerlessError: Missing required key 'restApiId' in params
    at promise.catch.err (/usr/local/lib/node_modules/serverless/lib/plugins/aws/provider/awsProvider.js:302:11)
    at process._tickCallback (internal/process/next_tick.js:68:7)
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com
 
  Your Environment Information ---------------------------
     OS:                     linux
     Node Version:           10.15.3
     Serverless Version:     1.42.2
 
```

**Comment by ozoli** [comment]
I reproduced this error following the instructions for an AWS GoLang example [here](https://github.com/shouldroforion/aws-golang-terraform-colonies)

**Comment by jgordor** [comment]
I had the same problem, in my case, node v10.15.3 serverless 1.42.2, in serverless.yml provider.apiName was set, after removing the custom api name the deploy worked.

**Comment by iabadjiev** [comment]
@medikoo can you please look at https://github.com/serverless/serverless/blob/49650a199cb5cb315fa6c20f6475949215019aa3/lib/plugins/aws/package/compile/events/apiGateway/lib/hack/updateStage.js#L50 I don't think that API name will alway be `${this.options.stage}-${this.serverless.service.service}`

**Comment by jeromegit** [comment]
Same issue with
Your Environment Information ---------------------------
     OS:                     darwin
     Node Version:           10.15.3
     Serverless Version:     1.42.2

**Comment by medikoo** [comment]
We have fix ready at https://github.com/serverless/serverless/pull/6129, still we just want to do some more testing before release, which should take place tomorrow.

Until that's the case please stick to v1.41 (or if you want to test our patch, set version temporarily to `serverless/serverless#fix-restapi-id`)

**Comment by jeromegit** [comment]
Thanks, Mariusz.
I will wait for the next release.

Jérôme  / Blog <http://provensal.com/lbb/> / FB
<https://www.facebook.com/jerome.provensal> / LinkedIn
<http://www.linkedin.com/in/jeromeprovensal> / IG
<http://instagram.com/jeromeig> / Tumblr <http://creativejp.tumblr.com/> /
INTP <http://www.mypersonality.info/personality-types/intp/>

**Comment by medikoo** [comment]
v1.42.3 was just released and that should fix this issue for all cases.

If you still happen to observe some problems, please report with all needed details, needed for us to reproduce on our side.

Thank you!

**Comment by jeromegit** [comment]
Fixed indeed.

You guys are the best!

Jérôme  / Blog <http://provensal.com/lbb/> / FB
<https://www.facebook.com/jerome.provensal> / LinkedIn
<http://www.linkedin.com/in/jeromeprovensal> / IG
<http://instagram.com/jeromeig> / Tumblr <http://creativejp.tumblr.com/> /
INTP <http://www.mypersonality.info/personality-types/intp/>

**Comment by juliankrispel** [comment]
I'm still getting this. Running `1.45.1`

![image](https://user-images.githubusercontent.com/1188186/59450864-1979c400-8e02-11e9-8698-963d19aeb9a5.png)

**Comment by medikoo** [comment]
@juliankrispel thanks for report, still in context of this case, this error should not occur (at worst you'd see `Rest API could not be resolved..` message with further explanations).

Can you run `sls deploy` (or whichever command that produces this error for you) with `SLS_DEBUG=*` env var, so we can see full stack trace?

**Comment by fxrcode** [comment]
I'm still facing this issue in 1.74.1. here's the log with SLS_DEBUG=*.
```
Stack Outputs
GetGroupsLambdaFunctionQualifiedArn: arn:aws:lambda:us-west-1:627950473701:function:serverless-udagram-app-dev-GetGroups:2
CreateGroupLambdaFunctionQualifiedArn: arn:aws:lambda:us-west-1:627950473701:function:serverless-udagram-app-dev-CreateGroup:1
ServiceEndpoint: https://lb40og5wv0.execute-api.us-west-1.amazonaws.com/dev
ServerlessDeploymentBucketName: serverless-udagram-app-d-serverlessdeploymentbuck-1m2by9zakxvsx

Serverless: WARNING: Inappropriate call of provider.request()
Serverless: [AWS cloudformation 200 0.104s 0 retries] describeStacks({ StackName: 'serverless-udagram-app-dev' })
Serverless: [AWS apigateway undefined 0.01s 0 retries] getDocumentationVersion({
  restApiId: undefined,
  documentationVersion: 'bd7d643e9b793c84f1e75ef2ab2a166b7fc67394'
})
 
  Serverless Error ---------------------------------------
 
  ServerlessError: Missing required key 'restApiId' in params
      at /usr/local/lib/node_modules/serverless/lib/plugins/aws/provider/awsProvider.js:326:27
      at processTicksAndRejections (internal/process/task_queues.js:97:5)
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com
 
  Your Environment Information ---------------------------
     Operating System:          linux
     Node Version:              13.14.0
     Framework Version:         1.74.1
     Plugin Version:            3.8.4
     SDK Version:               2.3.2
     Components Version:        2.34.9
 
```
