### ISSUE TITLE
`sls package` is demanding a default profile since the latest version?

### ISSUE THREAD

**Issue by philiiiiiipp** [serverless/serverless#6436]
# This is a Bug Report

Since the last update `sls package` requires a default profile to be set in the aws config ( or `--aws-profile` to be given ).

Not sure why the decision was made to require the aws profile even during packaging, or if this is a bug. 

It is quite anoying to us as we have a number of linting and sanity checks on the generated cf templates for which we would then have to add some aws credentials in our CI/CD for.

## Description

- What went wrong?
Running `sls package` without the default provider set or adding `--aws-profile` breaks. 

- What did you expect should have happened?
It should package the app without the need for the default profile to be set like it did before.

- What was the config you used?
The default one 

```
service: test

provider:
  name: aws
  runtime: nodejs10.x
functions:
  hello:
    handler: handler.hello
```

- What stacktrace or error message from your provider did you see?

```
Unhandled rejection ServerlessError: AWS provider credentials not found. Learn how to set up AWS provider credentials in our docs here: <http://slss.io/aws-creds-setup>.
    at BbPromise.catch.then.identity (/Users/philipp/node/dev/dh/sfa-api/node_modules/serverless/lib/plugins/aws/lib/validate.js:46:19)
    at tryCatcher (/Users/philipp/node/dev/dh/sfa-api/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/philipp/node/dev/dh/sfa-api/node_modules/bluebird/js/release/promise.js:517:31)
    at Promise._settlePromise (/Users/philipp/node/dev/dh/sfa-api/node_modules/bluebird/js/release/promise.js:574:18)
    at Promise._settlePromise0 (/Users/philipp/node/dev/dh/sfa-api/node_modules/bluebird/js/release/promise.js:619:10)
    at Promise._settlePromises (/Users/philipp/node/dev/dh/sfa-api/node_modules/bluebird/js/release/promise.js:699:18)
    at _drainQueueStep (/Users/philipp/node/dev/dh/sfa-api/node_modules/bluebird/js/release/async.js:138:12)
    at _drainQueue (/Users/philipp/node/dev/dh/sfa-api/node_modules/bluebird/js/release/async.js:131:9)
    at Async._drainQueues (/Users/philipp/node/dev/dh/sfa-api/node_modules/bluebird/js/release/async.js:147:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/Users/philipp/node/dev/dh/sfa-api/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
    at process.topLevelDomainCallback (domain.js:126:23)
```

**Comment by aaleksandrov** [comment]
I have similar issue, local invocation was working fine in 1.48.2 but breaks in 1.48.3 because of profile:
We install serverless globally
```
$ yarn global add serverless
yarn global v1.17.3
[1/4] Resolving packages...
warning serverless > json-refs > path-loader > superagent@3.8.3: Please note that v5.0.1+ of superagent removes User-Agent header by default, therefore you may need to add it yourself (e.g. GitHub blocks requests without a User-Agent header).  This notice will go away with v5.0.2+ once it is released.
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
success Installed "serverless@1.48.3" with binaries:
      - serverless
      - slss
      - sls
```
And then call 
```
ENVIRONMENT=test serverless invoke local -f ingestion -d '{"Records":[{"eventSource":"health"}]}' --environment=environments/test.yml

  Error --------------------------------------------------
 
  Profile ci-user does not exist
 
     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com
 
  Your Environment Information ---------------------------
     Operating System:          linux
     Node Version:              8.10.0
     Serverless Version:        1.48.3
     Enterprise Plugin Version: 1.3.2
     Platform SDK Version:      2.1.0
 
Script failed with status 1
```

environments/test.yml: 
```
stage: test
profile: ci-user
```

**Comment by KnupMan** [comment]
The same for me. Works only on `1.48.2`.

**Comment by aaleksandrov** [comment]
@pmuens Could you please change label from `question` to `bug`? Looks like it's a breaking change or bug to be honest

**Comment by dschep** [comment]
Fixed in 1.48.4

**Comment by massa-man** [comment]
I am still seeing this issue in v1.49.0, has this been merged to 1.49?

This is my package log:

```sls package --stage=dev
 
  Error --------------------------------------------------
 
  Profile ra_deploy_dev does not exist
 
     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com
 
  Your Environment Information ---------------------------
     Operating System:          linux
     Node Version:              10.15.3
     Serverless Version:        1.49.0
     Enterprise Plugin Version: 1.3.4
     Platform SDK Version:      2.1.0```

**Comment by philiiiiiipp** [comment]
This actually seems to me like a different bug to me the one I filed. I assume you have `profile: ra_deploy_dev` in your serverless.yml?

For me it was that packaging required a default profile to be set in the aws config or --aws-profile to be given while packaging.

The issue with packaging requiring a profile is fixed for me in the latest version.

**Comment by massa-man** [comment]
Correct, I have a profile defined in my serverless.yml. I am building in my CI in two stages: build stage which setups, tests and packages the project, and a second stage, which deploys.

In the build stage I am not configuring the profile with the AWS CLI because it should not be necessary, and it never was in the past. With v1.49 I now get this error, as it looks the packaging command is validating the profile even though it should not be necessary for anything.

**Comment by massa-man** [comment]
I have done some more testing on this, and the issue appears from v1.48.3 same as the one reported by @philiiiiiipp but is slightly different and does not get solved by this fix. The issue appears to be the same one the @aaleksandrov reported in one of the comments above (he also appears to have a AWS CLI profile defined in his config)

**Comment by aaleksandrov** [comment]
Yes, same issue in 1.48.4, 1.49.* and 1.50.* :(

**Comment by IslamAzab** [comment]
> Fixed in 1.48.4

@dschep It is not fixed for `1.48.4` version, only `1.48.2` worked fine

I can still replicate the error
```
Error --------------------------------------------------

  Profile ci-user does not exist

     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.

  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com

  Your Environment Information ---------------------------
     Operating System:          darwin
     Node Version:              10.15.3
     Serverless Version:        1.48.4
     Enterprise Plugin Version: 1.3.8
     Platform SDK Version:      2.1.0
```

**Comment by philiiiiiipp** [comment]
I am wondering if it is best to create a new issue? Or reopen this one ? @dschep

**Comment by aaleksandrov** [comment]
@philiiiiiipp I guess this one also already reported https://github.com/serverless/serverless/issues/6536

**Comment by philiiiiiipp** [comment]
Ok, in that case the best cause of action seems to follow up there. Good that you made the link 👍
