### ISSUE TITLE
Scheduled Lambdas do not support input parameters

### ISSUE THREAD

**Issue by arabold** [serverless/serverless#661]
In CloudWatch Events you can configure input parameters for your scheduled Lambdas (matched event, part of matched event, constant). Serverless doesn't support that yet.

**Comment by eahefnawy** [comment]
oh shoot right! will make it available in the next release. Thanks for the tip @arabold :blush:

**Comment by eahefnawy** [comment]
this has been fixed in v0.5 :) closing...

**Comment by nicka** [comment]
Hmm still having issues with this. Using version `0.5.1`.

My `s-function.json`:
```
{
  "name": "xxx",
  "runtime": "nodejs",
  "description": "xxx",
  "customName": false,
  "customRole": false,
  "handler": "handler.handler",
  "timeout": 300,
  "memorySize": 1024,
  "authorizer": {},
  "custom": {
    "excludePatterns": []
  },
  "endpoints": [],
  "events": [
    {
      "name": "xxx",
      "type": "schedule",
      "config": {
        "enabled": true,
        "schedule": "rate(5 minutes)",
        "input": {
          "identifier": "${asg_identifier}",
          "dimension": "AutoScalingGroupName",
          "metricName": "CPUUtilization",
          "namespace": "AWS/EC2",
          "unit": "Percent"
        }
      }
    }
  ],
  "environment": {
    "SERVERLESS_PROJECT": "${project}",
    "SERVERLESS_STAGE": "${stage}",
    "SERVERLESS_REGION": "${region}"
  },
  "vpc": {
    "securityGroupIds": [],
    "subnetIds": []
  }
}
```

**Comment by ralphevision** [comment]
Can you please provide an example in YAML to add a constant JSON event input for a scheduled lambda in the serverless.yml (version 1.0.0beta of serverless). Thanks.

**Comment by soumyadash14** [comment]
I am trying to pass in stage information to the scheduled function like this -->

events:
      - schedule:
          rate: rate(1 minute)
          enabled: true
          input:
            stageParams:
              stage: ${opt:stage , self:custom.defaultStage}

But I am not getting these information in the event object in my lambda function.

Can someone please let me know if there is a way to pass in these information to the lambda function ?

**Comment by mthenw** [comment]
@soumyadash14 could you create new issue for that?

**Comment by soumyadash14** [comment]
@mthenw I have created an issue for this.
https://github.com/serverless/serverless/issues/2844
