### ISSUE TITLE
Invoke local keeps hanging after response

### ISSUE THREAD

**Issue by Jonarod** [serverless/serverless#6679]
# This is a Bug Report

## Description

- What went wrong?
After invoking a function locally, the console does not exit, it hangs forever until I CTRL+C.

- What did you expect should have happened?
Should exit after response is sent to stdout.

- What was the config you used?

Here is a sample code using firebase:

```js
const firebase = require('firebase-admin');

async function main(params) {
  if (!firebase.apps.length) {
    firebase.initializeApp({
      credential: firebase.credential.cert(params.FIREBASE_SERVICE_ACCOUNT),
      databaseURL: params.FIREBASE_DATABASE_URL
    });
  }

  let user = await firebase.auth().createUser({
    email: "deleteme@email.com",
    emailVerified: false,
    displayName: "Delete Me TEST",
    disabled: false,
  })
  
  return user
}
```
Then invoking it like this:

```
sls invoke local -f my_function
```
results in the intended function working and logging properly, but the console hangs forever without exiting the action.

Interestingly, if I simulate the same use case using `setTimeout()` the issue is not reproduced. For example this works and exits correctly:
```js
async function main(params) {
  const user = await new Promise( (resolve) => {
    setTimeout(()=> {
       resolve({status: 'OK'})
    }, 2000)
  })
  return user
}
```

- What stacktrace or error message from your provider did you see?
Nothing. The console shows the expected output (a "user" object in the example provided), but it hangs without closing and any further message.

Similar or dependent issues:

- #5446 

## Additional Data

- **_Serverless Framework Version you're using_**: 1.52.0
- **_Operating System_**: Ubuntu
- **_Stack Trace_**: N/A
- **_Provider Error messages_**: N/A

**Comment by martrik** [comment]
I'm having the same issue with version `1.52.0` and an async inside the function.

**Comment by paul-ridgway** [comment]
It looks like this might have been introduced in the `1.48.1` release

**Comment by martrik** [comment]
Actually, in my case the problem is that I've got a MongoDB connection that should be kept open between executions. However, even when using `callbackwaitsforemptyeventloop = false` the lambda still hangs.

**Comment by paul-ridgway** [comment]
Ah I see, for me there has been no code change, it broke on updating the version so I stepped back to find out when the behaviour appears to have changed...

**Comment by martrik** [comment]
Interesting! For me this is a new service that I was creating so I wasn't really sure if the issue originated from my code or serverless'. Anyways, let's see if we can get the attention of any maintainer 😄

**Comment by QAnders** [comment]
On 1.53.0 and having the same issue...

**Comment by QAnders** [comment]
Still there on 1.54.0...
![slow-serverless-return](https://user-images.githubusercontent.com/12028885/67005369-b74c0b00-f0e2-11e9-8800-2b48f92786c4.gif)

**Comment by stellalie** [comment]
Yes, I got the same issue :) - Please fix this.

**Comment by selected-pixel-jameson** [comment]
Having the same issue on 1.54.0.

**Comment by QAnders** [comment]
Still hanging on 1.55.1, although it seems to not "freeze" for as long now...

**Comment by mstrazzini** [comment]
I have an entire project on hold because of this bug, so PLEASE fix it.

**Comment by mstrazzini** [comment]
The setTimeout() trick didn't work for me. Although it doesn't seem to affect deployed functions at all (sls invoke to the deployed functions works fine), so this is not really as urgent as I thought, but it is still annoying.

**Comment by selected-pixel-jameson** [comment]
Yes. It is super annoying having to cmd+. every time I run the function. But yes,Just annoying not breaking anything.

**Comment by tcastelli** [comment]
Same problem here :(

**Comment by KingDarBoja** [comment]
Maybe you guys could try setting some dummy data as stated on [this issue](https://github.com/serverless/serverless-google-cloudfunctions/issues/129).

Something like:
`serverless invoke local -f functioname -l --data {}`

**Comment by jimcamut** [comment]
I've been having the same issue on 1.60.5 and other recent version. 

*Here's a solution that's less than ideal, but still a solution:*

1) `yarn add serverless@1.48.0 -D` or `npm install  serverless@1.48.0 --save-dev`
2) In your serverless.yml file add `frameworkVersion: '=1.48.0'`

This will force your local serverless version to run on version 1.48.0 which appears to be the last version released before the bug was introduced. This solution is less than ideal, but it's the only thing that's working for me.

**Comment by abhishekover9000** [comment]
I'm also facing this bug

**Comment by mstrazzini** [comment]
Looks like it was fixed on latest version.

**Comment by abhishekover9000** [comment]
Just pulled the latest from npm, and it still hangs on git-bash on windows 10 x64

**Comment by abhishekover9000** [comment]
> Maybe you guys could try setting some dummy data as stated on [this issue](https://github.com/serverless/serverless-google-cloudfunctions/issues/129).
> 
> Something like:
> `serverless invoke local -f functioname -l --data {}`

this actually solves it

**Comment by mstrazzini** [comment]
Weird. My latest pulled from npm (on win64 too) solved the issue.

**Comment by QAnders** [comment]
This was fixed but is now back again in the latest release, 1.63.0... :(

**Comment by mstrazzini** [comment]
Yeah. It's back again here too... But I got used to it already. Just do a
CTRL+C once the invoke local hangs.

**Comment by balassit** [comment]
Facing the same issue on 1.64.0. Please add support for this as it breaks CI/CD builds.

**Comment by escar** [comment]
Still happens on 1.64.1. 
It seems it only hangs when executing async code in the handler.

**Comment by escar** [comment]
Running 1.64.1 here.
I believe this is not a problem with serverless. If using firebase, you have to delete the app once you're finished:

```
firebase.app().delete();
```

**Comment by jdchmiel** [comment]
just checked in on this issue.
`serverless invoke local  --function adHoc -l --data {}`
does not work for 1.67 and I am not using firebase.

**Comment by jdchmiel** [comment]
Still here for 1.73. invoking a deployed lambda is fine, just local that hangs.  Does anyone have a work around?  I need to invoke in a bash a for loop a few hundred times to fake data from an  SQS queue.

**Comment by jimcamut** [comment]
@jdchmiel I'm using a hack right now to get around this:

1. `yarn add serverless@1.48.0 -D` add version 1.48.0 as a dev dependency
2. In the serverless.yaml file you use to run locally, add `frameworkVersion: '=1.48.0'` to force it to run 1.48.0.

This will run version 1.48.0 locally for you and things won't hang. This version is the latest before the hanging issue started. I'm also still patiently waiting for a fix, and using this hack to run SLS locally for development purposes, while deploying updated serverless versions to production.

**Comment by nmklotas** [comment]
having the same issue with:
```
PS C:\Users\nemok\source\repos\invoices\api> serverless --version                                      
Serverless: DOTENV: Loading environment variables from .env:
Serverless:      - MONGODB_CONNECTION_URL
Serverless:      - iss
Framework Core: 1.78.1
Plugin: 3.7.0
SDK: 2.3.1
Components: 2.34.1
PS C:\Users\nemok\source\repos\invoices\api> 
```

**Comment by chandrakommuri** [comment]
same issue in 1.80.0 as well

**Comment by pradeepngupta** [comment]
Any update on this issue?
I am facing the same issue with:
Your Environment Information ---------------------------
     Operating System:          win32
     Node Version:              12.18.1
     Framework Version:         2.1.1
     Plugin Version:            4.0.4
     SDK Version:               2.3.2
     Components Version:        3.1.3

Even the expected output is not coming:
$ sls invoke local -f hello
Serverless: Running "serverless" installed locally (in service node_modules)
Serverless: DOTENV: Loading environment variables from .env:

**Comment by mstrazzini** [comment]
It seems the only way to really fix this is to stop using sls framework at
all and rethinking your backend. Do that and be happy.

Em seg, 21 de set de 2020 18:04, pradeepngupta <notifications@github.com>
escreveu:

**Comment by okonon** [comment]
same issue here 
```
  Your Environment Information ---------------------------
     Operating System:          darwin
     Node Version:              12.16.3
     Framework Version:         2.2.0 (local)
     Plugin Version:            4.0.4
     SDK Version:               2.3.2
     Components Version:        3.1.4
```

**Comment by huangweijin** [comment]
Any update? This is blocking me to use. the server-mocha-plugin which hangs after the tests are executed.

**Comment by danmoore83** [comment]
Been having this issue past few days in both Serverless Offline and the deployed Lambda on AWS.
The Firebase database connection keeps the process running, and simply adding the following worked after my firebase usage was done.
`firebase.app().delete()`

**Comment by smcelhinney** [comment]
For me, my issue was a Redis connection that was kept open, so the symptom seems to be that if client connections (of any kind) are not forcefully quit, it will remain open. In my case, I had to `client.quit()` to close the connection. 

Hope this helps someone else diagnose similar issues!

**Comment by codebravotech** [comment]
> For me, my issue was a Redis connection that was kept open, so the symptom seems to be that if client connections (of any kind) are not forcefully quit, it will remain open. In my case, I had to `client.quit()` to close the connection.
> 
> Hope this helps someone else diagnose similar issues!

This was the issue for me also, I had a connection open to a MYSQL db that needed to be closed.

**Comment by jespinoza-sp** [comment]
> > For me, my issue was a Redis connection that was kept open, so the symptom seems to be that if client connections (of any kind) are not forcefully quit, it will remain open. In my case, I had to `client.quit()` to close the connection.
> > Hope this helps someone else diagnose similar issues!
> 
> This was the issue for me also, I had a connection open to a MYSQL db that needed to be closed.

Thanks! I'm using TypeORM and destroying the connection before returning the data solved the issue for me

**Comment by karltaylor** [comment]
> Actually, in my case the problem is that I've got a MongoDB connection that should be kept open between executions. However, even when using `callbackwaitsforemptyeventloop = false` the lambda still hangs.

Having the same problem with @martrik here...

I'm using serverless `4.4.4` and `runtime: nodejs20.x`.

I've got an API Gateway lambda that is using a cachedConnection function. When running `serverless dev` the application will spin up - the connection connects (readyState === 1). However, the lambda in dev mode will **not** return successfully even with `callbackWaitsForEmptyEventLoop`.

To fix this in **_development_** I have to use `mongooseConnection.connection.close()` and the lambda will return correctly.

I have deployed the code successfully **without** closing the connection, and it works fine.
