### ISSUE TITLE
v0.5 - Crash on `serverless function logs`

### ISSUE THREAD

**Issue by jordanmack** [serverless/serverless#857]
From within a function folder: `sls function logs`

```
TypeError: Cannot read property 'getDeployedName' of undefined
    at FunctionLogs._validateAndPrepare (/home/username/Desktop/serverless/lib/actions/FunctionLogs.js:126:39)
```

**Comment by jordanmack** [comment]
This is on the most recent commit in the v0.5 branch: 53b8b7b4f37f85eeffe2cb14d7a0497bd8612df4

**Comment by HyperBrain** [comment]
Checked with the latest v0.5 checkout (3474048f924a39b7244b43cb2cd80fbe7619ee6a).
(1) Deployed function: `sls function deploy testfct`
(2) Ran function once through AWS console
(3) `sls function logs testfct` from project dir
=> Correct output:
```
START RequestId: 2367b47d-f010-11e5-b194-0bcd942e918c Version: 9
END RequestId: 2367b47d-f010-11e5-b194-0bcd942e918c
REPORT RequestId: 2367b47d-f010-11e5-b194-0bcd942e918c  Duration: 1.74 ms       Billed Duration: 100 ms         Memory Size: 1024 MB    Max Memory Used: 8 MB
```
(4) `sls function logs` from testfct dir
=> Correct output:
```
START RequestId: 2367b47d-f010-11e5-b194-0bcd942e918c Version: 9
END RequestId: 2367b47d-f010-11e5-b194-0bcd942e918c
REPORT RequestId: 2367b47d-f010-11e5-b194-0bcd942e918c  Duration: 1.74 ms       Billed Duration: 100 ms         Memory Size: 1024 MB    Max Memory Used: 8 MB
```

Could you please check your `s-project.json` or your `s-function.json`? Maybe it only happens when special conditions are met.

**Comment by ac360** [comment]
I believe this is a result of the `project` variable not being set correctly on project create.  This is now fixed in `v0.5`.

**Comment by jordanmack** [comment]
@HyperBrain As we discussed earlier, just for the record, this still occurs on 3474048f924a39b7244b43cb2cd80fbe7619ee6a. 

@ac360 I'm still getting it with the latest  version on master 2159533ba3e9b79d0a6fcc402a3e2c070c0d23a2. I believe the cause of this is related to the function name not matching the folder name. This may be one of those cases where the two haven't been decoupled yet.

**Comment by minibikini** [comment]
>  I believe the cause of this is related to the function name not matching the folder name. 

@jordanmack you were right, thank you!

**Comment by aexmachina** [comment]
This is happening for me in v0.5.5, and the function name _does_ match the folder name. I think this was previously working too.
