### ISSUE TITLE
A null in serverless.yml

### ISSUE THREAD

**Issue by alexshelkov** [serverless/serverless#8935]
The AWS Cognito have an `EnabledMfas` option and it must not exist in config if `MfaConfiguration` is OFF. So I need to remove it from resource config by seting `EnabledMfas = null (or undefined)`

<details>
<summary><code>serverless.yml</code></summary>

```yaml
frameworkVersion: ">= 2.16.0"

service: mailtumble-next-auth

useDotenv: true

resources:
  Resources:
    # --------------------------------------------------------------------
    # Resources
    # --------------------------------------------------------------------
    CognitoUserPool:
      Type: AWS::Cognito::UserPool
      Properties:
        UserPoolName: name
        UsernameAttributes:
          - email
        AutoVerifiedAttributes:
          - email
        MfaConfiguration: OFF 
        EnabledMfas: null # As MfaConfiguration is OFF we need to remove EnabledMfas or it will not be a valid option
        AccountRecoverySetting:
          RecoveryMechanisms:
            - Name: verified_email
              Priority: 1
            - Name: verified_phone_number
              Priority: 2
        Policies:
          PasswordPolicy:
            MinimumLength: 6
            RequireLowercase: false
            RequireSymbols: false
            RequireNumbers: false
            RequireUppercase: false
        VerificationMessageTemplate:
          DefaultEmailOption: CONFIRM_WITH_LINK

```

</details>

<details>
<summary><b><code>sls deploy -s dev</code> output</b></summary>

```
  Error: The CloudFormation template is invalid: [/Resources/CognitoUserPool/Type/EnabledMfas] 'null' values are not allowed in templates
```

</details>

<b>Installed version</b>

```
Framework Core: 2.16.0
Plugin: 4.3.0
SDK: 2.3.2
Components: 3.4.3
```

**Comment by pgrzesik** [comment]
Thanks for reporting @alexshelkov :bow: After discussing with @medikoo, we believe that the best way to move forward is to allow setting `null` values in `serverless.yml` that during internal processing will be stripped from the final `CloudFormation` template. 

## Implementation proposal
1. Add a new utility e.g `strip-null-properties-from-template` in `lib/plugins/aws/package/lib` which will iterate over properties of all resources and remove the values that are set to `null`
2. Introduce the use of the mentioned utility in https://github.com/serverless/serverless/blob/1eaa6260aa9f747d0aa01006ce54d3313e7b7e0f/lib/plugins/aws/package/index.js#L78, after `mergeCustomProviderResources` is called. 
3. Test the functionality with `runServerless`

We'd be more than happy to accept a PR for this one :raised_hands:

**Comment by yumeixox** [comment]
@pgrzesik @medikoo can I take this?

**Comment by pgrzesik** [comment]
That would be amazing @yumeixox :raised_hands: Thank you :bow: If you have any questions, feel free to let us know :100:

**Comment by yumeixox** [comment]
@alexshelkov @pgrzesik I'm a little confused, why not just remove EnabledMfas from the config?

**Comment by mahdisaadaat** [comment]
hi, can i do anything about it?

**Comment by alexshelkov** [comment]
> @alexshelkov @pgrzesik I'm a little confused, why not just remove EnabledMfas from the config?

Imagine that your `MfaConfiguration` is set via env var, and it can be on or off for some environments. So you have to change `EnabledMfas` based on `MfaConfiguration`. Valid values for `EnabledMfas` is a list string or not existing in the config (ie null). So in case of `MfaConfiguration = OFF` =>  `EnabledMfas` have to be `null` or you will get AWS errors. There are a lot of similar use cases where AWS don't support anything except not existing settings.

**Comment by yumeixox** [comment]
Ah I see, that makes sense. I'll be working on that implementation.

**Comment by pgrzesik** [comment]
To add to what @alexshelkov, it is also to ensure that at the end of the process, all `null` properties from final CF template will be stripped. That will allow to avoid some unnecessary internal logic that ensures that separately for each field (it's easy to miss that and introduce a potential bug), so it's a very valuable feature :+1: If you have any further questions, feel free to let us know :bow:

**Comment by pgrzesik** [comment]
Hello @alexshelkov - we just merged a PR that adds support for stripping properties defined as `null` - it should be released with the next version of the Framework. I'm closing this issue for now - if you'll experience issues after the new version gets released, please let us know :100:

**Comment by alexshelkov** [comment]
@pgrzesik I think the problem is still there. If I try to get config from: `${self:custom.mfa.methods}`, it will shows an error: `Cannot resolve variable at "resources.Resources.CognitoUserPool.Properties.EnabledMfas": Value not found at "self" source`

**Comment by pgrzesik** [comment]
I believe that might be related to recent changes to variables parser/resolver. If I'm not mistaken, you need to provide fallback value of `null` in such case - so it should be `${self:custom.mfa.methods, null}` - I've tested locally and I believe it should work. Please let me know

**Comment by alexshelkov** [comment]
Yes, it works but it fails again in more complex situation: `${self:custom.mfa.methods.${self:custom.mfa.status}, null}` here is we use one var depend on another.

**Comment by medikoo** [comment]
@alexshelkov in this case, to have `${self:custom.mfa.methods.${self:custom.mfa.status}, null} ` resolved, you need to ensure that `${self:custom.mfa.status}` resolves to some string value.

Otherwise it'll be seen as error, note that `${self:custom.mfa.status}` is configured to be part of string (by variables parser everything that goes after `:` is treated as one value, it's then the source resolver (in this case `self`), that parses the value and gets meaning of it.

One idea that comes to my mind is to hack it a bit, so it's: `${self:custom.mfa.methods.${self:custom.mfa.status, 'n/a'}, null}`
Having that in case of `self:custom.mfa.status` missing, it'll fallback to `n/a` strings, so it'll attempt to access `custom.mfa.methods['n/a']` propertym which will not exist, and `null` will resolve.

It's not perfectly clean, but at this point I cannot think of better solution. Ideally would be if you refactor from such nested variables resolution to more flat leveled solution.

**Comment by alexshelkov** [comment]
@medikoo I am sure that `${self:custom.mfa.status}` resolves to string and the problem is that `${self:custom.mfa.methods.${self:custom.mfa.status}}` resolve to null. As soon as it is not null then everything is working, but null produce and error: `A valid service attribute to satisfy the declaration 'self:custom.mfa.OFF,null' could not be found.` -- as you can see `${self:custom.mfa.status}` is resolved to OFF which is valid string.

**Comment by medikoo** [comment]
@alexshelkov  Problem is not perfectly clear to me. Let's maybe speak of concrete case, e.g. following template resolves for me as expected (`custom.test` ends with `null` value, and there are no resolution errors reported):

```yaml
custom:
  mfa:
    status: "OFF"
    methods:
      foo: bar
  test: ${self:custom.mfa.methods.${self:custom.mfa.status}, null}
```

What exactly is problem on your side?

**Comment by alexshelkov** [comment]
@medikoo please try read status from env like that: `${env:STATUS, 'OFF'}`;

**Comment by medikoo** [comment]
> @medikoo please try read status from env like that: ${env:STATUS, 'OFF'}.

Indeed it fails in this case. Situation is that at this point new variables resolver covers just partial resolution (and resolution from `env` source is subject to that). Having that, your input is considered as not resolvable by new resolver, so resolution fallbacks to old variable resolver (one that back Framework since very early days), which doesn't handle that notation well.

In first days of next week we will issue an update with full resolution from `env` sources, and then it'll start working for you in that form
